/*
**
** The C code is generated by ATS/Postiats
** The starting compilation time is: 2014-11-25:  2h:33m
**
*/

/*
** include runtime header files
*/
#ifndef _ATS_CCOMP_HEADER_NONE
#include "pats_ccomp_config.h"
#include "pats_ccomp_basics.h"
#include "pats_ccomp_typedefs.h"
#include "pats_ccomp_instrset.h"
#include "pats_ccomp_memalloc.h"
#ifndef _ATS_CCOMP_EXCEPTION_NONE
#include "pats_ccomp_memalloca.h"
#include "pats_ccomp_exception.h"
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE]
#endif /* _ATS_CCOMP_HEADER_NONE */


/*
** include prelude cats files
*/
#ifndef _ATS_CCOMP_PRELUDE_NONE
//
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/integer_ptr.cats"
#include "prelude/CATS/integer_fixed.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/memory.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/strptr.cats"
//
#include "prelude/CATS/filebas.cats"
//
#include "prelude/CATS/list.cats"
#include "prelude/CATS/option.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/arrayptr.cats"
#include "prelude/CATS/arrayref.cats"
#include "prelude/CATS/matrix.cats"
#include "prelude/CATS/matrixptr.cats"
//
#endif /* _ATS_CCOMP_PRELUDE_NONE */
/*
** for user-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER
//
#include _ATS_CCOMP_PRELUDE_USER
//
#endif /* _ATS_CCOMP_PRELUDE_USER */

/*
staload-prologues(beg)
*/
/*
staload-prologues(end)
*/
/*
typedefs-for-tyrecs-and-tysums(beg)
*/
typedef
ATSstruct {
atstkind_t0ype(atstype_int) atslab__0 ;
atstkind_t0ype(atstype_int) atslab__1 ;
} postiats_tyrec_0 ;
/*
typedefs-for-tyrecs-and-tysums(end)
*/
/*
dynconlst-declaration(beg)
*/
/*
dynconlst-declaration(end)
*/
/*
dyncstlst-declaration(beg)
*/
ATSdyncst_extfun(_057_home_057_alex_057_workspace_057_Postiats_057_projects_057_utfpl_057_src_057_jats_057_utfpl_057_stfpl_057_test_057_conats_056_sats__conats_shared_create, (atstyvar_type(a)), shared_t(atstyvar_type(a))) ;
ATSdyncst_extfun(_057_home_057_alex_057_workspace_057_Postiats_057_projects_057_utfpl_057_src_057_jats_057_utfpl_057_stfpl_057_test_057_conats_056_sats__conats_shared_acquire, (shared_t(atstyvar_type(a))), atstyvar_type(a)) ;
ATSdyncst_extfun(_057_home_057_alex_057_workspace_057_Postiats_057_projects_057_utfpl_057_src_057_jats_057_utfpl_057_stfpl_057_test_057_conats_056_sats__conats_shared_signal, (shared_t(atstyvar_type(a)), atstyvar_type(a)), atstyvar_type(a)) ;
ATSdyncst_extfun(_057_home_057_alex_057_workspace_057_Postiats_057_projects_057_utfpl_057_src_057_jats_057_utfpl_057_stfpl_057_test_057_conats_056_sats__conats_shared_release, (shared_t(atstyvar_type(a)), atstyvar_type(a)), atsvoid_t0ype) ;
ATSdyncst_extfun(_057_home_057_alex_057_workspace_057_Postiats_057_projects_057_utfpl_057_src_057_jats_057_utfpl_057_stfpl_057_test_057_conats_056_sats__conats_shared_condwait, (shared_t(atstyvar_type(a)), atstyvar_type(a)), atstyvar_type(a)) ;
/*
dyncstlst-declaration(end)
*/
/*
dynvalist-implementation(beg)
*/
/*
dynvalist-implementation(end)
*/
/*
exnconlst-declaration(beg)
*/
#ifndef _ATS_CCOMP_EXCEPTION_NONE
ATSextern()
atsvoid_t0ype
the_atsexncon_initize
(
  atstype_exnconptr d2c, atstype_string exnmsg
) ;
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE]
/*
exnconlst-declaration(end)
*/
/*
assumelst-declaration(beg)
*/
/*
assumelst-declaration(end)
*/
/*
extypelst-declaration(beg)
*/
/*
extypelst-declaration(end)
*/
ATSstatmpdec(statmp0, shared_t(atstkind_t0ype(atstype_int))) ;
ATSstatmpdec(statmp1, postiats_tyrec_0) ;
ATSstatmpdec(statmp2, atstkind_t0ype(atstype_int)) ;
ATSstatmpdec(statmp3, atstkind_t0ype(atstype_int)) ;
ATSstatmpdec_void(statmp4) ;
ATSstatmpdec(statmp5, atstkind_t0ype(atstype_int)) ;
/*
** for initialization(dynloading)
*/
ATSextern()
atsvoid_t0ype
_057_home_057_alex_057_workspace_057_Postiats_057_projects_057_utfpl_057_src_057_jats_057_utfpl_057_stfpl_057_test_057_15_thread_cond_056_dats__dynload()
{
ATSfunbody_beg()
ATSdynload(/*void*/)
ATSdynloadflag_ext(
_057_home_057_alex_057_workspace_057_Postiats_057_projects_057_utfpl_057_src_057_jats_057_utfpl_057_stfpl_057_test_057_15_thread_cond_056_dats__dynloadflag
) ;
ATSif(
ATSCKiseqz(
_057_home_057_alex_057_workspace_057_Postiats_057_projects_057_utfpl_057_src_057_jats_057_utfpl_057_stfpl_057_test_057_15_thread_cond_056_dats__dynloadflag
)
) ATSthen() {
ATSdynloadset(_057_home_057_alex_057_workspace_057_Postiats_057_projects_057_utfpl_057_src_057_jats_057_utfpl_057_stfpl_057_test_057_15_thread_cond_056_dats__dynloadflag) ;
/*
dynexnlst-initize(beg)
*/
/*
dynexnlst-initize(end)
*/
/*
emit_instr: loc0 = /home/alex/workspace/Postiats/projects/utfpl/src/jats/utfpl/stfpl/test/15_thread_cond.dats: 36(line=5, offs=9) -- 63(line=5, offs=36)
*/
ATSINSmove(statmp0, _057_home_057_alex_057_workspace_057_Postiats_057_projects_057_utfpl_057_src_057_jats_057_utfpl_057_stfpl_057_test_057_conats_056_sats__conats_shared_create(ATSPMVi0nt(0))) ;

/*
emit_instr: loc0 = /home/alex/workspace/Postiats/projects/utfpl/src/jats/utfpl/stfpl/test/15_thread_cond.dats: 78(line=7, offs=13) -- 84(line=7, offs=19)
*/
ATSINSmove_fltrec_beg()
ATSINSstore_fltrec_ofs (statmp1, postiats_tyrec_0, atslab__0, ATSPMVi0nt(1)) ;
ATSINSstore_fltrec_ofs (statmp1, postiats_tyrec_0, atslab__1, ATSPMVi0nt(2)) ;
ATSINSmove_fltrec_end()
/*
emit_instr: loc0 = /home/alex/workspace/Postiats/projects/utfpl/src/jats/utfpl/stfpl/test/15_thread_cond.dats: 98(line=9, offs=13) -- 122(line=9, offs=37)
*/
ATSINSmove(statmp2, _057_home_057_alex_057_workspace_057_Postiats_057_projects_057_utfpl_057_src_057_jats_057_utfpl_057_stfpl_057_test_057_conats_056_sats__conats_shared_acquire(statmp0)) ;

/*
emit_instr: loc0 = /home/alex/workspace/Postiats/projects/utfpl/src/jats/utfpl/stfpl/test/15_thread_cond.dats: 132(line=10, offs=9) -- 159(line=10, offs=36)
*/
ATSINSmove(statmp3, _057_home_057_alex_057_workspace_057_Postiats_057_projects_057_utfpl_057_src_057_jats_057_utfpl_057_stfpl_057_test_057_conats_056_sats__conats_shared_signal(statmp0, statmp2)) ;

/*
emit_instr: loc0 = /home/alex/workspace/Postiats/projects/utfpl/src/jats/utfpl/stfpl/test/15_thread_cond.dats: 169(line=11, offs=10) -- 197(line=11, offs=38)
*/
ATSINSmove_void(statmp4, _057_home_057_alex_057_workspace_057_Postiats_057_projects_057_utfpl_057_src_057_jats_057_utfpl_057_stfpl_057_test_057_conats_056_sats__conats_shared_release(statmp0, statmp3)) ;

/*
emit_instr: loc0 = /home/alex/workspace/Postiats/projects/utfpl/src/jats/utfpl/stfpl/test/15_thread_cond.dats: 206(line=12, offs=9) -- 235(line=12, offs=38)
*/
ATSINSmove(statmp5, _057_home_057_alex_057_workspace_057_Postiats_057_projects_057_utfpl_057_src_057_jats_057_utfpl_057_stfpl_057_test_057_conats_056_sats__conats_shared_condwait(statmp0, statmp3)) ;

} /* ATSendif */
ATSfunbody_end()
ATSreturn_void(tmpret_void) ;
} /* end of [*_dynload] */

/* ****** ****** */

/* end-of-compilation-unit */
