/*
**
** The C code is generated by ATS/Postiats
** The compilation time is: 2014-7-15: 12h:49m
**
*/

/*
** include runtime header files
*/
#ifndef _ATS_CCOMP_HEADER_NONE
#include "pats_ccomp_config.h"
#include "pats_ccomp_basics.h"
#include "pats_ccomp_typedefs.h"
#include "pats_ccomp_instrset.h"
#include "pats_ccomp_memalloc.h"
#ifndef _ATS_CCOMP_EXCEPTION_NONE
#include "pats_ccomp_memalloca.h"
#include "pats_ccomp_exception.h"
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE]
#endif /* _ATS_CCOMP_HEADER_NONE */


/*
** include prelude cats files
*/
#ifndef _ATS_CCOMP_PRELUDE_NONE
//
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/integer_ptr.cats"
#include "prelude/CATS/integer_fixed.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/memory.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/strptr.cats"
//
#include "prelude/CATS/filebas.cats"
//
#include "prelude/CATS/list.cats"
#include "prelude/CATS/option.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/arrayptr.cats"
#include "prelude/CATS/arrayref.cats"
#include "prelude/CATS/matrix.cats"
#include "prelude/CATS/matrixptr.cats"
//
#endif /* _ATS_CCOMP_PRELUDE_NONE */
/*
** for user-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER
//
#include _ATS_CCOMP_PRELUDE_USER
//
#endif /* _ATS_CCOMP_PRELUDE_USER */

/*
staload-prologues(beg)
*/
/*
staload-prologues(end)
*/
/*
typedefs-for-tyrecs-and-tysums(beg)
*/
/*
typedefs-for-tyrecs-and-tysums(end)
*/
/*
dynconlst-declaration(beg)
*/
/*
dynconlst-declaration(end)
*/
/*
dyncstlst-declaration(beg)
*/
ATSdyncst_extfun(_057_home_057_grad2_057_aren_057_workspace_057_Postiats_057_projects_057_utfpl_057_test_057_ats_testbed_057_06_056_dats__foo1, (), atstkind_t0ype(atstype_int)) ;
ATSdyncst_mac(atspre_print_string)
ATSdyncst_mac(atspre_print_int)
ATSdyncst_mac(atspre_print_newline)
/*
dyncstlst-declaration(end)
*/
/*
dynvalist-implementation(beg)
*/
/*
dynvalist-implementation(end)
*/
/*
exnconlst-declaration(beg)
*/
#ifndef _ATS_CCOMP_EXCEPTION_NONE
extern void the_atsexncon_initize (atstype_exncon *d2c, char *exnmsg) ;
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE]
/*
exnconlst-declaration(end)
*/
/*
assumelst-declaration(beg)
*/
/*
assumelst-declaration(end)
*/
/*
extypelst-declaration(beg)
*/
/*
extypelst-declaration(end)
*/
ATSstaticdec()
atsvoid_t0ype
foo_0() ;

#if(0)
ATSglobaldec()
atstkind_t0ype(atstype_int)
_057_home_057_grad2_057_aren_057_workspace_057_Postiats_057_projects_057_utfpl_057_test_057_ats_testbed_057_06_056_dats__foo1(atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]

ATSstaticdec()
atstkind_t0ype(atstype_int)
foo2_2(atstkind_t0ype(atstype_int)) ;

#if(0)
ATSglobaldec()
atsvoid_t0ype
mainats_void_0() ;
#endif // end of [QUALIFIED]

/*
/home/grad2/aren/workspace/Postiats/projects/utfpl/test/ats_testbed/06.dats: 47(line=4, offs=5) -- 263(line=18, offs=4)
*/
/*
local: 
global: foo_0$0(level=0)
local: 
global: 
*/
ATSstaticdec()
atsvoid_t0ype
foo_0()
{
/* tmpvardeclst(beg) */
ATStmpdec_void(tmpret0, atsvoid_t0ype) ;
ATStmpdec(tmp2, atstkind_t0ype(atstype_int)) ;
ATStmpdec_void(tmp3, atsvoid_t0ype) ;
ATStmpdec_void(tmp4, atsvoid_t0ype) ;
ATStmpdec_void(tmp5, atsvoid_t0ype) ;
ATStmpdec(tmp7, atstkind_t0ype(atstype_int)) ;
ATStmpdec_void(tmp8, atsvoid_t0ype) ;
ATStmpdec_void(tmp9, atsvoid_t0ype) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /home/grad2/aren/workspace/Postiats/projects/utfpl/test/ats_testbed/06.dats: 47(line=4, offs=5) -- 263(line=18, offs=4)
*/
__patsflab_foo_0:
/*
emit_instr: loc0 = /home/grad2/aren/workspace/Postiats/projects/utfpl/test/ats_testbed/06.dats: 62(line=4, offs=20) -- 263(line=18, offs=4)
*/
/*
letpush(beg)
*/
/* (*nothing*) */
/*
emit_instr: loc0 = /home/grad2/aren/workspace/Postiats/projects/utfpl/test/ats_testbed/06.dats: 142(line=10, offs=11) -- 149(line=10, offs=18)
*/
ATSINSmove(tmp2, _057_home_057_grad2_057_aren_057_workspace_057_Postiats_057_projects_057_utfpl_057_test_057_ats_testbed_057_06_056_dats__foo1()) ;

/*
emit_instr: loc0 = /home/grad2/aren/workspace/Postiats/projects/utfpl/test/ats_testbed/06.dats: 161(line=11, offs=12) -- 181(line=11, offs=32)
*/
ATSINSmove_void(tmp3, atspre_print_string(ATSPMVstring("y = "))) ;

/*
emit_instr: loc0 = /home/grad2/aren/workspace/Postiats/projects/utfpl/test/ats_testbed/06.dats: 161(line=11, offs=12) -- 181(line=11, offs=32)
*/
ATSINSmove_void(tmp4, atspre_print_int(tmp2)) ;

/*
emit_instr: loc0 = /home/grad2/aren/workspace/Postiats/projects/utfpl/test/ats_testbed/06.dats: 161(line=11, offs=12) -- 181(line=11, offs=32)
*/
ATSINSmove_void(tmp5, atspre_print_newline()) ;

/*
emit_instr: loc0 = /home/grad2/aren/workspace/Postiats/projects/utfpl/test/ats_testbed/06.dats: 217(line=15, offs=11) -- 224(line=15, offs=18)
*/
ATSINSmove(tmp7, foo2_2(ATSPMVi0nt(6))) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/grad2/aren/workspace/Postiats/projects/utfpl/test/ats_testbed/06.dats: 236(line=16, offs=12) -- 256(line=16, offs=32)
*/
ATSINSmove_void(tmp8, atspre_print_string(ATSPMVstring("z = "))) ;

/*
emit_instr: loc0 = /home/grad2/aren/workspace/Postiats/projects/utfpl/test/ats_testbed/06.dats: 236(line=16, offs=12) -- 256(line=16, offs=32)
*/
ATSINSmove_void(tmp9, atspre_print_int(tmp7)) ;

/*
emit_instr: loc0 = /home/grad2/aren/workspace/Postiats/projects/utfpl/test/ats_testbed/06.dats: 236(line=16, offs=12) -- 256(line=16, offs=32)
*/
ATSINSmove_void(tmpret0, atspre_print_newline()) ;

/*
emit_instr: loc0 = /home/grad2/aren/workspace/Postiats/projects/utfpl/test/ats_testbed/06.dats: 62(line=4, offs=20) -- 263(line=18, offs=4)
*/
/*
INSletpop()
*/
/* funbodyinstrlst(end) */
ATSreturn_void(tmpret0) ;
} /* end of [foo_0] */

/*
/home/grad2/aren/workspace/Postiats/projects/utfpl/test/ats_testbed/06.dats: 122(line=8, offs=18) -- 128(line=8, offs=24)
*/
/*
local: 
global: foo1$1$0(level=1)
local: x$63(1)(HSEapp(HSEcst(atstkind_t0ype); HSEs2exp(S2Eextkind(atstype_int))))
global: x$63(1)(HSEapp(HSEcst(atstkind_t0ype); HSEs2exp(S2Eextkind(atstype_int))))
*/
ATSglobaldec()
atstkind_t0ype(atstype_int)
_057_home_057_grad2_057_aren_057_workspace_057_Postiats_057_projects_057_utfpl_057_test_057_ats_testbed_057_06_056_dats__foo1(atstkind_t0ype(atstype_int) env0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret1, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /home/grad2/aren/workspace/Postiats/projects/utfpl/test/ats_testbed/06.dats: 117(line=8, offs=13) -- 128(line=8, offs=24)
*/
__patsflab_foo1:
/*
emit_instr: loc0 = /home/grad2/aren/workspace/Postiats/projects/utfpl/test/ats_testbed/06.dats: 127(line=8, offs=23) -- 128(line=8, offs=24)
*/
ATSINSmove(tmpret1, env0) ;
/* funbodyinstrlst(end) */
ATSreturn(tmpret1) ;
} /* end of [_057_home_057_grad2_057_aren_057_workspace_057_Postiats_057_projects_057_utfpl_057_test_057_ats_testbed_057_06_056_dats__foo1] */

/*
/home/grad2/aren/workspace/Postiats/projects/utfpl/test/ats_testbed/06.dats: 189(line=13, offs=7) -- 205(line=13, offs=23)
*/
/*
local: 
global: foo2_2$0(level=1)
local: x$63(1)(HSEapp(HSEcst(atstkind_t0ype); HSEs2exp(S2Eextkind(atstype_int))))
global: x$63(1)(HSEapp(HSEcst(atstkind_t0ype); HSEs2exp(S2Eextkind(atstype_int))))
*/
ATSstaticdec()
atstkind_t0ype(atstype_int)
foo2_2(atstkind_t0ype(atstype_int) env0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret6, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /home/grad2/aren/workspace/Postiats/projects/utfpl/test/ats_testbed/06.dats: 189(line=13, offs=7) -- 205(line=13, offs=23)
*/
__patsflab_foo2_2:
/*
emit_instr: loc0 = /home/grad2/aren/workspace/Postiats/projects/utfpl/test/ats_testbed/06.dats: 204(line=13, offs=22) -- 205(line=13, offs=23)
*/
ATSINSmove(tmpret6, env0) ;
/* funbodyinstrlst(end) */
ATSreturn(tmpret6) ;
} /* end of [foo2_2] */

/*
/home/grad2/aren/workspace/Postiats/projects/utfpl/test/ats_testbed/06.dats: 281(line=20, offs=17) -- 315(line=24, offs=4)
*/
/*
local: foo_0$0(level=0)
global: foo_0$0(level=0), mainats_void_0$3$0(level=0)
local: 
global: 
*/
ATSglobaldec()
atsvoid_t0ype
mainats_void_0()
{
/* tmpvardeclst(beg) */
ATStmpdec_void(tmpret10, atsvoid_t0ype) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
/*
emit_instr: loc0 = /home/grad2/aren/workspace/Postiats/projects/utfpl/test/ats_testbed/06.dats: 275(line=20, offs=11) -- 315(line=24, offs=4)
*/
__patsflab_main_void_0:
/*
emit_instr: loc0 = /home/grad2/aren/workspace/Postiats/projects/utfpl/test/ats_testbed/06.dats: 286(line=20, offs=22) -- 315(line=24, offs=4)
*/
/*
letpush(beg)
*/
/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/grad2/aren/workspace/Postiats/projects/utfpl/test/ats_testbed/06.dats: 301(line=21, offs=12) -- 307(line=21, offs=18)
*/
ATSINSmove_void(tmpret10, foo_0()) ;

/*
emit_instr: loc0 = /home/grad2/aren/workspace/Postiats/projects/utfpl/test/ats_testbed/06.dats: 286(line=20, offs=22) -- 315(line=24, offs=4)
*/
/*
INSletpop()
*/
/* funbodyinstrlst(end) */
ATSreturn_void(tmpret10) ;
} /* end of [mainats_void_0] */

/*
** for initialization(dynloading)
*/
atsvoid_t0ype
_057_home_057_grad2_057_aren_057_workspace_057_Postiats_057_projects_057_utfpl_057_test_057_ats_testbed_057_06_056_dats__dynload()
{
ATSdynload0(
_057_home_057_grad2_057_aren_057_workspace_057_Postiats_057_projects_057_utfpl_057_test_057_ats_testbed_057_06_056_dats__dynloadflag
) ;
ATSif(
ATSCKiseqz(
_057_home_057_grad2_057_aren_057_workspace_057_Postiats_057_projects_057_utfpl_057_test_057_ats_testbed_057_06_056_dats__dynloadflag
)
) ATSthen() {
ATSdynloadset(_057_home_057_grad2_057_aren_057_workspace_057_Postiats_057_projects_057_utfpl_057_test_057_ats_testbed_057_06_056_dats__dynloadflag) ;
/*
dynexnlst-initize(beg)
*/
/*
dynexnlst-initize(end)
*/
} /* ATSendif */
ATSreturn_void() ;
} /* end of [*_dynload] */

/*
** the ATS runtime
*/
#ifndef _ATS_CCOMP_RUNTIME_NONE
#include "pats_ccomp_runtime.c"
#include "pats_ccomp_runtime_memalloc.c"
#ifndef _ATS_CCOMP_EXCEPTION_NONE
#include "pats_ccomp_runtime2_dats.c"
#ifndef _ATS_CCOMP_RUNTIME_TRYWITH_NONE
#include "pats_ccomp_runtime_trywith.c"
#endif /* _ATS_CCOMP_RUNTIME_TRYWITH_NONE */
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE]
#endif /* _ATS_CCOMP_RUNTIME_NONE */

/*
** the [main] implementation
*/
int
main
(
int argc, char **argv, char **envp
) {
int err = 0 ;
_057_home_057_grad2_057_aren_057_workspace_057_Postiats_057_projects_057_utfpl_057_test_057_ats_testbed_057_06_056_dats__dynload() ;
ATSmainats_void_0(err) ;
return (err) ;
} /* end of [main] */
