/*
**
** The C code is generated by ATS/Postiats
** The compilation time is: 2013-7-15: 20h:10m
**
*/

/*
** include runtime header files
*/
#ifndef _ATS_CCOMP_HEADER_NONE
#include "pats_ccomp_config.h"
#include "pats_ccomp_basics.h"
#include "pats_ccomp_typedefs.h"
#include "pats_ccomp_instrset.h"
#include "pats_ccomp_memalloc.h"
#include "pats_ccomp_memalloca.h"
#include "pats_ccomp_exception.h"
#endif /* _ATS_CCOMP_HEADER_NONE */


/*
** include prelude cats files
*/
#ifndef _ATS_CCOMP_PRELUDE_NONE
//
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/memory.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/strptr.cats"
//
#include "prelude/CATS/filebas.cats"
//
#include "prelude/CATS/list.cats"
#include "prelude/CATS/option.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/arrayptr.cats"
#include "prelude/CATS/arrayref.cats"
#include "prelude/CATS/matrix.cats"
#include "prelude/CATS/matrixptr.cats"
//
#endif /* _ATS_CCOMP_PRELUDE_NONE */

/*
staload-prologues(beg)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/integer.dats: 1636(line=51, offs=1) -- 1675(line=51, offs=40)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/integer.dats: 26347(line=693, offs=1) -- 26378(line=693, offs=32)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/libc/SATS/stdlib.sats: 1379(line=35, offs=1) -- 1418(line=37, offs=3)
*/

#include "libc/CATS/stdlib.cats"
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/libc/SATS/stdlib.sats: 1814(line=54, offs=1) -- 1854(line=55, offs=33)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/string.dats: 1609(line=48, offs=1) -- 1648(line=48, offs=40)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/strptr.dats: 1609(line=48, offs=1) -- 1648(line=48, offs=40)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/strptr.dats: 1671(line=52, offs=1) -- 1718(line=52, offs=48)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/integer.dats: 1636(line=51, offs=1) -- 1675(line=51, offs=40)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/integer.dats: 26347(line=693, offs=1) -- 26378(line=693, offs=32)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/libc/SATS/stdlib.sats: 1379(line=35, offs=1) -- 1418(line=37, offs=3)
*/

#include "libc/CATS/stdlib.cats"
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/libc/SATS/stdlib.sats: 1814(line=54, offs=1) -- 1854(line=55, offs=33)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/pointer.dats: 1533(line=44, offs=1) -- 1572(line=44, offs=40)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/filebas.dats: 1613(line=48, offs=1) -- 1652(line=48, offs=40)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/filebas.dats: 1675(line=52, offs=1) -- 1722(line=52, offs=48)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/integer.dats: 1636(line=51, offs=1) -- 1675(line=51, offs=40)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/integer.dats: 26347(line=693, offs=1) -- 26378(line=693, offs=32)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/libc/SATS/stdlib.sats: 1379(line=35, offs=1) -- 1418(line=37, offs=3)
*/

#include "libc/CATS/stdlib.cats"
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/libc/SATS/stdlib.sats: 1814(line=54, offs=1) -- 1854(line=55, offs=33)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/filebas.dats: 1745(line=56, offs=1) -- 1783(line=56, offs=39)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/libc/SATS/stdio.sats: 1380(line=35, offs=1) -- 1418(line=37, offs=3)
*/

#include "libc/CATS/stdio.cats"
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/libc/SATS/stdio.sats: 1855(line=57, offs=1) -- 1897(line=59, offs=27)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/libc/sys/SATS/types.sats: 1380(line=35, offs=1) -- 1422(line=37, offs=3)
*/

#include "libc/sys/CATS/types.cats"
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/list.dats: 1533(line=44, offs=1) -- 1572(line=44, offs=40)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/list.dats: 1573(line=45, offs=1) -- 1619(line=45, offs=47)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/unsafe.dats: 1532(line=44, offs=1) -- 1566(line=44, offs=35)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/list_vt.dats: 1536(line=44, offs=1) -- 1575(line=44, offs=40)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/list_vt_mergesort.dats: 1546(line=44, offs=1) -- 1585(line=44, offs=40)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/list_vt_quicksort.dats: 1546(line=44, offs=1) -- 1585(line=44, offs=40)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/array.dats: 1534(line=44, offs=1) -- 1573(line=44, offs=40)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/array.dats: 1574(line=45, offs=1) -- 1616(line=45, offs=43)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/array_bsearch.dats: 1531(line=44, offs=1) -- 1570(line=44, offs=40)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/array_quicksort.dats: 1531(line=44, offs=1) -- 1570(line=44, offs=40)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/arrayptr.dats: 1532(line=44, offs=1) -- 1571(line=44, offs=40)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/arrayref.dats: 1532(line=44, offs=1) -- 1571(line=44, offs=40)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/matrix.dats: 1535(line=44, offs=1) -- 1574(line=44, offs=40)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/matrixptr.dats: 1538(line=44, offs=1) -- 1577(line=44, offs=40)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/matrixref.dats: 1538(line=44, offs=1) -- 1577(line=44, offs=40)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/unsafe.dats: 1532(line=44, offs=1) -- 1566(line=44, offs=35)
*/
/*
staload-prologues(end)
*/
/*
typedefs-for-tyrecs-and-tysums(beg)
*/
/*
typedefs-for-tyrecs-and-tysums(end)
*/
/*
dynconlst-declaration(beg)
*/
/*
dynconlst-declaration(end)
*/
/*
dyncstlst-declaration(beg)
*/
ATSdyncst_mac(atspre_isdigit_char) ;
ATSdyncst_mac(atspre_mul_int_double) ;
ATSdyncst_mac(atspre_g0int2float_int_double) ;
ATSdyncst_mac(atspre_sub_char0_char0) ;
ATSdyncst_mac(atspre_neq_char0_char0) ;
ATSdyncst_mac(atspre_sub_ptr0_ptr0) ;
ATSdyncst_mac(atspre_add_ptr0_bsz) ;
ATSdyncst_extfun(_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$projects_057$org_056$ats_055$lang_056$postiats_056$jats_057$test_057$atof_056$dats_atof_frac, (atstkind_type(atstype_ptrk)), atstkind_t0ype(atstype_double)) ;
ATSdyncst_mac(atspre_eq_char0_char0) ;
ATSdyncst_mac(atspre_prerr_string) ;
ATSdyncst_mac(atspre_prerr_newline) ;
ATSdyncst_mac(atspre_argv_get_at) ;
ATSdyncst_mac(atspre_print_string) ;
ATSdyncst_mac(atspre_print_double) ;
ATSdyncst_extfun(_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$projects_057$org_056$ats_055$lang_056$postiats_056$jats_057$test_057$atof_056$dats_atof, (atstkind_type(atstype_ptrk)), atstkind_t0ype(atstype_double)) ;
ATSdyncst_mac(atspre_print_newline) ;
/*
dyncstlst-declaration(end)
*/
/*
dynvalist-implementation(beg)
*/
/*
dynvalist-implementation(end)
*/
/*
exnconlst-declaration(beg)
*/
extern void the_atsexncon_initize (atstype_exncon *d2c, char *exnmsg) ;
/*
exnconlst-declaration(end)
*/
/*
assumelst-declaration(beg)
*/
/*
assumelst-declaration(end)
*/
#if(0)
#if(0)
ATSglobaldec()
atstkind_t0ype(atstype_bool)
ATSLIB_056$prelude_string_foreach_044$cont$1(atstkind_t0ype(atstype_char), atsrefarg1_type(atstyvar_type(env))) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

#if(0)
#if(0)
ATSglobaldec()
atsvoid_t0ype
ATSLIB_056$prelude_string_foreach_044$fwork$2(atstkind_t0ype(atstype_char), atsrefarg1_type(atstkind_t0ype(atstype_double))) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

#if(0)
ATSstaticdec()
atstkind_type(atstype_ptrk)
loop_4$4(atstkind_type(atstype_ptrk), atsrefarg1_type(atstyvar_type(env))) ;
#endif // end of [TEMPLATE]

#if(0)
#if(0)
ATSglobaldec()
atstkind_t0ype(atstype_size)
ATSLIB_056$prelude_string_foreach_env$3(atstkind_type(atstype_ptrk), atsrefarg1_type(atstyvar_type(env))) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstaticdec()
atstkind_t0ype(atstype_size)
ATSLIB_056$prelude_string_foreach_env$3$1(atstkind_type(atstype_ptrk), atsrefarg1_type(atstkind_t0ype(atstype_double))) ;

ATSstaticdec()
atstkind_type(atstype_ptrk)
loop_4$4$1(atstkind_type(atstype_ptrk), atsrefarg1_type(atstkind_t0ype(atstype_double))) ;

#if(0)
#if(0)
ATSglobaldec()
atstyvar_type(a)
ATSLIB_056$prelude_056$unsafe_ptr0_get$7(atstkind_type(atstype_ptrk)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstaticdec()
atstkind_t0ype(atstype_char)
ATSLIB_056$prelude_056$unsafe_ptr0_get$7$1(atstkind_type(atstype_ptrk)) ;

ATSstaticdec()
atstkind_t0ype(atstype_bool)
ATSLIB_056$prelude_string_foreach_044$cont$1$1(atstkind_t0ype(atstype_char), atsrefarg1_type(atstkind_t0ype(atstype_double))) ;

ATSstaticdec()
atsvoid_t0ype
ATSLIB_056$prelude_string_foreach_044$fwork$2$1(atstkind_t0ype(atstype_char), atsrefarg1_type(atstkind_t0ype(atstype_double))) ;

#if(0)
#if(0)
ATSglobaldec()
atstkind_type(atstype_ptrk)
ATSLIB_056$prelude_ptr0_succ$12(atstkind_type(atstype_ptrk)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstaticdec()
atstkind_type(atstype_ptrk)
ATSLIB_056$prelude_ptr0_succ$12$1(atstkind_type(atstype_ptrk)) ;

#if(0)
#if(0)
ATSglobaldec()
atstkind_type(atstype_ptrk)
ATSLIB_056$prelude_ptr1_add_guint$14(atstkind_type(atstype_ptrk), atstkind_t0ype(atstyvar_type(tk))) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstaticdec()
atstkind_type(atstype_ptrk)
ATSLIB_056$prelude_ptr1_add_guint$14$1(atstkind_type(atstype_ptrk), atstkind_t0ype(atstype_size)) ;

#if(0)
#if(0)
ATSglobaldec()
atstkind_type(atstype_ptrk)
ATSLIB_056$prelude_ptr0_add_guint$16(atstkind_type(atstype_ptrk), atstkind_t0ype(atstyvar_type(tk))) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstaticdec()
atstkind_type(atstype_ptrk)
ATSLIB_056$prelude_ptr0_add_guint$16$1(atstkind_type(atstype_ptrk), atstkind_t0ype(atstype_size)) ;

#if(0)
ATSglobaldec()
atstkind_t0ype(atstype_double)
_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$projects_057$org_056$ats_055$lang_056$postiats_056$jats_057$test_057$atof_056$dats_atof(atstkind_type(atstype_ptrk)) ;
#endif // end of [QUALIFIED]

ATSstaticdec()
atstkind_t0ype(atstype_double)
loop_21(atstkind_type(atstype_ptrk), atstkind_t0ype(atstype_double), atstkind_t0ype(atstype_double)) ;

ATSstaticdec()
atstkind_t0ype(atstype_char)
ATSLIB_056$prelude_056$unsafe_ptr0_get$7$2(atstkind_type(atstype_ptrk)) ;

ATSstaticdec()
atstkind_type(atstype_ptrk)
ATSLIB_056$prelude_ptr0_succ$12$2(atstkind_type(atstype_ptrk)) ;

ATSstaticdec()
atstkind_t0ype(atstype_char)
ATSLIB_056$prelude_056$unsafe_ptr0_get$7$3(atstkind_type(atstype_ptrk)) ;

#if(0)
#if(0)
ATSglobaldec()
atstkind_type(atstype_ptrk)
ATSLIB_056$prelude_ptr1_succ$26(atstkind_type(atstype_ptrk)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstaticdec()
atstkind_type(atstype_ptrk)
ATSLIB_056$prelude_ptr1_succ$26$1(atstkind_type(atstype_ptrk)) ;

ATSstaticdec()
atstkind_type(atstype_ptrk)
ATSLIB_056$prelude_ptr0_succ$12$3(atstkind_type(atstype_ptrk)) ;

#if(0)
ATSglobaldec()
atstkind_t0ype(atstype_double)
_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$projects_057$org_056$ats_055$lang_056$postiats_056$jats_057$test_057$atof_056$dats_atof_frac(atstkind_type(atstype_ptrk)) ;
#endif // end of [QUALIFIED]

ATSstaticdec()
atsvoid_t0ype
atof_usage_29(atstkind_type(atstype_ptrk)) ;

#if(0)
#if(0)
ATSglobaldec()
atstkind_t0ype(atstype_bool)
ATSLIB_056$prelude_gte_g1int_int$31(atstkind_t0ype(atstyvar_type(tk)), atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstaticdec()
atstkind_t0ype(atstype_bool)
ATSLIB_056$prelude_gte_g1int_int$31$1(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

#if(0)
ATSglobaldec()
atsvoid_t0ype
mainats_argc_argv_0(atstkind_t0ype(atstype_int), atsrefarg0_type(atstkind_type(atstype_ptrk))) ;
#endif // end of [QUALIFIED]

#if(0)
/*
/home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/atof.dats: 548(line=36, offs=21) -- 569(line=36, offs=42)
*/
/*
local: 
global: string_foreach$cont$1$0(level=1)
local: 
global: 
*/
ATSglobaldec()
/*
imparg = env(5650)
tmparg = S2Evar(env(5650))
tmpsub = None()
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056$prelude_string_foreach_044$cont$1(atstkind_t0ype(atstype_char) arg0, atsrefarg1_type(atstyvar_type(env)) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret2, atstkind_t0ype(atstype_bool)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_string_foreach_044$cont:
ATSINSmove(tmpret2, atspre_isdigit_char(arg0)) ;
/* funbodyinstrlst(end) */
ATSreturn(tmpret2) ;
} /* end of [ATSLIB_056$prelude_string_foreach_044$cont$1] */
#endif // end of [TEMPLATE]

#if(0)
/*
/home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/atof.dats: 610(line=39, offs=3) -- 653(line=39, offs=46)
*/
/*
local: 
global: string_foreach$fwork$2$0(level=1)
local: 
global: 
*/
ATSglobaldec()
/*
imparg = 
tmparg = S2Eapp(S2Ecst(g0float_t0ype); S2Ecst(double_kind))
tmpsub = None()
*/
atsvoid_t0ype
ATSLIB_056$prelude_string_foreach_044$fwork$2(atstkind_t0ype(atstype_char) arg0, atsrefarg1_type(atstkind_t0ype(atstype_double)) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec_void(tmpret3, atsvoid_t0ype) ;
ATStmpdec(tmp4, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp5, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp6, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp7, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_string_foreach_044$fwork:
ATSINSmove(tmp5, atspre_mul_int_double(ATSPMVi0nt(10), ATSderef(arg1, atstkind_t0ype(atstype_double)))) ;
ATSINSmove(tmp7, atspre_sub_char0_char0(arg0, ATSPMVchar('0'))) ;
ATSINSmove(tmp6, atspre_g0int2float_int_double(tmp7)) ;
ATSINSmove(tmp4, PMVtmpltcst(g0float_add<S2Eextkind(atstype_double)>)(tmp5, tmp6)) ;
ATSINSstore(ATSderef(arg1, atstkind_t0ype(atstype_double)), tmp4) ;
ATSINSmove_void(tmpret3, ATSempty()) ;
/* funbodyinstrlst(end) */
ATSreturn_void(tmpret3) ;
} /* end of [ATSLIB_056$prelude_string_foreach_044$fwork$2] */
#endif // end of [TEMPLATE]

#if(0)
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/string.dats: 13211(line=607, offs=5) -- 13557(line=620, offs=4)
*/
/*
local: loop_4$0(level=1)
global: loop_4$0(level=1)
local: 
global: 
*/
ATSstaticdec()
atstkind_type(atstype_ptrk)
loop_4$4(atstkind_type(atstype_ptrk) arg0, atsrefarg1_type(atstyvar_type(env)) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret10, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp11, atstkind_t0ype(atstype_char)) ;
ATStmpdec(tmp12, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp13, atstkind_t0ype(atstype_bool)) ;
ATStmpdec_void(tmp14, atsvoid_t0ype) ;
ATStmpdec(tmp15, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_loop_4:
/*
letpush(beg)
*/
ATSINSmove(tmp11, PMVtmpltcst(ptr0_get<S2Ecst(char_t0ype)>)(arg0)) ;
ATSINSmove(tmp13, atspre_neq_char0_char0(tmp11, ATSPMVchar('\000'))) ;
ATSif(
tmp13
) ATSthen() {
ATSINSmove(tmp12, PMVtmpltcst(string_foreach$cont<S2Evar(env(3437))>)(tmp11, ATSPMVrefarg1(arg1))) ;
} ATSelse() {
ATSINSmove(tmp12, ATSPMVbool_false()) ;
} /* ATSendif */
/*
letpush(end)
*/

ATSif(
tmp12
) ATSthen() {
/*
letpush(beg)
*/
ATSINSmove_void(tmp14, PMVtmpltcst(string_foreach$fwork<S2Evar(env(3437))>)(tmp11, ATSPMVrefarg1(arg1))) ;
/*
letpush(end)
*/

ATSINSmove(tmp15, PMVtmpltcst(ptr0_succ<S2Ecst(char_t0ype)>)(arg0)) ;
ATSINSmove(tmpret10, ATSfunclo_fun(PMVd2vfunlab(d2v=loop$357(1), flab=loop_4$0(level=1)), (atstkind_type(atstype_ptrk), atsrefarg1_type(atstyvar_type(env))), atstkind_type(atstype_ptrk))(tmp15, ATSPMVrefarg1(arg1))) ;
/*
INSletpop()
*/
} ATSelse() {
ATSINSmove(tmpret10, arg0) ;
} /* ATSendif */
/*
INSletpop()
*/
/* funbodyinstrlst(end) */
ATSreturn(tmpret10) ;
} /* end of [loop_4$4] */
#endif // end of [TEMPLATE]

#if(0)
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/string.dats: 13187(line=605, offs=7) -- 13670(line=628, offs=4)
*/
/*
local: 
global: string_foreach_env$3$0(level=0)
local: 
global: 
*/
ATSglobaldec()
/*
imparg = env(3437)
tmparg = S2Evar(env(3437))
tmpsub = None()
*/
atstkind_t0ype(atstype_size)
ATSLIB_056$prelude_string_foreach_env$3(atstkind_type(atstype_ptrk) arg0, atsrefarg1_type(atstyvar_type(env)) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret9, atstkind_t0ype(atstype_size)) ;
ATStmpdec(tmp16, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp17, atstkind_t0ype(atstype_ssize)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_string_foreach_env:
/*
letpush(beg)
*/
/* (*nothing*) */
ATSINSmove(tmp16, ATSfunclo_fun(PMVd2vfunlab(d2v=loop$357(1), flab=loop_4$0(level=1)), (atstkind_type(atstype_ptrk), atsrefarg1_type(atstyvar_type(env))), atstkind_type(atstype_ptrk))(ATSPMVcastfn(string2ptr, atstkind_type(atstype_ptrk), arg0), ATSPMVrefarg1(arg1))) ;
/*
letpush(end)
*/

ATSINSmove(tmp17, atspre_sub_ptr0_ptr0(tmp16, ATSPMVcastfn(string2ptr, atstkind_type(atstype_ptrk), arg0))) ;
ATSINSmove(tmpret9, ATSPMVcastfn(cast, atstkind_t0ype(atstype_size), tmp17)) ;
/*
INSletpop()
*/
/* funbodyinstrlst(end) */
ATSreturn(tmpret9) ;
} /* end of [ATSLIB_056$prelude_string_foreach_env$3] */
#endif // end of [TEMPLATE]

/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/string.dats: 13187(line=605, offs=7) -- 13670(line=628, offs=4)
*/
/*
local: 
global: string_foreach_env$3$1(level=1)
local: 
global: 
*/
ATSstaticdec()
/*
imparg = env(3437)
tmparg = S2Evar(env(3437))
tmpsub = Some(env(3437) -> S2Eapp(S2Ecst(g0float_t0ype); S2Ecst(double_kind)))
*/
atstkind_t0ype(atstype_size)
ATSLIB_056$prelude_string_foreach_env$3$1(atstkind_type(atstype_ptrk) arg0, atsrefarg1_type(atstkind_t0ype(atstype_double)) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmp9$1, atstkind_t0ype(atstype_size)) ;
ATStmpdec(tmp16$1, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp17$1, atstkind_t0ype(atstype_ssize)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_string_foreach_env:
/*
letpush(beg)
*/
/* (*nothing*) */
ATSINSmove(tmp16$1, loop_4$4$1(ATSPMVcastfn(string2ptr, atstkind_type(atstype_ptrk), arg0), ATSPMVrefarg1(arg1))) ;
/*
letpush(end)
*/

ATSINSmove(tmp17$1, atspre_sub_ptr0_ptr0(tmp16$1, ATSPMVcastfn(string2ptr, atstkind_type(atstype_ptrk), arg0))) ;
ATSINSmove(tmp9$1, ATSPMVcastfn(cast, atstkind_t0ype(atstype_size), tmp17$1)) ;
/*
INSletpop()
*/
/* funbodyinstrlst(end) */
ATSreturn(tmp9$1) ;
} /* end of [ATSLIB_056$prelude_string_foreach_env$3$1] */

/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/string.dats: 13211(line=607, offs=5) -- 13557(line=620, offs=4)
*/
/*
local: loop_4$1(level=2)
global: loop_4$1(level=2)
local: 
global: 
*/
ATSstaticdec()
atstkind_type(atstype_ptrk)
loop_4$4$1(atstkind_type(atstype_ptrk) arg0, atsrefarg1_type(atstkind_t0ype(atstype_double)) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmp10$1, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp11$1, atstkind_t0ype(atstype_char)) ;
ATStmpdec(tmp12$1, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp13$1, atstkind_t0ype(atstype_bool)) ;
ATStmpdec_void(tmp14$1, atsvoid_t0ype) ;
ATStmpdec(tmp15$1, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_loop_4:
/*
letpush(beg)
*/
ATSINSmove(tmp11$1, ATSLIB_056$prelude_056$unsafe_ptr0_get$7$1(arg0)) ;
ATSINSmove(tmp13$1, atspre_neq_char0_char0(tmp11$1, ATSPMVchar('\000'))) ;
ATSif(
tmp13$1
) ATSthen() {
ATSINSmove(tmp12$1, ATSLIB_056$prelude_string_foreach_044$cont$1$1(tmp11$1, ATSPMVrefarg1(arg1))) ;
} ATSelse() {
ATSINSmove(tmp12$1, ATSPMVbool_false()) ;
} /* ATSendif */
/*
letpush(end)
*/

ATSif(
tmp12$1
) ATSthen() {
/*
letpush(beg)
*/
ATSINSmove_void(tmp14$1, ATSLIB_056$prelude_string_foreach_044$fwork$2$1(tmp11$1, ATSPMVrefarg1(arg1))) ;
/*
letpush(end)
*/

ATSINSmove(tmp15$1, ATSLIB_056$prelude_ptr0_succ$12$1(arg0)) ;
ATSINSmove(tmp10$1, loop_4$4$1(tmp15$1, ATSPMVrefarg1(arg1))) ;
/*
INSletpop()
*/
} ATSelse() {
ATSINSmove(tmp10$1, arg0) ;
} /* ATSendif */
/*
INSletpop()
*/
/* funbodyinstrlst(end) */
ATSreturn(tmp10$1) ;
} /* end of [loop_4$4$1] */

#if(0)
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/unsafe.dats: 1621(line=51, offs=3) -- 1834(line=59, offs=2)
*/
/*
local: 
global: ptr0_get$7$0(level=0)
local: 
global: 
*/
ATSglobaldec()
/*
imparg = a(3798)
tmparg = S2Evar(a(3798))
tmpsub = None()
*/
atstyvar_type(a)
ATSLIB_056$prelude_056$unsafe_ptr0_get$7(atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret27, atstyvar_type(a)) ;
ATStmpdec(tmp28, atstyvar_type(a)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_ptr0_get:
/*
letpush(beg)
*/
/* (*nothing*) */
/* (*nothing*) */
ATSINSmove(tmp28, ATSderef(ATSPMVcastfn(g1ofg0_ptr, atstkind_type(atstype_ptrk), arg0), atstyvar_type(a))) ;
/* (*nothing*) */
/*
letpush(end)
*/

ATSINSmove(tmpret27, tmp28) ;
/*
INSletpop()
*/
/* funbodyinstrlst(end) */
ATSreturn(tmpret27) ;
} /* end of [ATSLIB_056$prelude_056$unsafe_ptr0_get$7] */
#endif // end of [TEMPLATE]

/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/unsafe.dats: 1621(line=51, offs=3) -- 1834(line=59, offs=2)
*/
/*
local: 
global: ptr0_get$7$1(level=3)
local: 
global: 
*/
ATSstaticdec()
/*
imparg = a(3798)
tmparg = S2Evar(a(3798))
tmpsub = Some(a(3798) -> S2Ecst(char_t0ype))
*/
atstkind_t0ype(atstype_char)
ATSLIB_056$prelude_056$unsafe_ptr0_get$7$1(atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmp27$1, atstkind_t0ype(atstype_char)) ;
ATStmpdec(tmp28$1, atstkind_t0ype(atstype_char)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_ptr0_get:
/*
letpush(beg)
*/
/* (*nothing*) */
/* (*nothing*) */
ATSINSmove(tmp28$1, ATSderef(ATSPMVcastfn(g1ofg0_ptr, atstkind_type(atstype_ptrk), arg0), atstkind_t0ype(atstype_char))) ;
/* (*nothing*) */
/*
letpush(end)
*/

ATSINSmove(tmp27$1, tmp28$1) ;
/*
INSletpop()
*/
/* funbodyinstrlst(end) */
ATSreturn(tmp27$1) ;
} /* end of [ATSLIB_056$prelude_056$unsafe_ptr0_get$7$1] */

/*
/home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/atof.dats: 548(line=36, offs=21) -- 569(line=36, offs=42)
*/
/*
local: 
global: string_foreach$cont$1$1(level=3)
local: 
global: 
*/
ATSstaticdec()
/*
imparg = env(5650)
tmparg = S2Evar(env(5650))
tmpsub = Some(env(5650) -> S2Eapp(S2Ecst(g0float_t0ype); S2Ecst(double_kind)))
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056$prelude_string_foreach_044$cont$1$1(atstkind_t0ype(atstype_char) arg0, atsrefarg1_type(atstkind_t0ype(atstype_double)) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmp2$1, atstkind_t0ype(atstype_bool)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_string_foreach_044$cont:
ATSINSmove(tmp2$1, atspre_isdigit_char(arg0)) ;
/* funbodyinstrlst(end) */
ATSreturn(tmp2$1) ;
} /* end of [ATSLIB_056$prelude_string_foreach_044$cont$1$1] */

/*
/home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/atof.dats: 610(line=39, offs=3) -- 653(line=39, offs=46)
*/
/*
local: 
global: string_foreach$fwork$2$1(level=3)
local: 
global: 
*/
ATSstaticdec()
/*
imparg = 
tmparg = S2Eapp(S2Ecst(g0float_t0ype); S2Ecst(double_kind))
tmpsub = Some()
*/
atsvoid_t0ype
ATSLIB_056$prelude_string_foreach_044$fwork$2$1(atstkind_t0ype(atstype_char) arg0, atsrefarg1_type(atstkind_t0ype(atstype_double)) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec_void(tmp3$1, atsvoid_t0ype) ;
ATStmpdec(tmp4$1, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp5$1, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp6$1, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp7$1, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_string_foreach_044$fwork:
ATSINSmove(tmp5$1, atspre_mul_int_double(ATSPMVi0nt(10), ATSderef(arg1, atstkind_t0ype(atstype_double)))) ;
ATSINSmove(tmp7$1, atspre_sub_char0_char0(arg0, ATSPMVchar('0'))) ;
ATSINSmove(tmp6$1, atspre_g0int2float_int_double(tmp7$1)) ;
ATSINSmove(tmp4$1, atspre_g0float_add_double(tmp5$1, tmp6$1)) ;
ATSINSstore(ATSderef(arg1, atstkind_t0ype(atstype_double)), tmp4$1) ;
ATSINSmove_void(tmp3$1, ATSempty()) ;
/* funbodyinstrlst(end) */
ATSreturn_void(tmp3$1) ;
} /* end of [ATSLIB_056$prelude_string_foreach_044$fwork$2$1] */

#if(0)
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/pointer.dats: 1808(line=61, offs=11) -- 1840(line=61, offs=43)
*/
/*
local: 
global: ptr0_succ$12$0(level=0)
local: 
global: 
*/
ATSglobaldec()
/*
imparg = a(3526)
tmparg = S2Evar(a(3526))
tmpsub = None()
*/
atstkind_type(atstype_ptrk)
ATSLIB_056$prelude_ptr0_succ$12(atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret37, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_ptr0_succ:
ATSINSmove(tmpret37, atspre_add_ptr0_bsz(arg0, ATSPMVsizeof(atstyvar_type(a)))) ;
/* funbodyinstrlst(end) */
ATSreturn(tmpret37) ;
} /* end of [ATSLIB_056$prelude_ptr0_succ$12] */
#endif // end of [TEMPLATE]

/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/pointer.dats: 1808(line=61, offs=11) -- 1840(line=61, offs=43)
*/
/*
local: 
global: ptr0_succ$12$1(level=3)
local: 
global: 
*/
ATSstaticdec()
/*
imparg = a(3526)
tmparg = S2Evar(a(3526))
tmpsub = Some(a(3526) -> S2Ecst(char_t0ype))
*/
atstkind_type(atstype_ptrk)
ATSLIB_056$prelude_ptr0_succ$12$1(atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmp37$1, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_ptr0_succ:
ATSINSmove(tmp37$1, atspre_add_ptr0_bsz(arg0, ATSPMVsizeof(atstkind_t0ype(atstype_char)))) ;
/* funbodyinstrlst(end) */
ATSreturn(tmp37$1) ;
} /* end of [ATSLIB_056$prelude_ptr0_succ$12$1] */

#if(0)
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/pointer.dats: 2736(line=100, offs=23) -- 2804(line=101, offs=60)
*/
/*
local: 
global: ptr1_add_guint$14$0(level=0)
local: 
global: 
*/
ATSglobaldec()
/*
imparg = a(3556), tk(3557)
tmparg = S2Evar(a(3556)); S2Evar(tk(3557))
tmpsub = None()
*/
atstkind_type(atstype_ptrk)
ATSLIB_056$prelude_ptr1_add_guint$14(atstkind_type(atstype_ptrk) arg0, atstkind_t0ype(atstyvar_type(tk)) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret40, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp41, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_ptr1_add_guint:
ATSINSmove(tmp41, PMVtmpltcst(ptr0_add_guint<S2Evar(a(3556))><S2Evar(tk(3557))>)(arg0, arg1)) ;
ATSINSmove(tmpret40, ATSPMVcastfn(cast, atstkind_type(atstype_ptrk), tmp41)) ;
/* funbodyinstrlst(end) */
ATSreturn(tmpret40) ;
} /* end of [ATSLIB_056$prelude_ptr1_add_guint$14] */
#endif // end of [TEMPLATE]

/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/pointer.dats: 2736(line=100, offs=23) -- 2804(line=101, offs=60)
*/
/*
local: 
global: ptr1_add_guint$14$1(level=1)
local: 
global: 
*/
ATSstaticdec()
/*
imparg = a(3556), tk(3557)
tmparg = S2Evar(a(3556)); S2Evar(tk(3557))
tmpsub = Some(a(3556) -> S2Ecst(char_t0ype); tk(3557) -> S2Eextkind(atstype_size))
*/
atstkind_type(atstype_ptrk)
ATSLIB_056$prelude_ptr1_add_guint$14$1(atstkind_type(atstype_ptrk) arg0, atstkind_t0ype(atstype_size) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmp40$1, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp41$1, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_ptr1_add_guint:
ATSINSmove(tmp41$1, ATSLIB_056$prelude_ptr0_add_guint$16$1(arg0, arg1)) ;
ATSINSmove(tmp40$1, ATSPMVcastfn(cast, atstkind_type(atstype_ptrk), tmp41$1)) ;
/* funbodyinstrlst(end) */
ATSreturn(tmp40$1) ;
} /* end of [ATSLIB_056$prelude_ptr1_add_guint$14$1] */

#if(0)
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/pointer.dats: 2126(line=75, offs=16) -- 2180(line=76, offs=46)
*/
/*
local: 
global: ptr0_add_guint$16$0(level=0)
local: 
global: 
*/
ATSglobaldec()
/*
imparg = a(3532), tk(3533)
tmparg = S2Evar(a(3532)); S2Evar(tk(3533))
tmpsub = None()
*/
atstkind_type(atstype_ptrk)
ATSLIB_056$prelude_ptr0_add_guint$16(atstkind_type(atstype_ptrk) arg0, atstkind_t0ype(atstyvar_type(tk)) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret44, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp45, atstkind_t0ype(atstype_size)) ;
ATStmpdec(tmp46, atstkind_t0ype(atstype_size)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_ptr0_add_guint:
ATSINSmove(tmp46, PMVtmpltcst(g0uint2uint<S2Evar(tk(3533)), S2Eextkind(atstype_size)>)(arg1)) ;
ATSINSmove(tmp45, PMVtmpltcst(g0uint_mul<S2Eextkind(atstype_size)>)(tmp46, ATSPMVsizeof(atstyvar_type(a)))) ;
ATSINSmove(tmpret44, atspre_add_ptr0_bsz(arg0, tmp45)) ;
/* funbodyinstrlst(end) */
ATSreturn(tmpret44) ;
} /* end of [ATSLIB_056$prelude_ptr0_add_guint$16] */
#endif // end of [TEMPLATE]

/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/pointer.dats: 2126(line=75, offs=16) -- 2180(line=76, offs=46)
*/
/*
local: 
global: ptr0_add_guint$16$1(level=2)
local: 
global: 
*/
ATSstaticdec()
/*
imparg = a(3532), tk(3533)
tmparg = S2Evar(a(3532)); S2Evar(tk(3533))
tmpsub = Some(a(3532) -> S2Ecst(char_t0ype); tk(3533) -> S2Eextkind(atstype_size))
*/
atstkind_type(atstype_ptrk)
ATSLIB_056$prelude_ptr0_add_guint$16$1(atstkind_type(atstype_ptrk) arg0, atstkind_t0ype(atstype_size) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmp44$1, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp45$1, atstkind_t0ype(atstype_size)) ;
ATStmpdec(tmp46$1, atstkind_t0ype(atstype_size)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_ptr0_add_guint:
ATSINSmove(tmp46$1, atspre_g0uint2uint_size_size(arg1)) ;
ATSINSmove(tmp45$1, atspre_g0uint_mul_size(tmp46$1, ATSPMVsizeof(atstkind_t0ype(atstype_char)))) ;
ATSINSmove(tmp44$1, atspre_add_ptr0_bsz(arg0, tmp45$1)) ;
/* funbodyinstrlst(end) */
ATSreturn(tmp44$1) ;
} /* end of [ATSLIB_056$prelude_ptr0_add_guint$16$1] */

/*
/home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/atof.dats: 420(line=28, offs=6) -- 801(line=47, offs=4)
*/
/*
local: 
global: atof$0$0(level=0)
local: 
global: 
*/
ATSglobaldec()
atstkind_t0ype(atstype_double)
_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$projects_057$org_056$ats_055$lang_056$postiats_056$jats_057$test_057$atof_056$dats_atof(atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret0, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmpref1, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp8, atstkind_t0ype(atstype_size)) ;
ATStmpdec(tmp39, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp50, atstkind_t0ype(atstype_double)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_atof:
/*
letpush(beg)
*/
/* (*nothing*) */
/*
ATSINStmpdec(tmpref1)) ;
*/
ATSINSmove(tmpref1, ATSPMVf0loat(0.0)) ;
ATSINSmove(tmp8, ATSLIB_056$prelude_string_foreach_env$3$1(ATSPMVcastfn(g1ofg0_string, atstkind_type(atstype_ptrk), arg0), ATSPMVrefarg1(ATSPMVptrof(tmpref1)))) ;
ATSINSmove(tmp39, ATSLIB_056$prelude_ptr1_add_guint$14$1(ATSPMVcastfn(string2ptr, atstkind_type(atstype_ptrk), ATSPMVcastfn(g1ofg0_string, atstkind_type(atstype_ptrk), arg0)), tmp8)) ;
/*
letpush(end)
*/

ATSINSmove(tmp50, _057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$projects_057$org_056$ats_055$lang_056$postiats_056$jats_057$test_057$atof_056$dats_atof_frac(ATSPMVcastfn(cast, atstkind_type(atstype_ptrk), tmp39))) ;
ATSINSmove(tmpret0, atspre_g0float_add_double(tmpref1, tmp50)) ;
/*
INSletpop()
*/
/* funbodyinstrlst(end) */
ATSreturn(tmpret0) ;
} /* end of [_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$projects_057$org_056$ats_055$lang_056$postiats_056$jats_057$test_057$atof_056$dats_atof] */

/*
/home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/atof.dats: 880(line=54, offs=5) -- 1102(line=65, offs=4)
*/
/*
local: loop_21$0(level=1)
global: loop_21$0(level=1)
local: 
global: 
*/
ATSstaticdec()
atstkind_t0ype(atstype_double)
loop_21(atstkind_type(atstype_ptrk) arg0, atstkind_t0ype(atstype_double) arg1, atstkind_t0ype(atstype_double) arg2)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret52, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp53, atstkind_t0ype(atstype_char)) ;
ATStmpdec(tmp56, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp57, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp59, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp60, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp61, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp62, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp63, atstkind_t0ype(atstype_double)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_loop_21:
/*
letpush(beg)
*/
ATSINSmove(tmp53, ATSLIB_056$prelude_056$unsafe_ptr0_get$7$2(arg0)) ;
/*
letpush(end)
*/

ATSINSmove(tmp56, atspre_isdigit_char(tmp53)) ;
ATSif(
tmp56
) ATSthen() {
ATSINSmove(tmp57, ATSLIB_056$prelude_ptr0_succ$12$2(arg0)) ;
ATSINSmove(tmp60, atspre_mul_int_double(ATSPMVi0nt(10), arg1)) ;
ATSINSmove(tmp62, atspre_sub_char0_char0(tmp53, ATSPMVchar('0'))) ;
ATSINSmove(tmp61, atspre_g0int2float_int_double(tmp62)) ;
ATSINSmove(tmp59, atspre_g0float_add_double(tmp60, tmp61)) ;
ATSINSmove(tmp63, atspre_mul_int_double(ATSPMVi0nt(10), arg2)) ;
ATSINSmove(tmpret52, loop_21(tmp57, tmp59, tmp63)) ;
} ATSelse() {
ATSINSmove(tmpret52, atspre_g0float_div_double(arg1, arg2)) ;
} /* ATSendif */
/*
INSletpop()
*/
/* funbodyinstrlst(end) */
ATSreturn(tmpret52) ;
} /* end of [loop_21] */

/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/unsafe.dats: 1621(line=51, offs=3) -- 1834(line=59, offs=2)
*/
/*
local: 
global: ptr0_get$7$2(level=2)
local: 
global: 
*/
ATSstaticdec()
/*
imparg = a(3798)
tmparg = S2Evar(a(3798))
tmpsub = Some(a(3798) -> S2Ecst(char_t0ype))
*/
atstkind_t0ype(atstype_char)
ATSLIB_056$prelude_056$unsafe_ptr0_get$7$2(atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmp27$2, atstkind_t0ype(atstype_char)) ;
ATStmpdec(tmp28$2, atstkind_t0ype(atstype_char)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_ptr0_get:
/*
letpush(beg)
*/
/* (*nothing*) */
/* (*nothing*) */
ATSINSmove(tmp28$2, ATSderef(ATSPMVcastfn(g1ofg0_ptr, atstkind_type(atstype_ptrk), arg0), atstkind_t0ype(atstype_char))) ;
/* (*nothing*) */
/*
letpush(end)
*/

ATSINSmove(tmp27$2, tmp28$2) ;
/*
INSletpop()
*/
/* funbodyinstrlst(end) */
ATSreturn(tmp27$2) ;
} /* end of [ATSLIB_056$prelude_056$unsafe_ptr0_get$7$2] */

/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/pointer.dats: 1808(line=61, offs=11) -- 1840(line=61, offs=43)
*/
/*
local: 
global: ptr0_succ$12$2(level=2)
local: 
global: 
*/
ATSstaticdec()
/*
imparg = a(3526)
tmparg = S2Evar(a(3526))
tmpsub = Some(a(3526) -> S2Ecst(char_t0ype))
*/
atstkind_type(atstype_ptrk)
ATSLIB_056$prelude_ptr0_succ$12$2(atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmp37$2, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_ptr0_succ:
ATSINSmove(tmp37$2, atspre_add_ptr0_bsz(arg0, ATSPMVsizeof(atstkind_t0ype(atstype_char)))) ;
/* funbodyinstrlst(end) */
ATSreturn(tmp37$2) ;
} /* end of [ATSLIB_056$prelude_ptr0_succ$12$2] */

/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/unsafe.dats: 1621(line=51, offs=3) -- 1834(line=59, offs=2)
*/
/*
local: 
global: ptr0_get$7$3(level=1)
local: 
global: 
*/
ATSstaticdec()
/*
imparg = a(3798)
tmparg = S2Evar(a(3798))
tmpsub = Some(a(3798) -> S2Ecst(char_t0ype))
*/
atstkind_t0ype(atstype_char)
ATSLIB_056$prelude_056$unsafe_ptr0_get$7$3(atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmp27$3, atstkind_t0ype(atstype_char)) ;
ATStmpdec(tmp28$3, atstkind_t0ype(atstype_char)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_ptr0_get:
/*
letpush(beg)
*/
/* (*nothing*) */
/* (*nothing*) */
ATSINSmove(tmp28$3, ATSderef(ATSPMVcastfn(g1ofg0_ptr, atstkind_type(atstype_ptrk), arg0), atstkind_t0ype(atstype_char))) ;
/* (*nothing*) */
/*
letpush(end)
*/

ATSINSmove(tmp27$3, tmp28$3) ;
/*
INSletpop()
*/
/* funbodyinstrlst(end) */
ATSreturn(tmp27$3) ;
} /* end of [ATSLIB_056$prelude_056$unsafe_ptr0_get$7$3] */

#if(0)
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/pointer.dats: 2321(line=84, offs=15) -- 2371(line=85, offs=45)
*/
/*
local: 
global: ptr1_succ$26$0(level=0)
local: 
global: 
*/
ATSglobaldec()
/*
imparg = a(3536)
tmparg = S2Evar(a(3536))
tmpsub = None()
*/
atstkind_type(atstype_ptrk)
ATSLIB_056$prelude_ptr1_succ$26(atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret69, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp70, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_ptr1_succ:
ATSINSmove(tmp70, PMVtmpltcst(ptr0_succ<S2Evar(a(3536))>)(arg0)) ;
ATSINSmove(tmpret69, ATSPMVcastfn(cast, atstkind_type(atstype_ptrk), tmp70)) ;
/* funbodyinstrlst(end) */
ATSreturn(tmpret69) ;
} /* end of [ATSLIB_056$prelude_ptr1_succ$26] */
#endif // end of [TEMPLATE]

/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/pointer.dats: 2321(line=84, offs=15) -- 2371(line=85, offs=45)
*/
/*
local: 
global: ptr1_succ$26$1(level=1)
local: 
global: 
*/
ATSstaticdec()
/*
imparg = a(3536)
tmparg = S2Evar(a(3536))
tmpsub = Some(a(3536) -> S2Ecst(char_t0ype))
*/
atstkind_type(atstype_ptrk)
ATSLIB_056$prelude_ptr1_succ$26$1(atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmp69$1, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp70$1, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_ptr1_succ:
ATSINSmove(tmp70$1, ATSLIB_056$prelude_ptr0_succ$12$3(arg0)) ;
ATSINSmove(tmp69$1, ATSPMVcastfn(cast, atstkind_type(atstype_ptrk), tmp70$1)) ;
/* funbodyinstrlst(end) */
ATSreturn(tmp69$1) ;
} /* end of [ATSLIB_056$prelude_ptr1_succ$26$1] */

/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/pointer.dats: 1808(line=61, offs=11) -- 1840(line=61, offs=43)
*/
/*
local: 
global: ptr0_succ$12$3(level=2)
local: 
global: 
*/
ATSstaticdec()
/*
imparg = a(3526)
tmparg = S2Evar(a(3526))
tmpsub = Some(a(3526) -> S2Ecst(char_t0ype))
*/
atstkind_type(atstype_ptrk)
ATSLIB_056$prelude_ptr0_succ$12$3(atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmp37$3, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_ptr0_succ:
ATSINSmove(tmp37$3, atspre_add_ptr0_bsz(arg0, ATSPMVsizeof(atstkind_t0ype(atstype_char)))) ;
/* funbodyinstrlst(end) */
ATSreturn(tmp37$3) ;
} /* end of [ATSLIB_056$prelude_ptr0_succ$12$3] */

/*
/home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/atof.dats: 861(line=52, offs=11) -- 1260(line=74, offs=4)
*/
/*
local: 
global: atof_frac$20$0(level=0)
local: 
global: 
*/
ATSglobaldec()
atstkind_t0ype(atstype_double)
_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$projects_057$org_056$ats_055$lang_056$postiats_056$jats_057$test_057$atof_056$dats_atof_frac(atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret51, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp64, atstkind_t0ype(atstype_char)) ;
ATStmpdec(tmp67, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp68, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_atof_frac:
/*
letpush(beg)
*/
/* (*nothing*) */
ATSINSmove(tmp64, ATSLIB_056$prelude_056$unsafe_ptr0_get$7$3(ATSPMVcastfn(string2ptr, atstkind_type(atstype_ptrk), arg0))) ;
/*
letpush(end)
*/

ATSINSmove(tmp67, atspre_eq_char0_char0(tmp64, ATSPMVchar('.'))) ;
ATSif(
tmp67
) ATSthen() {
ATSINSmove(tmp68, ATSLIB_056$prelude_ptr1_succ$26$1(ATSPMVcastfn(string2ptr, atstkind_type(atstype_ptrk), arg0))) ;
ATSINSmove(tmpret51, loop_21(tmp68, ATSPMVf0loat(0.0), ATSPMVf0loat(1.0))) ;
} ATSelse() {
ATSINSmove(tmpret51, ATSPMVf0loat(0.0)) ;
} /* ATSendif */
/*
INSletpop()
*/
/* funbodyinstrlst(end) */
ATSreturn(tmpret51) ;
} /* end of [_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$projects_057$org_056$ats_055$lang_056$postiats_056$jats_057$test_057$atof_056$dats_atof_frac] */

/*
/home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/atof.dats: 1308(line=78, offs=4) -- 1380(line=79, offs=62)
*/
/*
local: 
global: atof_usage_29$0(level=0)
local: 
global: 
*/
ATSstaticdec()
atsvoid_t0ype
atof_usage_29(atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec_void(tmpret74, atsvoid_t0ype) ;
ATStmpdec_void(tmp75, atsvoid_t0ype) ;
ATStmpdec_void(tmp76, atsvoid_t0ype) ;
ATStmpdec_void(tmp77, atsvoid_t0ype) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_atof_usage_29:
ATSINSmove_void(tmp75, atspre_prerr_string(ATSPMVstring("Usage: "))) ;
ATSINSmove_void(tmp76, atspre_prerr_string(arg0)) ;
ATSINSmove_void(tmp77, atspre_prerr_string(ATSPMVstring(" [float]"))) ;
ATSINSmove_void(tmpret74, atspre_prerr_newline()) ;
/* funbodyinstrlst(end) */
ATSreturn_void(tmpret74) ;
} /* end of [atof_usage_29] */

#if(0)
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/integer.dats: 28079(line=758, offs=15) -- 28120(line=758, offs=56)
*/
/*
local: 
global: gte_g1int_int$31$0(level=0)
local: 
global: 
*/
ATSglobaldec()
/*
imparg = tk(3272)
tmparg = S2Evar(tk(3272))
tmpsub = None()
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056$prelude_gte_g1int_int$31(atstkind_t0ype(atstyvar_type(tk)) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret81, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp82, atstkind_t0ype(atstyvar_type(tk))) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_gte_g1int_int:
ATSINSmove(tmp82, PMVtmpltcst(g1int2int<S2Eextkind(atstype_int), S2Evar(tk(3272))>)(arg1)) ;
ATSINSmove(tmpret81, PMVtmpltcst(g1int_gte<S2Evar(tk(3272))>)(arg0, tmp82)) ;
/* funbodyinstrlst(end) */
ATSreturn(tmpret81) ;
} /* end of [ATSLIB_056$prelude_gte_g1int_int$31] */
#endif // end of [TEMPLATE]

/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/integer.dats: 28079(line=758, offs=15) -- 28120(line=758, offs=56)
*/
/*
local: 
global: gte_g1int_int$31$1(level=1)
local: 
global: 
*/
ATSstaticdec()
/*
imparg = tk(3272)
tmparg = S2Evar(tk(3272))
tmpsub = Some(tk(3272) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056$prelude_gte_g1int_int$31$1(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmp81$1, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp82$1, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_gte_g1int_int:
ATSINSmove(tmp82$1, atspre_g1int2int_int_int(arg1)) ;
ATSINSmove(tmp81$1, atspre_g1int_gte_int(arg0, tmp82$1)) ;
/* funbodyinstrlst(end) */
ATSreturn(tmp81$1) ;
} /* end of [ATSLIB_056$prelude_gte_g1int_int$31$1] */

/*
/home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/atof.dats: 1442(line=85, offs=7) -- 1704(line=99, offs=2)
*/
/*
local: 
global: mainats_argc_argv_0$30$0(level=0)
local: 
global: 
*/
ATSglobaldec()
atsvoid_t0ype
mainats_argc_argv_0(atstkind_t0ype(atstype_int) arg0, atsrefarg0_type(atstkind_type(atstype_ptrk)) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec_void(tmpret78, atsvoid_t0ype) ;
ATStmpdec(tmp79, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp80, atstkind_t0ype(atstype_bool)) ;
ATStmpdec_void(tmp85, atsvoid_t0ype) ;
ATStmpdec_void(tmp86, atsvoid_t0ype) ;
ATStmpdec_void(tmp87, atsvoid_t0ype) ;
ATStmpdec_void(tmp88, atsvoid_t0ype) ;
ATStmpdec(tmp89, atstkind_t0ype(atstype_double)) ;
ATStmpdec_void(tmp90, atsvoid_t0ype) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_main_argc_argv_0:
/*
letpush(beg)
*/
ATSINSmove(tmp80, ATSLIB_056$prelude_gte_g1int_int$31$1(arg0, ATSPMVi0nt(2))) ;
ATSif(
tmp80
) ATSthen() {
ATSINSmove(tmp79, atspre_argv_get_at(ATSPMVrefarg0(arg1), ATSPMVi0nt(1))) ;
} ATSelse() {
ATSINSmove(tmp79, ATSPMVstring("3.1416")) ;
} /* ATSendif */
ATSINSmove_void(tmp85, atspre_print_string(ATSPMVstring("atof(\""))) ;
ATSINSmove_void(tmp86, atspre_print_string(tmp79)) ;
ATSINSmove_void(tmp87, atspre_print_string(ATSPMVstring("\") = "))) ;
ATSINSmove(tmp89, _057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$projects_057$org_056$ats_055$lang_056$postiats_056$jats_057$test_057$atof_056$dats_atof(tmp79)) ;
ATSINSmove_void(tmp88, atspre_print_double(tmp89)) ;
ATSINSmove_void(tmp90, atspre_print_newline()) ;
/*
letpush(end)
*/

ATSINSmove_void(tmpret78, ATSempty()) ;
/*
INSletpop()
*/
/* funbodyinstrlst(end) */
ATSreturn_void(tmpret78) ;
} /* end of [mainats_argc_argv_0] */


/*
** for initialization(dynloading)
*/
atsvoid_t0ype
_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$projects_057$org_056$ats_055$lang_056$postiats_056$jats_057$test_057$atof_056$dats__dynload()
{
ATSdynload0(
_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$projects_057$org_056$ats_055$lang_056$postiats_056$jats_057$test_057$atof_056$dats__dynloadflag
) ;
ATSif(
ATSCKiseqz(
_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$projects_057$org_056$ats_055$lang_056$postiats_056$jats_057$test_057$atof_056$dats__dynloadflag
)
) ATSthen() {
ATSdynloadset(_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$projects_057$org_056$ats_055$lang_056$postiats_056$jats_057$test_057$atof_056$dats__dynloadflag) ;
/*
dynexnlst-initize(beg)
*/
/*
dynexnlst-initize(end)
*/
} /* ATSendif */
ATSreturn_void() ;
} /* end of [*_dynload] */

/*
** the ATS runtime
*/
#ifndef _ATS_CCOMP_RUNTIME_NONE
#include "pats_ccomp_runtime.c"
#include "pats_ccomp_runtime2_dats.c"
#include "pats_ccomp_runtime_trywith.c"
#endif /* _ATS_CCOMP_RUNTIME_NONE */

/*
** the [main] implementation
*/
int
main
(
int argc, char **argv, char **envp
) {
int err = 0 ;
_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$projects_057$org_056$ats_055$lang_056$postiats_056$jats_057$test_057$atof_056$dats__dynload() ;
ATSmainats_argc_argv_0(argc, argv, err) ;
return (err) ;
} /* end of [main] */
