/*
**
** The C code is generated by ATS/Postiats
** The compilation time is: 2013-7-3: 16h:41m
**
*/

/*
** include runtime header files
*/
#ifndef _ATS_CCOMP_HEADER_NONE
#include "pats_ccomp_config.h"
#include "pats_ccomp_basics.h"
#include "pats_ccomp_typedefs.h"
#include "pats_ccomp_instrset.h"
#include "pats_ccomp_memalloc.h"
#include "pats_ccomp_memalloca.h"
#include "pats_ccomp_exception.h"
#endif /* _ATS_CCOMP_HEADER_NONE */


/*
** include prelude cats files
*/
#ifndef _ATS_CCOMP_PRELUDE_NONE
//
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/memory.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/strptr.cats"
//
#include "prelude/CATS/filebas.cats"
//
#include "prelude/CATS/list.cats"
#include "prelude/CATS/option.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/arrayptr.cats"
#include "prelude/CATS/arrayref.cats"
#include "prelude/CATS/matrix.cats"
#include "prelude/CATS/matrixptr.cats"
//
#endif /* _ATS_CCOMP_PRELUDE_NONE */

/*
staload-prologues(beg)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/integer.dats: 1636(line=51, offs=1) -- 1675(line=51, offs=40)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/integer.dats: 26347(line=693, offs=1) -- 26378(line=693, offs=32)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/libc/SATS/stdlib.sats: 1379(line=35, offs=1) -- 1418(line=37, offs=3)
*/

#include "libc/CATS/stdlib.cats"
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/libc/SATS/stdlib.sats: 1814(line=54, offs=1) -- 1854(line=55, offs=33)
*/
/*
staload-prologues(end)
*/
/*
typedefs-for-tyrecs-and-tysums(beg)
*/
/*
typedefs-for-tyrecs-and-tysums(end)
*/
/*
dynconlst-declaration(beg)
*/
/*
dynconlst-declaration(end)
*/
/*
dyncstlst-declaration(beg)
*/
ATSdyncst_mac(atspre_assert_errmsg_bool0) ;
/*
dyncstlst-declaration(end)
*/
/*
dynvalist-implementation(beg)
*/
/*
dynvalist-implementation(end)
*/
/*
exnconlst-declaration(beg)
*/
extern void the_atsexncon_initize (atstype_exncon *d2c, char *exnmsg) ;
/*
exnconlst-declaration(end)
*/
/*
assumelst-declaration(beg)
*/
/*
assumelst-declaration(end)
*/
ATSstaticdec()
atstkind_t0ype(atstype_int)
f91_0(atstkind_t0ype(atstype_int)) ;

#if(0)
#if(0)
ATSglobaldec()
atstkind_t0ype(atstype_bool)
ATSLIB_056$prelude_gte_g0int_int$1(atstkind_t0ype(atstyvar_type(tk)), atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstaticdec()
atstkind_t0ype(atstype_bool)
ATSLIB_056$prelude_gte_g0int_int$1$1(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

#if(0)
#if(0)
ATSglobaldec()
atstkind_t0ype(atstype_bool)
ATSLIB_056$prelude_eq_g0int_int$8(atstkind_t0ype(atstyvar_type(tk)), atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstaticdec()
atstkind_t0ype(atstype_bool)
ATSLIB_056$prelude_eq_g0int_int$8$1(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

ATSstaticdec()
atstkind_t0ype(atstype_bool)
ATSLIB_056$prelude_eq_g0int_int$8$2(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

ATSstaticdec()
atstkind_t0ype(atstype_bool)
ATSLIB_056$prelude_eq_g0int_int$8$3(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

ATSstaticdec()
atstkind_t0ype(atstype_bool)
ATSLIB_056$prelude_eq_g0int_int$8$4(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

ATSstaticdec()
atstkind_t0ype(atstype_bool)
ATSLIB_056$prelude_eq_g0int_int$8$5(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

ATSstaticdec()
atstkind_t0ype(atstype_bool)
ATSLIB_056$prelude_eq_g0int_int$8$6(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

ATSstaticdec()
atstkind_t0ype(atstype_bool)
ATSLIB_056$prelude_eq_g0int_int$8$7(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

ATSstaticdec()
atstkind_t0ype(atstype_bool)
ATSLIB_056$prelude_eq_g0int_int$8$8(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

ATSstaticdec()
atstkind_t0ype(atstype_bool)
ATSLIB_056$prelude_eq_g0int_int$8$9(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

ATSstaticdec()
atstkind_t0ype(atstype_bool)
ATSLIB_056$prelude_eq_g0int_int$8$10(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

#if(0)
ATSglobaldec()
atsvoid_t0ype
mainats_void_0() ;
#endif // end of [QUALIFIED]

/*
/home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/f91.dats: 173(line=12, offs=5) -- 240(line=13, offs=48)
*/
/*
local: f91_0$0(level=0)
global: f91_0$0(level=0)
local: 
global: 
*/
ATSstaticdec()
atstkind_t0ype(atstype_int)
f91_0(atstkind_t0ype(atstype_int) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret0, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp1, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp6, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp7, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_f91_0:
ATSINSmove(tmp1, ATSLIB_056$prelude_gte_g0int_int$1$1(arg0, ATSPMVi0nt(101))) ;
ATSif(
tmp1
) ATSthen() {
ATSINSmove(tmpret0, atspre_g0int_sub_int(arg0, ATSPMVi0nt(10))) ;
} ATSelse() {
ATSINSmove(tmp7, atspre_g0int_add_int(arg0, ATSPMVi0nt(11))) ;
ATSINSmove(tmp6, f91_0(tmp7)) ;
ATSINSmove(tmpret0, f91_0(tmp6)) ;
} /* ATSendif */
/* funbodyinstrlst(end) */
ATSreturn(tmpret0) ;
} /* end of [f91_0] */

#if(0)
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/integer.dats: 27564(line=740, offs=15) -- 27605(line=740, offs=56)
*/
/*
local: 
global: gte_g0int_int$1$0(level=0)
local: 
global: 
*/
ATSglobaldec()
/*
imparg = tk(3149)
tmparg = S2Evar(tk(3149))
tmpsub = None()
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056$prelude_gte_g0int_int$1(atstkind_t0ype(atstyvar_type(tk)) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret2, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp3, atstkind_t0ype(atstyvar_type(tk))) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_gte_g0int_int:
ATSINSmove(tmp3, PMVtmpltcst(g0int2int<S2Eextkind(atstype_int), S2Evar(tk(3149))>)(arg1)) ;
ATSINSmove(tmpret2, PMVtmpltcst(g0int_gte<S2Evar(tk(3149))>)(arg0, tmp3)) ;
/* funbodyinstrlst(end) */
ATSreturn(tmpret2) ;
} /* end of [ATSLIB_056$prelude_gte_g0int_int$1] */
#endif // end of [TEMPLATE]

/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/integer.dats: 27564(line=740, offs=15) -- 27605(line=740, offs=56)
*/
/*
local: 
global: gte_g0int_int$1$1(level=1)
local: 
global: 
*/
ATSstaticdec()
/*
imparg = tk(3149)
tmparg = S2Evar(tk(3149))
tmpsub = Some(tk(3149) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056$prelude_gte_g0int_int$1$1(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmp2$1, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp3$1, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_gte_g0int_int:
ATSINSmove(tmp3$1, atspre_g0int2int_int_int(arg1)) ;
ATSINSmove(tmp2$1, atspre_g0int_gte_int(arg0, tmp3$1)) ;
/* funbodyinstrlst(end) */
ATSreturn(tmp2$1) ;
} /* end of [ATSLIB_056$prelude_gte_g0int_int$1$1] */

#if(0)
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/integer.dats: 27633(line=742, offs=14) -- 27673(line=742, offs=54)
*/
/*
local: 
global: eq_g0int_int$8$0(level=0)
local: 
global: 
*/
ATSglobaldec()
/*
imparg = tk(3150)
tmparg = S2Evar(tk(3150))
tmpsub = None()
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056$prelude_eq_g0int_int$8(atstkind_t0ype(atstyvar_type(tk)) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret11, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp12, atstkind_t0ype(atstyvar_type(tk))) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_eq_g0int_int:
ATSINSmove(tmp12, PMVtmpltcst(g0int2int<S2Eextkind(atstype_int), S2Evar(tk(3150))>)(arg1)) ;
ATSINSmove(tmpret11, PMVtmpltcst(g0int_eq<S2Evar(tk(3150))>)(arg0, tmp12)) ;
/* funbodyinstrlst(end) */
ATSreturn(tmpret11) ;
} /* end of [ATSLIB_056$prelude_eq_g0int_int$8] */
#endif // end of [TEMPLATE]

/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/integer.dats: 27633(line=742, offs=14) -- 27673(line=742, offs=54)
*/
/*
local: 
global: eq_g0int_int$8$1(level=1)
local: 
global: 
*/
ATSstaticdec()
/*
imparg = tk(3150)
tmparg = S2Evar(tk(3150))
tmpsub = Some(tk(3150) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056$prelude_eq_g0int_int$8$1(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmp11$1, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp12$1, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_eq_g0int_int:
ATSINSmove(tmp12$1, atspre_g0int2int_int_int(arg1)) ;
ATSINSmove(tmp11$1, atspre_g0int_eq_int(arg0, tmp12$1)) ;
/* funbodyinstrlst(end) */
ATSreturn(tmp11$1) ;
} /* end of [ATSLIB_056$prelude_eq_g0int_int$8$1] */

/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/integer.dats: 27633(line=742, offs=14) -- 27673(line=742, offs=54)
*/
/*
local: 
global: eq_g0int_int$8$2(level=1)
local: 
global: 
*/
ATSstaticdec()
/*
imparg = tk(3150)
tmparg = S2Evar(tk(3150))
tmpsub = Some(tk(3150) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056$prelude_eq_g0int_int$8$2(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmp11$2, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp12$2, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_eq_g0int_int:
ATSINSmove(tmp12$2, atspre_g0int2int_int_int(arg1)) ;
ATSINSmove(tmp11$2, atspre_g0int_eq_int(arg0, tmp12$2)) ;
/* funbodyinstrlst(end) */
ATSreturn(tmp11$2) ;
} /* end of [ATSLIB_056$prelude_eq_g0int_int$8$2] */

/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/integer.dats: 27633(line=742, offs=14) -- 27673(line=742, offs=54)
*/
/*
local: 
global: eq_g0int_int$8$3(level=1)
local: 
global: 
*/
ATSstaticdec()
/*
imparg = tk(3150)
tmparg = S2Evar(tk(3150))
tmpsub = Some(tk(3150) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056$prelude_eq_g0int_int$8$3(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmp11$3, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp12$3, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_eq_g0int_int:
ATSINSmove(tmp12$3, atspre_g0int2int_int_int(arg1)) ;
ATSINSmove(tmp11$3, atspre_g0int_eq_int(arg0, tmp12$3)) ;
/* funbodyinstrlst(end) */
ATSreturn(tmp11$3) ;
} /* end of [ATSLIB_056$prelude_eq_g0int_int$8$3] */

/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/integer.dats: 27633(line=742, offs=14) -- 27673(line=742, offs=54)
*/
/*
local: 
global: eq_g0int_int$8$4(level=1)
local: 
global: 
*/
ATSstaticdec()
/*
imparg = tk(3150)
tmparg = S2Evar(tk(3150))
tmpsub = Some(tk(3150) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056$prelude_eq_g0int_int$8$4(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmp11$4, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp12$4, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_eq_g0int_int:
ATSINSmove(tmp12$4, atspre_g0int2int_int_int(arg1)) ;
ATSINSmove(tmp11$4, atspre_g0int_eq_int(arg0, tmp12$4)) ;
/* funbodyinstrlst(end) */
ATSreturn(tmp11$4) ;
} /* end of [ATSLIB_056$prelude_eq_g0int_int$8$4] */

/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/integer.dats: 27633(line=742, offs=14) -- 27673(line=742, offs=54)
*/
/*
local: 
global: eq_g0int_int$8$5(level=1)
local: 
global: 
*/
ATSstaticdec()
/*
imparg = tk(3150)
tmparg = S2Evar(tk(3150))
tmpsub = Some(tk(3150) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056$prelude_eq_g0int_int$8$5(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmp11$5, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp12$5, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_eq_g0int_int:
ATSINSmove(tmp12$5, atspre_g0int2int_int_int(arg1)) ;
ATSINSmove(tmp11$5, atspre_g0int_eq_int(arg0, tmp12$5)) ;
/* funbodyinstrlst(end) */
ATSreturn(tmp11$5) ;
} /* end of [ATSLIB_056$prelude_eq_g0int_int$8$5] */

/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/integer.dats: 27633(line=742, offs=14) -- 27673(line=742, offs=54)
*/
/*
local: 
global: eq_g0int_int$8$6(level=1)
local: 
global: 
*/
ATSstaticdec()
/*
imparg = tk(3150)
tmparg = S2Evar(tk(3150))
tmpsub = Some(tk(3150) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056$prelude_eq_g0int_int$8$6(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmp11$6, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp12$6, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_eq_g0int_int:
ATSINSmove(tmp12$6, atspre_g0int2int_int_int(arg1)) ;
ATSINSmove(tmp11$6, atspre_g0int_eq_int(arg0, tmp12$6)) ;
/* funbodyinstrlst(end) */
ATSreturn(tmp11$6) ;
} /* end of [ATSLIB_056$prelude_eq_g0int_int$8$6] */

/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/integer.dats: 27633(line=742, offs=14) -- 27673(line=742, offs=54)
*/
/*
local: 
global: eq_g0int_int$8$7(level=1)
local: 
global: 
*/
ATSstaticdec()
/*
imparg = tk(3150)
tmparg = S2Evar(tk(3150))
tmpsub = Some(tk(3150) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056$prelude_eq_g0int_int$8$7(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmp11$7, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp12$7, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_eq_g0int_int:
ATSINSmove(tmp12$7, atspre_g0int2int_int_int(arg1)) ;
ATSINSmove(tmp11$7, atspre_g0int_eq_int(arg0, tmp12$7)) ;
/* funbodyinstrlst(end) */
ATSreturn(tmp11$7) ;
} /* end of [ATSLIB_056$prelude_eq_g0int_int$8$7] */

/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/integer.dats: 27633(line=742, offs=14) -- 27673(line=742, offs=54)
*/
/*
local: 
global: eq_g0int_int$8$8(level=1)
local: 
global: 
*/
ATSstaticdec()
/*
imparg = tk(3150)
tmparg = S2Evar(tk(3150))
tmpsub = Some(tk(3150) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056$prelude_eq_g0int_int$8$8(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmp11$8, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp12$8, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_eq_g0int_int:
ATSINSmove(tmp12$8, atspre_g0int2int_int_int(arg1)) ;
ATSINSmove(tmp11$8, atspre_g0int_eq_int(arg0, tmp12$8)) ;
/* funbodyinstrlst(end) */
ATSreturn(tmp11$8) ;
} /* end of [ATSLIB_056$prelude_eq_g0int_int$8$8] */

/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/integer.dats: 27633(line=742, offs=14) -- 27673(line=742, offs=54)
*/
/*
local: 
global: eq_g0int_int$8$9(level=1)
local: 
global: 
*/
ATSstaticdec()
/*
imparg = tk(3150)
tmparg = S2Evar(tk(3150))
tmpsub = Some(tk(3150) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056$prelude_eq_g0int_int$8$9(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmp11$9, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp12$9, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_eq_g0int_int:
ATSINSmove(tmp12$9, atspre_g0int2int_int_int(arg1)) ;
ATSINSmove(tmp11$9, atspre_g0int_eq_int(arg0, tmp12$9)) ;
/* funbodyinstrlst(end) */
ATSreturn(tmp11$9) ;
} /* end of [ATSLIB_056$prelude_eq_g0int_int$8$9] */

/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/integer.dats: 27633(line=742, offs=14) -- 27673(line=742, offs=54)
*/
/*
local: 
global: eq_g0int_int$8$10(level=1)
local: 
global: 
*/
ATSstaticdec()
/*
imparg = tk(3150)
tmparg = S2Evar(tk(3150))
tmpsub = Some(tk(3150) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056$prelude_eq_g0int_int$8$10(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmp11$10, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp12$10, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_eq_g0int_int:
ATSINSmove(tmp12$10, atspre_g0int2int_int_int(arg1)) ;
ATSINSmove(tmp11$10, atspre_g0int_eq_int(arg0, tmp12$10)) ;
/* funbodyinstrlst(end) */
ATSreturn(tmp11$10) ;
} /* end of [ATSLIB_056$prelude_eq_g0int_int$8$10] */

/*
/home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/f91.dats: 295(line=19, offs=7) -- 699(line=35, offs=4)
*/
/*
local: f91_0$0(level=0)
global: f91_0$0(level=0), mainats_void_0$7$0(level=0)
local: 
global: 
*/
ATSglobaldec()
atsvoid_t0ype
mainats_void_0()
{
/* tmpvardeclst(beg) */
ATStmpdec_void(tmpret8, atsvoid_t0ype) ;
ATStmpdec_void(tmp9, atsvoid_t0ype) ;
ATStmpdec(tmp10, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp15, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp16, atstkind_t0ype(atstype_int)) ;
ATStmpdec_void(tmp17, atsvoid_t0ype) ;
ATStmpdec(tmp18, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp21, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp22, atstkind_t0ype(atstype_int)) ;
ATStmpdec_void(tmp23, atsvoid_t0ype) ;
ATStmpdec(tmp24, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp27, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp28, atstkind_t0ype(atstype_int)) ;
ATStmpdec_void(tmp29, atsvoid_t0ype) ;
ATStmpdec(tmp30, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp33, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp34, atstkind_t0ype(atstype_int)) ;
ATStmpdec_void(tmp35, atsvoid_t0ype) ;
ATStmpdec(tmp36, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp39, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp40, atstkind_t0ype(atstype_int)) ;
ATStmpdec_void(tmp41, atsvoid_t0ype) ;
ATStmpdec(tmp42, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp45, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp46, atstkind_t0ype(atstype_int)) ;
ATStmpdec_void(tmp47, atsvoid_t0ype) ;
ATStmpdec(tmp48, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp51, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp52, atstkind_t0ype(atstype_int)) ;
ATStmpdec_void(tmp53, atsvoid_t0ype) ;
ATStmpdec(tmp54, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp57, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp58, atstkind_t0ype(atstype_int)) ;
ATStmpdec_void(tmp59, atsvoid_t0ype) ;
ATStmpdec(tmp60, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp63, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp64, atstkind_t0ype(atstype_int)) ;
ATStmpdec_void(tmp65, atsvoid_t0ype) ;
ATStmpdec(tmp66, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp69, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp70, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_main_void_0:
/*
letpush(beg)
*/
/* (*nothing*) */
ATSINSmove(tmp16, atspre_g1int_add_int(ATSPMVi0nt(0), ATSPMVi0nt(0))) ;
ATSINSmove(tmp15, f91_0(tmp16)) ;
ATSINSmove(tmp10, ATSLIB_056$prelude_eq_g0int_int$8$1(tmp15, ATSPMVi0nt(91))) ;
ATSINSmove_void(tmp9, atspre_assert_errmsg_bool0(tmp10, ATSCSTSPmyloc("/home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/f91.dats: 326(line=22, offs=10) -- 351(line=22, offs=35)"))) ;
ATSINSmove(tmp22, atspre_g1int_add_int(ATSPMVi0nt(0), ATSPMVi0nt(1))) ;
ATSINSmove(tmp21, f91_0(tmp22)) ;
ATSINSmove(tmp18, ATSLIB_056$prelude_eq_g0int_int$8$2(tmp21, ATSPMVi0nt(91))) ;
ATSINSmove_void(tmp17, atspre_assert_errmsg_bool0(tmp18, ATSCSTSPmyloc("/home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/f91.dats: 362(line=23, offs=10) -- 387(line=23, offs=35)"))) ;
ATSINSmove(tmp28, atspre_g1int_add_int(ATSPMVi0nt(0), ATSPMVi0nt(2))) ;
ATSINSmove(tmp27, f91_0(tmp28)) ;
ATSINSmove(tmp24, ATSLIB_056$prelude_eq_g0int_int$8$3(tmp27, ATSPMVi0nt(91))) ;
ATSINSmove_void(tmp23, atspre_assert_errmsg_bool0(tmp24, ATSCSTSPmyloc("/home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/f91.dats: 398(line=24, offs=10) -- 423(line=24, offs=35)"))) ;
ATSINSmove(tmp34, atspre_g1int_add_int(ATSPMVi0nt(0), ATSPMVi0nt(3))) ;
ATSINSmove(tmp33, f91_0(tmp34)) ;
ATSINSmove(tmp30, ATSLIB_056$prelude_eq_g0int_int$8$4(tmp33, ATSPMVi0nt(91))) ;
ATSINSmove_void(tmp29, atspre_assert_errmsg_bool0(tmp30, ATSCSTSPmyloc("/home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/f91.dats: 434(line=25, offs=10) -- 459(line=25, offs=35)"))) ;
ATSINSmove(tmp40, atspre_g1int_add_int(ATSPMVi0nt(0), ATSPMVi0nt(4))) ;
ATSINSmove(tmp39, f91_0(tmp40)) ;
ATSINSmove(tmp36, ATSLIB_056$prelude_eq_g0int_int$8$5(tmp39, ATSPMVi0nt(91))) ;
ATSINSmove_void(tmp35, atspre_assert_errmsg_bool0(tmp36, ATSCSTSPmyloc("/home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/f91.dats: 470(line=26, offs=10) -- 495(line=26, offs=35)"))) ;
ATSINSmove(tmp46, atspre_g1int_add_int(ATSPMVi0nt(0), ATSPMVi0nt(5))) ;
ATSINSmove(tmp45, f91_0(tmp46)) ;
ATSINSmove(tmp42, ATSLIB_056$prelude_eq_g0int_int$8$6(tmp45, ATSPMVi0nt(91))) ;
ATSINSmove_void(tmp41, atspre_assert_errmsg_bool0(tmp42, ATSCSTSPmyloc("/home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/f91.dats: 506(line=27, offs=10) -- 531(line=27, offs=35)"))) ;
ATSINSmove(tmp52, atspre_g1int_add_int(ATSPMVi0nt(0), ATSPMVi0nt(6))) ;
ATSINSmove(tmp51, f91_0(tmp52)) ;
ATSINSmove(tmp48, ATSLIB_056$prelude_eq_g0int_int$8$7(tmp51, ATSPMVi0nt(91))) ;
ATSINSmove_void(tmp47, atspre_assert_errmsg_bool0(tmp48, ATSCSTSPmyloc("/home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/f91.dats: 542(line=28, offs=10) -- 567(line=28, offs=35)"))) ;
ATSINSmove(tmp58, atspre_g1int_add_int(ATSPMVi0nt(0), ATSPMVi0nt(7))) ;
ATSINSmove(tmp57, f91_0(tmp58)) ;
ATSINSmove(tmp54, ATSLIB_056$prelude_eq_g0int_int$8$8(tmp57, ATSPMVi0nt(91))) ;
ATSINSmove_void(tmp53, atspre_assert_errmsg_bool0(tmp54, ATSCSTSPmyloc("/home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/f91.dats: 578(line=29, offs=10) -- 603(line=29, offs=35)"))) ;
ATSINSmove(tmp64, atspre_g1int_add_int(ATSPMVi0nt(0), ATSPMVi0nt(8))) ;
ATSINSmove(tmp63, f91_0(tmp64)) ;
ATSINSmove(tmp60, ATSLIB_056$prelude_eq_g0int_int$8$9(tmp63, ATSPMVi0nt(91))) ;
ATSINSmove_void(tmp59, atspre_assert_errmsg_bool0(tmp60, ATSCSTSPmyloc("/home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/f91.dats: 614(line=30, offs=10) -- 639(line=30, offs=35)"))) ;
ATSINSmove(tmp70, atspre_g1int_add_int(ATSPMVi0nt(0), ATSPMVi0nt(9))) ;
ATSINSmove(tmp69, f91_0(tmp70)) ;
ATSINSmove(tmp66, ATSLIB_056$prelude_eq_g0int_int$8$10(tmp69, ATSPMVi0nt(91))) ;
ATSINSmove_void(tmp65, atspre_assert_errmsg_bool0(tmp66, ATSCSTSPmyloc("/home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/f91.dats: 650(line=31, offs=10) -- 675(line=31, offs=35)"))) ;
/*
letpush(end)
*/

ATSINSmove_void(tmpret8, ATSempty()) ;
/*
INSletpop()
*/
/* funbodyinstrlst(end) */
ATSreturn_void(tmpret8) ;
} /* end of [mainats_void_0] */


/*
** for initialization(dynloading)
*/
atsvoid_t0ype
_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$projects_057$org_056$ats_055$lang_056$postiats_056$jats_057$test_057$f91_056$dats__dynload()
{
ATSdynload0(
_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$projects_057$org_056$ats_055$lang_056$postiats_056$jats_057$test_057$f91_056$dats__dynloadflag
) ;
ATSif(
ATSCKiseqz(
_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$projects_057$org_056$ats_055$lang_056$postiats_056$jats_057$test_057$f91_056$dats__dynloadflag
)
) ATSthen() {
ATSdynloadset(_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$projects_057$org_056$ats_055$lang_056$postiats_056$jats_057$test_057$f91_056$dats__dynloadflag) ;
/*
dynexnlst-initize(beg)
*/
/*
dynexnlst-initize(end)
*/
} /* ATSendif */
ATSreturn_void() ;
} /* end of [*_dynload] */

/*
** the ATS runtime
*/
#ifndef _ATS_CCOMP_RUNTIME_NONE
#include "pats_ccomp_runtime.c"
#include "pats_ccomp_runtime2_dats.c"
#include "pats_ccomp_runtime_trywith.c"
#endif /* _ATS_CCOMP_RUNTIME_NONE */

/*
** the [main] implementation
*/
int
main
(
int argc, char **argv, char **envp
) {
int err = 0 ;
_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$projects_057$org_056$ats_055$lang_056$postiats_056$jats_057$test_057$f91_056$dats__dynload() ;
ATSmainats_void_0(err) ;
return (err) ;
} /* end of [main] */
