/*
**
** The C code is generated by ATS/Postiats
** The compilation time is: 2013-4-26: 15h:37m
**
*/

/*
** include runtime header files
*/
#ifndef _ATS_CCOMP_HEADER_NONE
#include "pats_ccomp_config.h"
#include "pats_ccomp_basics.h"
#include "pats_ccomp_typedefs.h"
#include "pats_ccomp_instrset.h"
#include "pats_ccomp_exception.h"
#include "pats_ccomp_memalloc.h"
#include "pats_ccomp_memalloca.h"
#endif /* _ATS_CCOMP_HEADER_NONE */


/*
** include prelude cats files
*/
#ifndef _ATS_CCOMP_PRELUDE_NONE
//
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/memory.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/strptr.cats"
//
#include "prelude/CATS/filebas.cats"
//
#include "prelude/CATS/list.cats"
#include "prelude/CATS/option.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/arrayptr.cats"
#include "prelude/CATS/arrayref.cats"
#include "prelude/CATS/matrix.cats"
#include "prelude/CATS/matrixptr.cats"
//
#endif /* _ATS_CCOMP_PRELUDE_NONE */

/*
staload-prologues(beg)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/integer.dats: 25237(line=637, offs=1) -- 25268(line=637, offs=32)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/libc/SATS/stdlib.sats: 1379(line=35, offs=1) -- 1418(line=37, offs=3)
*/

#include "libc/CATS/stdlib.cats"
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/libc/SATS/stdlib.sats: 1814(line=54, offs=1) -- 1854(line=55, offs=33)
*/
/*
staload-prologues(end)
*/
/*
typedefs-for-tyrecs-and-tysums(beg)
*/
/*
typedefs-for-tyrecs-and-tysums(end)
*/
/*
dyncstlst-declaration(beg)
*/
ATSdyncst_mac(atspre_print_string) ;
ATSdyncst_mac(atspre_print_int) ;
ATSdyncst_mac(atspre_print_newline) ;
/*
dyncstlst-declaration(end)
*/
ATSstaticdec()
atstkind_t0ype(atstype_int)
fact_0(atstkind_t0ype(atstype_int)) ;

#if(0)
#if(0)
ATSglobaldec()
atstkind_t0ype(atstype_bool)
_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$ATS_055$Postiats_057$prelude_057$SATS_057$integer_056$sats_gt_g1int_int$1(atstkind_t0ype(atstyvar_type(tk)), atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstaticdec()
atstkind_t0ype(atstype_bool)
_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$ATS_055$Postiats_057$prelude_057$SATS_057$integer_056$sats_gt_g1int_int$1$1(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

#if(0)
ATSglobaldec()
atstkind_t0ype(atstype_int)
mainats_void_int() ;
#endif // end of [QUALIFIED]

/*
/home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/fact.dats: 368(line=19, offs=5) -- 665(line=37, offs=4)
*/
/*
local: fact_0$0(0)
global: fact_0$0(0)
local: 
global: 
*/
ATSstaticdec()
atstkind_t0ype(atstype_int)
fact_0(atstkind_t0ype(atstype_int) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret0, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp1, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp6, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp7, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp8, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_fact_0:
/*
letpush(beg)
*/
/*
letpush(end)
*/

ATSINSmove(tmp1, _057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$ATS_055$Postiats_057$prelude_057$SATS_057$integer_056$sats_gt_g1int_int$1$1(arg0, ATSPMVi0nt(0))) ;
ATSif(
tmp1
) ATSthen() {
/*
letpush(beg)
*/
ATSINSmove(tmp7, atspre_g1int_sub_int(arg0, ATSPMVi0nt(1))) ;
ATSINSmove(tmp6, fact_0(tmp7)) ;
/* (*nothing*) */
ATSINSmove(tmp8, atspre_g1int_mul_int(arg0, tmp6)) ;
/*
letpush(end)
*/

ATSINSmove(tmpret0, tmp8) ;
/*
INSletpop()
*/
} ATSelse() {
ATSINSmove(tmpret0, ATSPMVi0nt(1)) ;
} /* ATSendif */
/*
INSletpop()
*/
/* funbodyinstrlst(end) */
ATSreturn(tmpret0) ;
} /* end of [fact_0] */

#if(0)
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/integer.dats: 26897(line=700, offs=14) -- 26937(line=700, offs=54)
*/
/*
local: 
global: gt_g1int_int$1$0(0)
local: 
global: 
*/
ATSglobaldec()
/*
imparg = tk(2916)
tmparg = S2Evar(tk(2916))
tmpsub = None()
*/
atstkind_t0ype(atstype_bool)
_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$ATS_055$Postiats_057$prelude_057$SATS_057$integer_056$sats_gt_g1int_int$1(atstkind_t0ype(atstyvar_type(tk)) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret2, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp3, atstkind_t0ype(atstyvar_type(tk))) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_gt_g1int_int:
ATSINSmove(tmp3, PMVtmpltcst(g1int2int<S2EVar(389->S2Eextkind(atstype_int)), S2EVar(390->S2Evar(tk(2916)))>)(arg1)) ;
ATSINSmove(tmpret2, PMVtmpltcst(g1int_gt<S2Evar(tk(2916))>)(arg0, tmp3)) ;
/* funbodyinstrlst(end) */
ATSreturn(tmpret2) ;
} /* end of [_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$ATS_055$Postiats_057$prelude_057$SATS_057$integer_056$sats_gt_g1int_int$1] */
#endif // end of [TEMPLATE]

/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/integer.dats: 26897(line=700, offs=14) -- 26937(line=700, offs=54)
*/
/*
local: 
global: gt_g1int_int$1$1(1)
local: 
global: 
*/
ATSstaticdec()
/*
imparg = tk(2916)
tmparg = S2Evar(tk(2916))
tmpsub = Some(tk(2916) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$ATS_055$Postiats_057$prelude_057$SATS_057$integer_056$sats_gt_g1int_int$1$1(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmp2$1, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp3$1, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_gt_g1int_int:
ATSINSmove(tmp3$1, atspre_g1int2int_int_int(arg1)) ;
ATSINSmove(tmp2$1, atspre_g1int_gt_int(arg0, tmp3$1)) ;
/* funbodyinstrlst(end) */
ATSreturn(tmp2$1) ;
} /* end of [_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$ATS_055$Postiats_057$prelude_057$SATS_057$integer_056$sats_gt_g1int_int$1$1] */

/*
/home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/fact.dats: 702(line=40, offs=6) -- 790(line=44, offs=2)
*/
/*
local: fact_0$0(0)
global: fact_0$0(0), mainats_void_int$7$0(0)
local: 
global: 
*/
ATSglobaldec()
atstkind_t0ype(atstype_int)
mainats_void_int()
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret9, atstkind_t0ype(atstype_int)) ;
ATStmpdec_void(tmp10, atsvoid_t0ype) ;
ATStmpdec_void(tmp11, atsvoid_t0ype) ;
ATStmpdec_void(tmp12, atsvoid_t0ype) ;
ATStmpdec_void(tmp13, atsvoid_t0ype) ;
ATStmpdec(tmp14, atstkind_t0ype(atstype_int)) ;
ATStmpdec_void(tmp15, atsvoid_t0ype) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_main_void_int:
/*
letpush(beg)
*/
/* (*nothing*) */
ATSINSmove_void(tmp10, atspre_print_string(ATSPMVstring("fact("))) ;
ATSINSmove_void(tmp11, atspre_print_int(ATSPMVi0nt(12))) ;
ATSINSmove_void(tmp12, atspre_print_string(ATSPMVstring(") = "))) ;
ATSINSmove(tmp14, fact_0(ATSPMVi0nt(12))) ;
ATSINSmove_void(tmp13, atspre_print_int(ATSselrecsin(tmp14, atstkind_t0ype(atstype_int), atslab$1))) ;
ATSINSmove_void(tmp15, atspre_print_newline()) ;
/*
letpush(end)
*/

ATSINSmove(tmpret9, ATSPMVi0nt(0)) ;
/*
INSletpop()
*/
/* funbodyinstrlst(end) */
ATSreturn(tmpret9) ;
} /* end of [mainats_void_int] */


/*
** for initialization(dynloading)
*/
atsvoid_t0ype
_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$projects_057$org_056$ats_055$lang_056$postiats_056$jats_057$test_057$fact_056$dats__dynload()
{
ATSdynload0(
_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$projects_057$org_056$ats_055$lang_056$postiats_056$jats_057$test_057$fact_056$dats__dynloadflag
) ;
ATSif(
ATSCKiseqz(
_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$projects_057$org_056$ats_055$lang_056$postiats_056$jats_057$test_057$fact_056$dats__dynloadflag
)
) ATSthen() {
ATSdynloadset(_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$projects_057$org_056$ats_055$lang_056$postiats_056$jats_057$test_057$fact_056$dats__dynloadflag) ;
} /* ATSendif */
ATSreturn_void() ;
} /* end of [*_dynload] */

/*
** the ATS runtime
*/
#ifndef _ATS_CCOMP_RUNTIME_NONE
#include "pats_ccomp_runtime.c"
#endif /* _ATS_CCOMP_RUNTIME_NONE */

/*
** the [main] implementation
*/
int
main
(
int argc, char **argv, char **envp
) {
int err = 0 ;
_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$projects_057$org_056$ats_055$lang_056$postiats_056$jats_057$test_057$fact_056$dats__dynload() ;
ATSmainats_void_int(err) ;
return (err) ;
} /* end of [main] */
