/*
**
** The C code is generated by ATS/Postiats
** The compilation time is: 2013-7-3: 16h:41m
**
*/

/*
** include runtime header files
*/
#ifndef _ATS_CCOMP_HEADER_NONE
#include "pats_ccomp_config.h"
#include "pats_ccomp_basics.h"
#include "pats_ccomp_typedefs.h"
#include "pats_ccomp_instrset.h"
#include "pats_ccomp_memalloc.h"
#include "pats_ccomp_memalloca.h"
#include "pats_ccomp_exception.h"
#endif /* _ATS_CCOMP_HEADER_NONE */


/*
** include prelude cats files
*/
#ifndef _ATS_CCOMP_PRELUDE_NONE
//
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/memory.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/strptr.cats"
//
#include "prelude/CATS/filebas.cats"
//
#include "prelude/CATS/list.cats"
#include "prelude/CATS/option.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/arrayptr.cats"
#include "prelude/CATS/arrayref.cats"
#include "prelude/CATS/matrix.cats"
#include "prelude/CATS/matrixptr.cats"
//
#endif /* _ATS_CCOMP_PRELUDE_NONE */

/*
staload-prologues(beg)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/integer.dats: 1636(line=51, offs=1) -- 1675(line=51, offs=40)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/integer.dats: 26347(line=693, offs=1) -- 26378(line=693, offs=32)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/libc/SATS/stdlib.sats: 1379(line=35, offs=1) -- 1418(line=37, offs=3)
*/

#include "libc/CATS/stdlib.cats"
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/libc/SATS/stdlib.sats: 1814(line=54, offs=1) -- 1854(line=55, offs=33)
*/
/*
staload-prologues(end)
*/
/*
typedefs-for-tyrecs-and-tysums(beg)
*/
typedef
struct {
atstkind_t0ype(atstype_int) atslab$0; 
atstkind_t0ype(atstype_int) atslab$1; 
} postiats_tyrec_0 ;
/*
typedefs-for-tyrecs-and-tysums(end)
*/
/*
dynconlst-declaration(beg)
*/
/*
dynconlst-declaration(end)
*/
/*
dyncstlst-declaration(beg)
*/
ATSdyncst_extfun(_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$projects_057$org_056$ats_055$lang_056$postiats_056$jats_057$test_057$fib_056$dats_fib, (atstkind_t0ype(atstype_int)), atstkind_t0ype(atstype_int)) ;
ATSdyncst_mac(atspre_print_string) ;
ATSdyncst_mac(atspre_print_int) ;
ATSdyncst_mac(atspre_print_newline) ;
ATSdyncst_mac(atspre_assert_errmsg_bool0) ;
/*
dyncstlst-declaration(end)
*/
/*
dynvalist-implementation(beg)
*/
/*
dynvalist-implementation(end)
*/
/*
exnconlst-declaration(beg)
*/
extern void the_atsexncon_initize (atstype_exncon *d2c, char *exnmsg) ;
/*
exnconlst-declaration(end)
*/
/*
assumelst-declaration(beg)
*/
/*
assumelst-declaration(end)
*/
ATSstaticdec()
atsvoid_t0ype
loop_1(atsrefarg1_type(postiats_tyrec_0), atstkind_t0ype(atstype_int)) ;

#if(0)
#if(0)
ATSglobaldec()
atstkind_t0ype(atstype_bool)
ATSLIB_056$prelude_gt_g0int_int$2(atstkind_t0ype(atstyvar_type(tk)), atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstaticdec()
atstkind_t0ype(atstype_bool)
ATSLIB_056$prelude_gt_g0int_int$2$1(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

#if(0)
ATSglobaldec()
atstkind_t0ype(atstype_int)
_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$projects_057$org_056$ats_055$lang_056$postiats_056$jats_057$test_057$fib_056$dats_fib(atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]

#if(0)
#if(0)
ATSglobaldec()
atstkind_t0ype(atstype_bool)
ATSLIB_056$prelude_eq_g0int_int$9(atstkind_t0ype(atstyvar_type(tk)), atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstaticdec()
atstkind_t0ype(atstype_bool)
ATSLIB_056$prelude_eq_g0int_int$9$1(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

#if(0)
ATSglobaldec()
atstkind_t0ype(atstype_int)
mainats_void_int() ;
#endif // end of [QUALIFIED]

/*
/home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/fib.dats: 255(line=16, offs=5) -- 583(line=29, offs=4)
*/
/*
local: loop_1$0(level=1)
global: loop_1$0(level=1)
local: 
global: 
*/
ATSstaticdec()
atsvoid_t0ype
loop_1(atsrefarg1_type(postiats_tyrec_0) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec_void(tmpret1, atsvoid_t0ype) ;
ATStmpdec(tmp2, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp7, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp8, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp9, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp10, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_loop_1:
/*
letpush(beg)
*/
/*
letpush(end)
*/

ATSINSmove(tmp2, ATSLIB_056$prelude_gt_g0int_int$2$1(arg1, ATSPMVi0nt(0))) ;
ATSif(
tmp2
) ATSthen() {
/*
letpush(beg)
*/
ATSINSmove(tmp7, ATSSELfltrec(ATSderef(arg0, postiats_tyrec_0), postiats_tyrec_0, atslab$0)) ;
ATSINSmove(tmp8, ATSSELfltrec(ATSderef(arg0, postiats_tyrec_0), postiats_tyrec_0, atslab$1)) ;
ATSINSstore(ATSSELfltrec(ATSderef(arg0, postiats_tyrec_0), postiats_tyrec_0, atslab$0), tmp8) ;
ATSINSmove(tmp9, atspre_g0int_add_int(tmp7, tmp8)) ;
ATSINSstore(ATSSELfltrec(ATSderef(arg0, postiats_tyrec_0), postiats_tyrec_0, atslab$1), tmp9) ;
/*
letpush(end)
*/

ATSINSmove(tmp10, atspre_g0int_sub_int(arg1, ATSPMVi0nt(1))) ;
ATSINSmove_void(tmpret1, loop_1(ATSPMVrefarg1(arg0), tmp10)) ;
/*
INSletpop()
*/
} ATSelse() {
ATSINSmove_void(tmpret1, ATSempty()) ;
} /* ATSendif */
/*
INSletpop()
*/
/* funbodyinstrlst(end) */
ATSreturn_void(tmpret1) ;
} /* end of [loop_1] */

#if(0)
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/integer.dats: 27495(line=738, offs=14) -- 27535(line=738, offs=54)
*/
/*
local: 
global: gt_g0int_int$2$0(level=0)
local: 
global: 
*/
ATSglobaldec()
/*
imparg = tk(3148)
tmparg = S2Evar(tk(3148))
tmpsub = None()
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056$prelude_gt_g0int_int$2(atstkind_t0ype(atstyvar_type(tk)) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret3, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp4, atstkind_t0ype(atstyvar_type(tk))) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_gt_g0int_int:
ATSINSmove(tmp4, PMVtmpltcst(g0int2int<S2Eextkind(atstype_int), S2Evar(tk(3148))>)(arg1)) ;
ATSINSmove(tmpret3, PMVtmpltcst(g0int_gt<S2Evar(tk(3148))>)(arg0, tmp4)) ;
/* funbodyinstrlst(end) */
ATSreturn(tmpret3) ;
} /* end of [ATSLIB_056$prelude_gt_g0int_int$2] */
#endif // end of [TEMPLATE]

/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/integer.dats: 27495(line=738, offs=14) -- 27535(line=738, offs=54)
*/
/*
local: 
global: gt_g0int_int$2$1(level=2)
local: 
global: 
*/
ATSstaticdec()
/*
imparg = tk(3148)
tmparg = S2Evar(tk(3148))
tmpsub = Some(tk(3148) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056$prelude_gt_g0int_int$2$1(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmp3$1, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp4$1, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_gt_g0int_int:
ATSINSmove(tmp4$1, atspre_g0int2int_int_int(arg1)) ;
ATSINSmove(tmp3$1, atspre_g0int_gt_int(arg0, tmp4$1)) ;
/* funbodyinstrlst(end) */
ATSreturn(tmp3$1) ;
} /* end of [ATSLIB_056$prelude_gt_g0int_int$2$1] */

/*
/home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/fib.dats: 236(line=14, offs=15) -- 709(line=37, offs=4)
*/
/*
local: 
global: fib$0$0(level=0)
local: 
global: 
*/
ATSglobaldec()
atstkind_t0ype(atstype_int)
_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$projects_057$org_056$ats_055$lang_056$postiats_056$jats_057$test_057$fib_056$dats_fib(atstkind_t0ype(atstype_int) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret0, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmpref11, postiats_tyrec_0) ;
ATStmpdec_void(tmp12, atsvoid_t0ype) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_fib:
/*
letpush(beg)
*/
/*
ATSINStmpdec(tmpref11)) ;
*/
ATSINSstore_fltrec_ofs (tmpref11, postiats_tyrec_0, atslab$0, ATSPMVi0nt(0)) ;
ATSINSstore_fltrec_ofs (tmpref11, postiats_tyrec_0, atslab$1, ATSPMVi0nt(1)) ;
ATSINSmove_void(tmp12, loop_1(ATSPMVrefarg1(ATSPMVptrof(tmpref11)), arg0)) ;
/*
letpush(end)
*/

ATSINSmove(tmpret0, ATSSELfltrec(tmpref11, postiats_tyrec_0, atslab$0)) ;
/*
INSletpop()
*/
/* funbodyinstrlst(end) */
ATSreturn(tmpret0) ;
} /* end of [_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$projects_057$org_056$ats_055$lang_056$postiats_056$jats_057$test_057$fib_056$dats_fib] */

#if(0)
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/integer.dats: 27633(line=742, offs=14) -- 27673(line=742, offs=54)
*/
/*
local: 
global: eq_g0int_int$9$0(level=0)
local: 
global: 
*/
ATSglobaldec()
/*
imparg = tk(3150)
tmparg = S2Evar(tk(3150))
tmpsub = None()
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056$prelude_eq_g0int_int$9(atstkind_t0ype(atstyvar_type(tk)) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret20, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp21, atstkind_t0ype(atstyvar_type(tk))) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_eq_g0int_int:
ATSINSmove(tmp21, PMVtmpltcst(g0int2int<S2Eextkind(atstype_int), S2Evar(tk(3150))>)(arg1)) ;
ATSINSmove(tmpret20, PMVtmpltcst(g0int_eq<S2Evar(tk(3150))>)(arg0, tmp21)) ;
/* funbodyinstrlst(end) */
ATSreturn(tmpret20) ;
} /* end of [ATSLIB_056$prelude_eq_g0int_int$9] */
#endif // end of [TEMPLATE]

/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/integer.dats: 27633(line=742, offs=14) -- 27673(line=742, offs=54)
*/
/*
local: 
global: eq_g0int_int$9$1(level=1)
local: 
global: 
*/
ATSstaticdec()
/*
imparg = tk(3150)
tmparg = S2Evar(tk(3150))
tmpsub = Some(tk(3150) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056$prelude_eq_g0int_int$9$1(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmp20$1, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp21$1, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_eq_g0int_int:
ATSINSmove(tmp21$1, atspre_g0int2int_int_int(arg1)) ;
ATSINSmove(tmp20$1, atspre_g0int_eq_int(arg0, tmp21$1)) ;
/* funbodyinstrlst(end) */
ATSreturn(tmp20$1) ;
} /* end of [ATSLIB_056$prelude_eq_g0int_int$9$1] */

/*
/home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/fib.dats: 768(line=42, offs=6) -- 875(line=46, offs=2)
*/
/*
local: 
global: mainats_void_int$8$0(level=0)
local: 
global: 
*/
ATSglobaldec()
atstkind_t0ype(atstype_int)
mainats_void_int()
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret13, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp14, atstkind_t0ype(atstype_int)) ;
ATStmpdec_void(tmp15, atsvoid_t0ype) ;
ATStmpdec_void(tmp16, atsvoid_t0ype) ;
ATStmpdec_void(tmp17, atsvoid_t0ype) ;
ATStmpdec_void(tmp18, atsvoid_t0ype) ;
ATStmpdec(tmp19, atstkind_t0ype(atstype_bool)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_main_void_int:
/*
letpush(beg)
*/
ATSINSmove(tmp14, _057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$projects_057$org_056$ats_055$lang_056$postiats_056$jats_057$test_057$fib_056$dats_fib(ATSPMVi0nt(3))) ;
ATSINSmove_void(tmp15, atspre_print_string(ATSPMVstring("ans = "))) ;
ATSINSmove_void(tmp16, atspre_print_int(tmp14)) ;
ATSINSmove_void(tmp17, atspre_print_newline()) ;
ATSINSmove(tmp19, ATSLIB_056$prelude_eq_g0int_int$9$1(tmp14, ATSPMVi0nt(2))) ;
ATSINSmove_void(tmp18, atspre_assert_errmsg_bool0(tmp19, ATSCSTSPmyloc("/home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/fib.dats: 853(line=45, offs=12) -- 871(line=45, offs=30)"))) ;
/*
letpush(end)
*/

ATSINSmove(tmpret13, ATSPMVi0nt(0)) ;
/*
INSletpop()
*/
/* funbodyinstrlst(end) */
ATSreturn(tmpret13) ;
} /* end of [mainats_void_int] */


/*
** for initialization(dynloading)
*/
atsvoid_t0ype
_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$projects_057$org_056$ats_055$lang_056$postiats_056$jats_057$test_057$fib_056$dats__dynload()
{
ATSdynload0(
_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$projects_057$org_056$ats_055$lang_056$postiats_056$jats_057$test_057$fib_056$dats__dynloadflag
) ;
ATSif(
ATSCKiseqz(
_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$projects_057$org_056$ats_055$lang_056$postiats_056$jats_057$test_057$fib_056$dats__dynloadflag
)
) ATSthen() {
ATSdynloadset(_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$projects_057$org_056$ats_055$lang_056$postiats_056$jats_057$test_057$fib_056$dats__dynloadflag) ;
/*
dynexnlst-initize(beg)
*/
/*
dynexnlst-initize(end)
*/
} /* ATSendif */
ATSreturn_void() ;
} /* end of [*_dynload] */

/*
** the ATS runtime
*/
#ifndef _ATS_CCOMP_RUNTIME_NONE
#include "pats_ccomp_runtime.c"
#include "pats_ccomp_runtime2_dats.c"
#include "pats_ccomp_runtime_trywith.c"
#endif /* _ATS_CCOMP_RUNTIME_NONE */

/*
** the [main] implementation
*/
int
main
(
int argc, char **argv, char **envp
) {
int err = 0 ;
_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$projects_057$org_056$ats_055$lang_056$postiats_056$jats_057$test_057$fib_056$dats__dynload() ;
ATSmainats_void_int(err) ;
return (err) ;
} /* end of [main] */
