/*
**
** The C code is generated by ATS/Postiats
** The compilation time is: 2013-7-3: 16h:41m
**
*/

/*
** include runtime header files
*/
#ifndef _ATS_CCOMP_HEADER_NONE
#include "pats_ccomp_config.h"
#include "pats_ccomp_basics.h"
#include "pats_ccomp_typedefs.h"
#include "pats_ccomp_instrset.h"
#include "pats_ccomp_memalloc.h"
#include "pats_ccomp_memalloca.h"
#include "pats_ccomp_exception.h"
#endif /* _ATS_CCOMP_HEADER_NONE */


/*
** include prelude cats files
*/
#ifndef _ATS_CCOMP_PRELUDE_NONE
//
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/memory.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/strptr.cats"
//
#include "prelude/CATS/filebas.cats"
//
#include "prelude/CATS/list.cats"
#include "prelude/CATS/option.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/arrayptr.cats"
#include "prelude/CATS/arrayref.cats"
#include "prelude/CATS/matrix.cats"
#include "prelude/CATS/matrixptr.cats"
//
#endif /* _ATS_CCOMP_PRELUDE_NONE */

/*
staload-prologues(beg)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/integer.dats: 1636(line=51, offs=1) -- 1675(line=51, offs=40)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/integer.dats: 26347(line=693, offs=1) -- 26378(line=693, offs=32)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/libc/SATS/stdlib.sats: 1379(line=35, offs=1) -- 1418(line=37, offs=3)
*/

#include "libc/CATS/stdlib.cats"
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/libc/SATS/stdlib.sats: 1814(line=54, offs=1) -- 1854(line=55, offs=33)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/string.dats: 1609(line=48, offs=1) -- 1648(line=48, offs=40)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/strptr.dats: 1609(line=48, offs=1) -- 1648(line=48, offs=40)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/strptr.dats: 1671(line=52, offs=1) -- 1718(line=52, offs=48)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/integer.dats: 1636(line=51, offs=1) -- 1675(line=51, offs=40)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/integer.dats: 26347(line=693, offs=1) -- 26378(line=693, offs=32)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/libc/SATS/stdlib.sats: 1379(line=35, offs=1) -- 1418(line=37, offs=3)
*/

#include "libc/CATS/stdlib.cats"
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/libc/SATS/stdlib.sats: 1814(line=54, offs=1) -- 1854(line=55, offs=33)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/pointer.dats: 1533(line=44, offs=1) -- 1572(line=44, offs=40)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/filebas.dats: 1613(line=48, offs=1) -- 1652(line=48, offs=40)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/filebas.dats: 1675(line=52, offs=1) -- 1722(line=52, offs=48)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/integer.dats: 1636(line=51, offs=1) -- 1675(line=51, offs=40)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/integer.dats: 26347(line=693, offs=1) -- 26378(line=693, offs=32)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/libc/SATS/stdlib.sats: 1379(line=35, offs=1) -- 1418(line=37, offs=3)
*/

#include "libc/CATS/stdlib.cats"
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/libc/SATS/stdlib.sats: 1814(line=54, offs=1) -- 1854(line=55, offs=33)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/filebas.dats: 1745(line=56, offs=1) -- 1783(line=56, offs=39)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/libc/SATS/stdio.sats: 1380(line=35, offs=1) -- 1418(line=37, offs=3)
*/

#include "libc/CATS/stdio.cats"
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/libc/SATS/stdio.sats: 1855(line=57, offs=1) -- 1897(line=59, offs=27)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/libc/sys/SATS/types.sats: 1380(line=35, offs=1) -- 1422(line=37, offs=3)
*/

#include "libc/sys/CATS/types.cats"
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/list.dats: 1533(line=44, offs=1) -- 1572(line=44, offs=40)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/list.dats: 1573(line=45, offs=1) -- 1619(line=45, offs=47)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/unsafe.dats: 1532(line=44, offs=1) -- 1566(line=44, offs=35)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/list_vt.dats: 1536(line=44, offs=1) -- 1575(line=44, offs=40)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/list_vt_mergesort.dats: 1546(line=44, offs=1) -- 1585(line=44, offs=40)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/list_vt_quicksort.dats: 1546(line=44, offs=1) -- 1585(line=44, offs=40)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/array.dats: 1534(line=44, offs=1) -- 1573(line=44, offs=40)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/array.dats: 1574(line=45, offs=1) -- 1616(line=45, offs=43)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/array_bsearch.dats: 1531(line=44, offs=1) -- 1570(line=44, offs=40)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/array_quicksort.dats: 1531(line=44, offs=1) -- 1570(line=44, offs=40)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/arrayptr.dats: 1532(line=44, offs=1) -- 1571(line=44, offs=40)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/arrayref.dats: 1532(line=44, offs=1) -- 1571(line=44, offs=40)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/matrix.dats: 1535(line=44, offs=1) -- 1574(line=44, offs=40)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/matrixptr.dats: 1538(line=44, offs=1) -- 1577(line=44, offs=40)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/matrixref.dats: 1538(line=44, offs=1) -- 1577(line=44, offs=40)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/unsafe.dats: 1532(line=44, offs=1) -- 1566(line=44, offs=35)
*/
/*
staload-prologues(end)
*/
/*
typedefs-for-tyrecs-and-tysums(beg)
*/
typedef
struct {
atstkind_t0ype(atstype_int) atslab$0; 
atstkind_t0ype(atstype_int) atslab$1; 
} postiats_tyrec_0 ;
typedef
struct {
atstkind_t0ype(atstype_int) atslab$0; 
postiats_tyrec_0 atslab$1; 
} postiats_tyrec_1 ;
/*
typedefs-for-tyrecs-and-tysums(end)
*/
/*
dynconlst-declaration(beg)
*/
/*
dynconlst-declaration(end)
*/
/*
dyncstlst-declaration(beg)
*/
ATSdyncst_mac(atspre_arrayptr_make_arrpsz) ;
ATSdyncst_mac(atspre_add_ptr0_bsz) ;
ATSdyncst_mac(atspre_arrayptr_free) ;
ATSdyncst_mac(atspre_assert_errmsg_bool1) ;
/*
dyncstlst-declaration(end)
*/
/*
dynvalist-implementation(beg)
*/
/*
dynvalist-implementation(end)
*/
/*
exnconlst-declaration(beg)
*/
extern void the_atsexncon_initize (atstype_exncon *d2c, char *exnmsg) ;
/*
exnconlst-declaration(end)
*/
/*
assumelst-declaration(beg)
*/
/*
assumelst-declaration(end)
*/
ATSstaticdec()
atsvoid_t0ype
foo_0() ;

#if(0)
#if(0)
ATSglobaldec()
atstyvar_type(a)
ATSLIB_056$prelude_arrayptr_get_at_gint$1(atsrefarg0_type(atstkind_type(atstype_ptrk)), atstkind_t0ype(atstyvar_type(tk))) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstaticdec()
postiats_tyrec_0
ATSLIB_056$prelude_arrayptr_get_at_gint$1$1(atsrefarg0_type(atstkind_type(atstype_ptrk)), atstkind_t0ype(atstype_int)) ;

#if(0)
#if(0)
ATSglobaldec()
atstkind_type(atstype_ptrk)
ATSLIB_056$prelude_ptr1_add_gint$3(atstkind_type(atstype_ptrk), atstkind_t0ype(atstyvar_type(tk))) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstaticdec()
atstkind_type(atstype_ptrk)
ATSLIB_056$prelude_ptr1_add_gint$3$1(atstkind_type(atstype_ptrk), atstkind_t0ype(atstype_int)) ;

#if(0)
#if(0)
ATSglobaldec()
atstkind_type(atstype_ptrk)
ATSLIB_056$prelude_ptr0_add_gint$5(atstkind_type(atstype_ptrk), atstkind_t0ype(atstyvar_type(tk))) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstaticdec()
atstkind_type(atstype_ptrk)
ATSLIB_056$prelude_ptr0_add_gint$5$1(atstkind_type(atstype_ptrk), atstkind_t0ype(atstype_int)) ;

#if(0)
#if(0)
ATSglobaldec()
atstyvar_type(a)
ATSLIB_056$prelude_056$unsafe_ptr0_get$9(atstkind_type(atstype_ptrk)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstaticdec()
postiats_tyrec_0
ATSLIB_056$prelude_056$unsafe_ptr0_get$9$1(atstkind_type(atstype_ptrk)) ;

#if(0)
#if(0)
ATSglobaldec()
atsvoid_t0ype
ATSLIB_056$prelude_arrayptr_set_at_gint$11(atsrefarg0_type(atstkind_type(atstype_ptrk)), atstkind_t0ype(atstyvar_type(tk)), atstyvar_type(a)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstaticdec()
atsvoid_t0ype
ATSLIB_056$prelude_arrayptr_set_at_gint$11$1(atsrefarg0_type(atstkind_type(atstype_ptrk)), atstkind_t0ype(atstype_int), postiats_tyrec_0) ;

ATSstaticdec()
atstkind_type(atstype_ptrk)
ATSLIB_056$prelude_ptr1_add_gint$3$2(atstkind_type(atstype_ptrk), atstkind_t0ype(atstype_int)) ;

ATSstaticdec()
atstkind_type(atstype_ptrk)
ATSLIB_056$prelude_ptr0_add_gint$5$2(atstkind_type(atstype_ptrk), atstkind_t0ype(atstype_int)) ;

#if(0)
#if(0)
ATSglobaldec()
atsvoid_t0ype
ATSLIB_056$prelude_056$unsafe_ptr0_set$15(atstkind_type(atstype_ptrk), atstyvar_type(a)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstaticdec()
atsvoid_t0ype
ATSLIB_056$prelude_056$unsafe_ptr0_set$15$1(atstkind_type(atstype_ptrk), postiats_tyrec_0) ;

#if(0)
#if(0)
ATSglobaldec()
atstkind_t0ype(atstype_bool)
ATSLIB_056$prelude_eq_g1int_int$17(atstkind_t0ype(atstyvar_type(tk)), atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstaticdec()
atstkind_t0ype(atstype_bool)
ATSLIB_056$prelude_eq_g1int_int$17$1(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

ATSstaticdec()
atstkind_t0ype(atstype_bool)
ATSLIB_056$prelude_eq_g1int_int$17$2(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

#if(0)
ATSglobaldec()
atsvoid_t0ype
mainats_void_0() ;
#endif // end of [QUALIFIED]

/*
/home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/test19.dats: 52(line=6, offs=5) -- 366(line=24, offs=2)
*/
/*
local: 
global: foo_0$0(level=0)
local: 
global: 
*/
ATSstaticdec()
atsvoid_t0ype
foo_0()
{
/* tmpvardeclst(beg) */
ATStmpdec_void(tmpret0, atsvoid_t0ype) ;
ATStmpdec(tmp1, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp2, atstype_arrpsz) ;
ATStmpdec(tmp3, atstype_arrptr) ;
ATStmpdec(tmp4, postiats_tyrec_0) ;
ATStmpdec(tmp5, postiats_tyrec_0) ;
ATStmpdec(tmp6, postiats_tyrec_0) ;
ATStmpdec_void(tmp25, atsvoid_t0ype) ;
ATStmpdec(tmp37, postiats_tyrec_0) ;
ATStmpdec_void(tmp38, atsvoid_t0ype) ;
ATStmpdec(tmpref39, postiats_tyrec_1) ;
ATStmpdec(tmp40, postiats_tyrec_0) ;
ATStmpdec_void(tmp41, atsvoid_t0ype) ;
ATStmpdec(tmp42, atstkind_t0ype(atstype_bool)) ;
ATStmpdec_void(tmp47, atsvoid_t0ype) ;
ATStmpdec(tmp48, atstkind_t0ype(atstype_bool)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_foo_0:
/*
letpush(beg)
*/
/*
ATSINStmpdec(tmp2)) ;
*/
ATSINSstore_arrpsz_asz(tmp2, 2) ;
ATSINSstore_arrpsz_ptr(tmp2, postiats_tyrec_0, 2) ;
ATSINSmove_arrpsz_ptr(tmp3, tmp2) ;
ATSINSstore_fltrec_ofs (tmp4, postiats_tyrec_0, atslab$0, ATSPMVi0nt(1)) ;
ATSINSstore_fltrec_ofs (tmp4, postiats_tyrec_0, atslab$1, ATSPMVi0nt(1)) ;
ATSINSpmove(tmp3, postiats_tyrec_0, tmp4) ;
ATSINSupdate_ptrinc(tmp3, postiats_tyrec_0) ;
ATSINSstore_fltrec_ofs (tmp5, postiats_tyrec_0, atslab$0, ATSPMVi0nt(2)) ;
ATSINSstore_fltrec_ofs (tmp5, postiats_tyrec_0, atslab$1, ATSPMVi0nt(2)) ;
ATSINSpmove(tmp3, postiats_tyrec_0, tmp5) ;
ATSINSmove(tmp1, atspre_arrayptr_make_arrpsz(tmp2)) ;
ATSINSmove(tmp6, ATSLIB_056$prelude_arrayptr_get_at_gint$1$1(ATSPMVrefarg0(tmp1), ATSPMVi0nt(0))) ;
ATSINSstore_fltrec_ofs (tmp37, postiats_tyrec_0, atslab$0, ATSPMVi0nt(3)) ;
ATSINSstore_fltrec_ofs (tmp37, postiats_tyrec_0, atslab$1, ATSPMVi0nt(3)) ;
ATSINSmove_void(tmp25, ATSLIB_056$prelude_arrayptr_set_at_gint$11$1(ATSPMVrefarg0(tmp1), ATSPMVi0nt(0), tmp37)) ;
ATSINSmove_void(tmp38, atspre_arrayptr_free(tmp1)) ;
/*
ATSINStmpdec(tmpref39)) ;
*/
ATSINSstore_fltrec_ofs (tmp40, postiats_tyrec_0, atslab$0, ATSPMVi0nt(2)) ;
ATSINSstore_fltrec_ofs (tmp40, postiats_tyrec_0, atslab$1, ATSPMVi0nt(3)) ;
ATSINSstore_fltrec_ofs (tmpref39, postiats_tyrec_1, atslab$0, ATSPMVi0nt(1)) ;
ATSINSstore_fltrec_ofs (tmpref39, postiats_tyrec_1, atslab$1, tmp40) ;
ATSINSstore(ATSSELfltrec(tmpref39, postiats_tyrec_1, atslab$0), ATSPMVi0nt(3)) ;
ATSINSstore(ATSSELfltrec(ATSSELfltrec(tmpref39, postiats_tyrec_1, atslab$1), postiats_tyrec_0, atslab$0), ATSPMVi0nt(4)) ;
ATSINSmove(tmp42, ATSLIB_056$prelude_eq_g1int_int$17$1(ATSSELfltrec(tmpref39, postiats_tyrec_1, atslab$0), ATSPMVi0nt(3))) ;
ATSINSmove_void(tmp41, atspre_assert_errmsg_bool1(tmp42, ATSCSTSPmyloc("/home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/test19.dats: 309(line=19, offs=10) -- 328(line=19, offs=29)"))) ;
ATSINSmove(tmp48, ATSLIB_056$prelude_eq_g1int_int$17$2(ATSSELfltrec(ATSSELfltrec(tmpref39, postiats_tyrec_1, atslab$1), postiats_tyrec_0, atslab$0), ATSPMVi0nt(4))) ;
ATSINSmove_void(tmp47, atspre_assert_errmsg_bool1(tmp48, ATSCSTSPmyloc("/home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/test19.dats: 339(line=20, offs=10) -- 360(line=20, offs=31)"))) ;
/*
letpush(end)
*/

ATSINSmove_void(tmpret0, ATSempty()) ;
/*
INSletpop()
*/
/* funbodyinstrlst(end) */
ATSreturn_void(tmpret0) ;
} /* end of [foo_0] */

#if(0)
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/arrayptr.dats: 4215(line=194, offs=3) -- 4304(line=197, offs=4)
*/
/*
local: 
global: arrayptr_get_at_gint$1$0(level=0)
local: 
global: 
*/
ATSglobaldec()
/*
imparg = a(5169), tk(5170)
tmparg = S2Evar(a(5169)); S2Evar(tk(5170))
tmpsub = None()
*/
atstyvar_type(a)
ATSLIB_056$prelude_arrayptr_get_at_gint$1(atsrefarg0_type(atstkind_type(atstype_ptrk)) arg0, atstkind_t0ype(atstyvar_type(tk)) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret7, atstyvar_type(a)) ;
ATStmpdec(tmp8, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_arrayptr_get_at_gint:
/*
letpush(beg)
*/
/* (*nothing*) */
/*
letpush(end)
*/

ATSINSmove(tmp8, PMVtmpltcst(ptr1_add_gint<S2Evar(a(5169))><S2Evar(tk(5170))>)(ATSPMVcastfn(arrayptr2ptr, atstkind_type(atstype_ptrk), ATSPMVrefarg0(arg0)), arg1)) ;
ATSINSmove(tmpret7, PMVtmpltcst(ptr0_get<S2Evar(a(5169))>)(tmp8)) ;
/*
INSletpop()
*/
/* funbodyinstrlst(end) */
ATSreturn(tmpret7) ;
} /* end of [ATSLIB_056$prelude_arrayptr_get_at_gint$1] */
#endif // end of [TEMPLATE]

/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/arrayptr.dats: 4215(line=194, offs=3) -- 4304(line=197, offs=4)
*/
/*
local: 
global: arrayptr_get_at_gint$1$1(level=1)
local: 
global: 
*/
ATSstaticdec()
/*
imparg = a(5169), tk(5170)
tmparg = S2Evar(a(5169)); S2Evar(tk(5170))
tmpsub = Some(a(5169) -> S2Etyrec(flt0; npf=-1; 0=S2Ecst(int), 1=S2Ecst(int)); tk(5170) -> S2Eextkind(atstype_int))
*/
postiats_tyrec_0
ATSLIB_056$prelude_arrayptr_get_at_gint$1$1(atsrefarg0_type(atstkind_type(atstype_ptrk)) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmp7$1, postiats_tyrec_0) ;
ATStmpdec(tmp8$1, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_arrayptr_get_at_gint:
/*
letpush(beg)
*/
/* (*nothing*) */
/*
letpush(end)
*/

ATSINSmove(tmp8$1, ATSLIB_056$prelude_ptr1_add_gint$3$1(ATSPMVcastfn(arrayptr2ptr, atstkind_type(atstype_ptrk), ATSPMVrefarg0(arg0)), arg1)) ;
ATSINSmove(tmp7$1, ATSLIB_056$prelude_056$unsafe_ptr0_get$9$1(tmp8$1)) ;
/*
INSletpop()
*/
/* funbodyinstrlst(end) */
ATSreturn(tmp7$1) ;
} /* end of [ATSLIB_056$prelude_arrayptr_get_at_gint$1$1] */

#if(0)
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/pointer.dats: 2518(line=93, offs=22) -- 2585(line=94, offs=59)
*/
/*
local: 
global: ptr1_add_gint$3$0(level=0)
local: 
global: 
*/
ATSglobaldec()
/*
imparg = a(3476), tk(3477)
tmparg = S2Evar(a(3476)); S2Evar(tk(3477))
tmpsub = None()
*/
atstkind_type(atstype_ptrk)
ATSLIB_056$prelude_ptr1_add_gint$3(atstkind_type(atstype_ptrk) arg0, atstkind_t0ype(atstyvar_type(tk)) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret11, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp12, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_ptr1_add_gint:
ATSINSmove(tmp12, PMVtmpltcst(ptr0_add_gint<S2Evar(a(3476))><S2Evar(tk(3477))>)(arg0, arg1)) ;
ATSINSmove(tmpret11, ATSPMVcastfn(cast, atstkind_type(atstype_ptrk), tmp12)) ;
/* funbodyinstrlst(end) */
ATSreturn(tmpret11) ;
} /* end of [ATSLIB_056$prelude_ptr1_add_gint$3] */
#endif // end of [TEMPLATE]

/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/pointer.dats: 2518(line=93, offs=22) -- 2585(line=94, offs=59)
*/
/*
local: 
global: ptr1_add_gint$3$1(level=2)
local: 
global: 
*/
ATSstaticdec()
/*
imparg = a(3476), tk(3477)
tmparg = S2Evar(a(3476)); S2Evar(tk(3477))
tmpsub = Some(a(3476) -> S2Etyrec(flt0; npf=-1; 0=S2Ecst(int), 1=S2Ecst(int)); tk(3477) -> S2Eextkind(atstype_int))
*/
atstkind_type(atstype_ptrk)
ATSLIB_056$prelude_ptr1_add_gint$3$1(atstkind_type(atstype_ptrk) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmp11$1, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp12$1, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_ptr1_add_gint:
ATSINSmove(tmp12$1, ATSLIB_056$prelude_ptr0_add_gint$5$1(arg0, arg1)) ;
ATSINSmove(tmp11$1, ATSPMVcastfn(cast, atstkind_type(atstype_ptrk), tmp12$1)) ;
/* funbodyinstrlst(end) */
ATSreturn(tmp11$1) ;
} /* end of [ATSLIB_056$prelude_ptr1_add_gint$3$1] */

#if(0)
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/pointer.dats: 1952(line=68, offs=15) -- 2005(line=69, offs=45)
*/
/*
local: 
global: ptr0_add_gint$5$0(level=0)
local: 
global: 
*/
ATSglobaldec()
/*
imparg = a(3462), tk(3463)
tmparg = S2Evar(a(3462)); S2Evar(tk(3463))
tmpsub = None()
*/
atstkind_type(atstype_ptrk)
ATSLIB_056$prelude_ptr0_add_gint$5(atstkind_type(atstype_ptrk) arg0, atstkind_t0ype(atstyvar_type(tk)) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret15, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp16, atstkind_t0ype(atstype_size)) ;
ATStmpdec(tmp17, atstkind_t0ype(atstype_size)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_ptr0_add_gint:
ATSINSmove(tmp17, PMVtmpltcst(g0int2uint<S2Evar(tk(3463)), S2Eextkind(atstype_size)>)(arg1)) ;
ATSINSmove(tmp16, PMVtmpltcst(g0uint_mul<S2Eextkind(atstype_size)>)(tmp17, ATSPMVsizeof(atstyvar_type(a)))) ;
ATSINSmove(tmpret15, atspre_add_ptr0_bsz(arg0, tmp16)) ;
/* funbodyinstrlst(end) */
ATSreturn(tmpret15) ;
} /* end of [ATSLIB_056$prelude_ptr0_add_gint$5] */
#endif // end of [TEMPLATE]

/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/pointer.dats: 1952(line=68, offs=15) -- 2005(line=69, offs=45)
*/
/*
local: 
global: ptr0_add_gint$5$1(level=3)
local: 
global: 
*/
ATSstaticdec()
/*
imparg = a(3462), tk(3463)
tmparg = S2Evar(a(3462)); S2Evar(tk(3463))
tmpsub = Some(a(3462) -> S2Etyrec(flt0; npf=-1; 0=S2Ecst(int), 1=S2Ecst(int)); tk(3463) -> S2Eextkind(atstype_int))
*/
atstkind_type(atstype_ptrk)
ATSLIB_056$prelude_ptr0_add_gint$5$1(atstkind_type(atstype_ptrk) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmp15$1, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp16$1, atstkind_t0ype(atstype_size)) ;
ATStmpdec(tmp17$1, atstkind_t0ype(atstype_size)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_ptr0_add_gint:
ATSINSmove(tmp17$1, atspre_g0int2uint_int_size(arg1)) ;
ATSINSmove(tmp16$1, atspre_g0uint_mul_size(tmp17$1, ATSPMVsizeof(postiats_tyrec_0))) ;
ATSINSmove(tmp15$1, atspre_add_ptr0_bsz(arg0, tmp16$1)) ;
/* funbodyinstrlst(end) */
ATSreturn(tmp15$1) ;
} /* end of [ATSLIB_056$prelude_ptr0_add_gint$5$1] */

#if(0)
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/unsafe.dats: 1621(line=51, offs=3) -- 1834(line=59, offs=2)
*/
/*
local: 
global: ptr0_get$9$0(level=0)
local: 
global: 
*/
ATSglobaldec()
/*
imparg = a(3723)
tmparg = S2Evar(a(3723))
tmpsub = None()
*/
atstyvar_type(a)
ATSLIB_056$prelude_056$unsafe_ptr0_get$9(atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret21, atstyvar_type(a)) ;
ATStmpdec(tmp22, atstyvar_type(a)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_ptr0_get:
/*
letpush(beg)
*/
/* (*nothing*) */
/* (*nothing*) */
ATSINSmove(tmp22, ATSderef(ATSPMVcastfn(g1ofg0_ptr, atstkind_type(atstype_ptrk), arg0), atstyvar_type(a))) ;
/* (*nothing*) */
/*
letpush(end)
*/

ATSINSmove(tmpret21, tmp22) ;
/*
INSletpop()
*/
/* funbodyinstrlst(end) */
ATSreturn(tmpret21) ;
} /* end of [ATSLIB_056$prelude_056$unsafe_ptr0_get$9] */
#endif // end of [TEMPLATE]

/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/unsafe.dats: 1621(line=51, offs=3) -- 1834(line=59, offs=2)
*/
/*
local: 
global: ptr0_get$9$1(level=2)
local: 
global: 
*/
ATSstaticdec()
/*
imparg = a(3723)
tmparg = S2Evar(a(3723))
tmpsub = Some(a(3723) -> S2Etyrec(flt0; npf=-1; 0=S2Ecst(int), 1=S2Ecst(int)))
*/
postiats_tyrec_0
ATSLIB_056$prelude_056$unsafe_ptr0_get$9$1(atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmp21$1, postiats_tyrec_0) ;
ATStmpdec(tmp22$1, postiats_tyrec_0) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_ptr0_get:
/*
letpush(beg)
*/
/* (*nothing*) */
/* (*nothing*) */
ATSINSmove(tmp22$1, ATSderef(ATSPMVcastfn(g1ofg0_ptr, atstkind_type(atstype_ptrk), arg0), postiats_tyrec_0)) ;
/* (*nothing*) */
/*
letpush(end)
*/

ATSINSmove(tmp21$1, tmp22$1) ;
/*
INSletpop()
*/
/* funbodyinstrlst(end) */
ATSreturn(tmp21$1) ;
} /* end of [ATSLIB_056$prelude_056$unsafe_ptr0_get$9$1] */

#if(0)
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/arrayptr.dats: 4567(line=210, offs=3) -- 4662(line=213, offs=4)
*/
/*
local: 
global: arrayptr_set_at_gint$11$0(level=0)
local: 
global: 
*/
ATSglobaldec()
/*
imparg = a(5179), tk(5180)
tmparg = S2Evar(a(5179)); S2Evar(tk(5180))
tmpsub = None()
*/
atsvoid_t0ype
ATSLIB_056$prelude_arrayptr_set_at_gint$11(atsrefarg0_type(atstkind_type(atstype_ptrk)) arg0, atstkind_t0ype(atstyvar_type(tk)) arg1, atstyvar_type(a) arg2)
{
/* tmpvardeclst(beg) */
ATStmpdec_void(tmpret26, atsvoid_t0ype) ;
ATStmpdec(tmp27, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_arrayptr_set_at_gint:
/*
letpush(beg)
*/
/* (*nothing*) */
/*
letpush(end)
*/

ATSINSmove(tmp27, PMVtmpltcst(ptr1_add_gint<S2Evar(a(5179))><S2Evar(tk(5180))>)(ATSPMVcastfn(arrayptr2ptr, atstkind_type(atstype_ptrk), ATSPMVrefarg0(arg0)), arg1)) ;
ATSINSmove_void(tmpret26, PMVtmpltcst(ptr0_set<S2Evar(a(5179))>)(tmp27, arg2)) ;
/*
INSletpop()
*/
/* funbodyinstrlst(end) */
ATSreturn_void(tmpret26) ;
} /* end of [ATSLIB_056$prelude_arrayptr_set_at_gint$11] */
#endif // end of [TEMPLATE]

/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/arrayptr.dats: 4567(line=210, offs=3) -- 4662(line=213, offs=4)
*/
/*
local: 
global: arrayptr_set_at_gint$11$1(level=1)
local: 
global: 
*/
ATSstaticdec()
/*
imparg = a(5179), tk(5180)
tmparg = S2Evar(a(5179)); S2Evar(tk(5180))
tmpsub = Some(a(5179) -> S2Etyrec(flt0; npf=-1; 0=S2Ecst(int), 1=S2Ecst(int)); tk(5180) -> S2Eextkind(atstype_int))
*/
atsvoid_t0ype
ATSLIB_056$prelude_arrayptr_set_at_gint$11$1(atsrefarg0_type(atstkind_type(atstype_ptrk)) arg0, atstkind_t0ype(atstype_int) arg1, postiats_tyrec_0 arg2)
{
/* tmpvardeclst(beg) */
ATStmpdec_void(tmp26$1, atsvoid_t0ype) ;
ATStmpdec(tmp27$1, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_arrayptr_set_at_gint:
/*
letpush(beg)
*/
/* (*nothing*) */
/*
letpush(end)
*/

ATSINSmove(tmp27$1, ATSLIB_056$prelude_ptr1_add_gint$3$2(ATSPMVcastfn(arrayptr2ptr, atstkind_type(atstype_ptrk), ATSPMVrefarg0(arg0)), arg1)) ;
ATSINSmove_void(tmp26$1, ATSLIB_056$prelude_056$unsafe_ptr0_set$15$1(tmp27$1, arg2)) ;
/*
INSletpop()
*/
/* funbodyinstrlst(end) */
ATSreturn_void(tmp26$1) ;
} /* end of [ATSLIB_056$prelude_arrayptr_set_at_gint$11$1] */

/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/pointer.dats: 2518(line=93, offs=22) -- 2585(line=94, offs=59)
*/
/*
local: 
global: ptr1_add_gint$3$2(level=2)
local: 
global: 
*/
ATSstaticdec()
/*
imparg = a(3476), tk(3477)
tmparg = S2Evar(a(3476)); S2Evar(tk(3477))
tmpsub = Some(a(3476) -> S2Etyrec(flt0; npf=-1; 0=S2Ecst(int), 1=S2Ecst(int)); tk(3477) -> S2Eextkind(atstype_int))
*/
atstkind_type(atstype_ptrk)
ATSLIB_056$prelude_ptr1_add_gint$3$2(atstkind_type(atstype_ptrk) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmp11$2, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp12$2, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_ptr1_add_gint:
ATSINSmove(tmp12$2, ATSLIB_056$prelude_ptr0_add_gint$5$2(arg0, arg1)) ;
ATSINSmove(tmp11$2, ATSPMVcastfn(cast, atstkind_type(atstype_ptrk), tmp12$2)) ;
/* funbodyinstrlst(end) */
ATSreturn(tmp11$2) ;
} /* end of [ATSLIB_056$prelude_ptr1_add_gint$3$2] */

/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/pointer.dats: 1952(line=68, offs=15) -- 2005(line=69, offs=45)
*/
/*
local: 
global: ptr0_add_gint$5$2(level=3)
local: 
global: 
*/
ATSstaticdec()
/*
imparg = a(3462), tk(3463)
tmparg = S2Evar(a(3462)); S2Evar(tk(3463))
tmpsub = Some(a(3462) -> S2Etyrec(flt0; npf=-1; 0=S2Ecst(int), 1=S2Ecst(int)); tk(3463) -> S2Eextkind(atstype_int))
*/
atstkind_type(atstype_ptrk)
ATSLIB_056$prelude_ptr0_add_gint$5$2(atstkind_type(atstype_ptrk) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmp15$2, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp16$2, atstkind_t0ype(atstype_size)) ;
ATStmpdec(tmp17$2, atstkind_t0ype(atstype_size)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_ptr0_add_gint:
ATSINSmove(tmp17$2, atspre_g0int2uint_int_size(arg1)) ;
ATSINSmove(tmp16$2, atspre_g0uint_mul_size(tmp17$2, ATSPMVsizeof(postiats_tyrec_0))) ;
ATSINSmove(tmp15$2, atspre_add_ptr0_bsz(arg0, tmp16$2)) ;
/* funbodyinstrlst(end) */
ATSreturn(tmp15$2) ;
} /* end of [ATSLIB_056$prelude_ptr0_add_gint$5$2] */

#if(0)
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/unsafe.dats: 1947(line=68, offs=3) -- 2170(line=76, offs=2)
*/
/*
local: 
global: ptr0_set$15$0(level=0)
local: 
global: 
*/
ATSglobaldec()
/*
imparg = a(3726)
tmparg = S2Evar(a(3726))
tmpsub = None()
*/
atsvoid_t0ype
ATSLIB_056$prelude_056$unsafe_ptr0_set$15(atstkind_type(atstype_ptrk) arg0, atstyvar_type(a) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec_void(tmpret35, atsvoid_t0ype) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_ptr0_set:
/*
letpush(beg)
*/
/* (*nothing*) */
/* (*nothing*) */
ATSINSstore(ATSderef(ATSPMVcastfn(g1ofg0_ptr, atstkind_type(atstype_ptrk), arg0), atstyvar_type(a)), arg1) ;
/* (*nothing*) */
/*
letpush(end)
*/

ATSINSmove_void(tmpret35, ATSempty()) ;
/*
INSletpop()
*/
/* funbodyinstrlst(end) */
ATSreturn_void(tmpret35) ;
} /* end of [ATSLIB_056$prelude_056$unsafe_ptr0_set$15] */
#endif // end of [TEMPLATE]

/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/unsafe.dats: 1947(line=68, offs=3) -- 2170(line=76, offs=2)
*/
/*
local: 
global: ptr0_set$15$1(level=2)
local: 
global: 
*/
ATSstaticdec()
/*
imparg = a(3726)
tmparg = S2Evar(a(3726))
tmpsub = Some(a(3726) -> S2Etyrec(flt0; npf=-1; 0=S2Ecst(int), 1=S2Ecst(int)))
*/
atsvoid_t0ype
ATSLIB_056$prelude_056$unsafe_ptr0_set$15$1(atstkind_type(atstype_ptrk) arg0, postiats_tyrec_0 arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec_void(tmp35$1, atsvoid_t0ype) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_ptr0_set:
/*
letpush(beg)
*/
/* (*nothing*) */
/* (*nothing*) */
ATSINSstore(ATSderef(ATSPMVcastfn(g1ofg0_ptr, atstkind_type(atstype_ptrk), arg0), postiats_tyrec_0), arg1) ;
/* (*nothing*) */
/*
letpush(end)
*/

ATSINSmove_void(tmp35$1, ATSempty()) ;
/*
INSletpop()
*/
/* funbodyinstrlst(end) */
ATSreturn_void(tmp35$1) ;
} /* end of [ATSLIB_056$prelude_056$unsafe_ptr0_set$15$1] */

#if(0)
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/integer.dats: 28148(line=760, offs=14) -- 28188(line=760, offs=54)
*/
/*
local: 
global: eq_g1int_int$17$0(level=0)
local: 
global: 
*/
ATSglobaldec()
/*
imparg = tk(3209)
tmparg = S2Evar(tk(3209))
tmpsub = None()
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056$prelude_eq_g1int_int$17(atstkind_t0ype(atstyvar_type(tk)) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret43, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp44, atstkind_t0ype(atstyvar_type(tk))) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_eq_g1int_int:
ATSINSmove(tmp44, PMVtmpltcst(g1int2int<S2Eextkind(atstype_int), S2Evar(tk(3209))>)(arg1)) ;
ATSINSmove(tmpret43, PMVtmpltcst(g1int_eq<S2Evar(tk(3209))>)(arg0, tmp44)) ;
/* funbodyinstrlst(end) */
ATSreturn(tmpret43) ;
} /* end of [ATSLIB_056$prelude_eq_g1int_int$17] */
#endif // end of [TEMPLATE]

/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/integer.dats: 28148(line=760, offs=14) -- 28188(line=760, offs=54)
*/
/*
local: 
global: eq_g1int_int$17$1(level=1)
local: 
global: 
*/
ATSstaticdec()
/*
imparg = tk(3209)
tmparg = S2Evar(tk(3209))
tmpsub = Some(tk(3209) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056$prelude_eq_g1int_int$17$1(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmp43$1, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp44$1, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_eq_g1int_int:
ATSINSmove(tmp44$1, atspre_g1int2int_int_int(arg1)) ;
ATSINSmove(tmp43$1, atspre_g1int_eq_int(arg0, tmp44$1)) ;
/* funbodyinstrlst(end) */
ATSreturn(tmp43$1) ;
} /* end of [ATSLIB_056$prelude_eq_g1int_int$17$1] */

/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/integer.dats: 28148(line=760, offs=14) -- 28188(line=760, offs=54)
*/
/*
local: 
global: eq_g1int_int$17$2(level=1)
local: 
global: 
*/
ATSstaticdec()
/*
imparg = tk(3209)
tmparg = S2Evar(tk(3209))
tmpsub = Some(tk(3209) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056$prelude_eq_g1int_int$17$2(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmp43$2, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp44$2, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_eq_g1int_int:
ATSINSmove(tmp44$2, atspre_g1int2int_int_int(arg1)) ;
ATSINSmove(tmp43$2, atspre_g1int_eq_int(arg0, tmp44$2)) ;
/* funbodyinstrlst(end) */
ATSreturn(tmp43$2) ;
} /* end of [ATSLIB_056$prelude_eq_g1int_int$17$2] */

/*
/home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/test19.dats: 400(line=26, offs=17) -- 411(line=26, offs=28)
*/
/*
local: foo_0$0(level=0)
global: foo_0$0(level=0), mainats_void_0$22$0(level=0)
local: 
global: 
*/
ATSglobaldec()
atsvoid_t0ype
mainats_void_0()
{
/* tmpvardeclst(beg) */
ATStmpdec_void(tmpret51, atsvoid_t0ype) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_main_void_0:
ATSINSmove_void(tmpret51, foo_0()) ;
/* funbodyinstrlst(end) */
ATSreturn_void(tmpret51) ;
} /* end of [mainats_void_0] */


/*
** for initialization(dynloading)
*/
atsvoid_t0ype
_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$projects_057$org_056$ats_055$lang_056$postiats_056$jats_057$test_057$test19_056$dats__dynload()
{
ATSdynload0(
_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$projects_057$org_056$ats_055$lang_056$postiats_056$jats_057$test_057$test19_056$dats__dynloadflag
) ;
ATSif(
ATSCKiseqz(
_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$projects_057$org_056$ats_055$lang_056$postiats_056$jats_057$test_057$test19_056$dats__dynloadflag
)
) ATSthen() {
ATSdynloadset(_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$projects_057$org_056$ats_055$lang_056$postiats_056$jats_057$test_057$test19_056$dats__dynloadflag) ;
/*
dynexnlst-initize(beg)
*/
/*
dynexnlst-initize(end)
*/
} /* ATSendif */
ATSreturn_void() ;
} /* end of [*_dynload] */

/*
** the ATS runtime
*/
#ifndef _ATS_CCOMP_RUNTIME_NONE
#include "pats_ccomp_runtime.c"
#include "pats_ccomp_runtime2_dats.c"
#include "pats_ccomp_runtime_trywith.c"
#endif /* _ATS_CCOMP_RUNTIME_NONE */

/*
** the [main] implementation
*/
int
main
(
int argc, char **argv, char **envp
) {
int err = 0 ;
_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$projects_057$org_056$ats_055$lang_056$postiats_056$jats_057$test_057$test19_056$dats__dynload() ;
ATSmainats_void_0(err) ;
return (err) ;
} /* end of [main] */
