/*
**
** The C code is generated by ATS/Postiats
** The compilation time is: 2013-6-27: 19h:56m
**
*/

/*
** include runtime header files
*/
#ifndef _ATS_CCOMP_HEADER_NONE
#include "pats_ccomp_config.h"
#include "pats_ccomp_basics.h"
#include "pats_ccomp_typedefs.h"
#include "pats_ccomp_instrset.h"
#include "pats_ccomp_exception.h"
#include "pats_ccomp_memalloc.h"
#include "pats_ccomp_memalloca.h"
#endif /* _ATS_CCOMP_HEADER_NONE */


/*
** include prelude cats files
*/
#ifndef _ATS_CCOMP_PRELUDE_NONE
//
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/memory.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/strptr.cats"
//
#include "prelude/CATS/filebas.cats"
//
#include "prelude/CATS/list.cats"
#include "prelude/CATS/option.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/arrayptr.cats"
#include "prelude/CATS/arrayref.cats"
#include "prelude/CATS/matrix.cats"
#include "prelude/CATS/matrixptr.cats"
//
#endif /* _ATS_CCOMP_PRELUDE_NONE */

/*
staload-prologues(beg)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/integer.dats: 25237(line=637, offs=1) -- 25268(line=637, offs=32)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/libc/SATS/stdlib.sats: 1379(line=35, offs=1) -- 1418(line=37, offs=3)
*/

#include "libc/CATS/stdlib.cats"
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/libc/SATS/stdlib.sats: 1814(line=54, offs=1) -- 1854(line=55, offs=33)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/string.dats: 1532(line=44, offs=1) -- 1571(line=44, offs=40)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/strptr.dats: 1532(line=44, offs=1) -- 1571(line=44, offs=40)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/pointer.dats: 1533(line=44, offs=1) -- 1572(line=44, offs=40)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/filebas.dats: 1536(line=44, offs=1) -- 1575(line=44, offs=40)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/filebas.dats: 1598(line=48, offs=1) -- 1636(line=48, offs=39)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/libc/SATS/stdio.sats: 1380(line=35, offs=1) -- 1418(line=37, offs=3)
*/

#include "libc/CATS/stdio.cats"
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/array.dats: 1534(line=44, offs=1) -- 1573(line=44, offs=40)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/array.dats: 1574(line=45, offs=1) -- 1616(line=45, offs=43)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/array_bsearch.dats: 1531(line=44, offs=1) -- 1570(line=44, offs=40)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/array_quicksort.dats: 1531(line=44, offs=1) -- 1570(line=44, offs=40)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/arrayptr.dats: 1532(line=44, offs=1) -- 1571(line=44, offs=40)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/arrayref.dats: 1532(line=44, offs=1) -- 1571(line=44, offs=40)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/matrix.dats: 1535(line=44, offs=1) -- 1574(line=44, offs=40)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/matrixptr.dats: 1538(line=44, offs=1) -- 1577(line=44, offs=40)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/matrixref.dats: 1538(line=44, offs=1) -- 1577(line=44, offs=40)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/unsafe.dats: 1532(line=44, offs=1) -- 1566(line=44, offs=35)
*/
/*
staload-prologues(end)
*/
/*
typedefs-for-tyrecs-and-tysums(beg)
*/
typedef
struct {
atstkind_t0ype(atstype_int) atslab$0; 
atstkind_t0ype(atstype_int) atslab$1; 
} postiats_tyrec_0 ;
typedef
struct {
atstkind_t0ype(atstype_int) atslab$0; 
postiats_tyrec_0 atslab$1; 
} postiats_tyrec_1 ;
/*
typedefs-for-tyrecs-and-tysums(end)
*/
/*
dyncstlst-declaration(beg)
*/
ATSdyncst_mac(atspre_arrayptr_make_arrpsz) ;
ATSdyncst_mac(atspre_ptr0_add_bytesize) ;
ATSdyncst_mac(atspre_arrayptr_free) ;
ATSdyncst_mac(atspre_assert_errmsg_bool1) ;
/*
dyncstlst-declaration(end)
*/
ATSstaticdec()
atsvoid_t0ype
foo_0() ;

#if(0)
#if(0)
ATSglobaldec()
atstyvar_type(a)
_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$ATS_055$Postiats_057$prelude_057$SATS_057$arrayptr_056$sats_arrayptr_get_at_gint$1(atsrefarg0_type(atstkind_type(atstype_ptrk)), atstkind_t0ype(atstyvar_type(tk))) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstaticdec()
postiats_tyrec_0
_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$ATS_055$Postiats_057$prelude_057$SATS_057$arrayptr_056$sats_arrayptr_get_at_gint$1$1(atsrefarg0_type(atstkind_type(atstype_ptrk)), atstkind_t0ype(atstype_int)) ;

#if(0)
#if(0)
ATSglobaldec()
atstkind_type(atstype_ptrk)
_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$ATS_055$Postiats_057$prelude_057$SATS_057$pointer_056$sats_ptr1_add_gint$3(atstkind_type(atstype_ptrk), atstkind_t0ype(atstyvar_type(tk))) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstaticdec()
atstkind_type(atstype_ptrk)
_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$ATS_055$Postiats_057$prelude_057$SATS_057$pointer_056$sats_ptr1_add_gint$3$1(atstkind_type(atstype_ptrk), atstkind_t0ype(atstype_int)) ;

#if(0)
#if(0)
ATSglobaldec()
atstkind_type(atstype_ptrk)
_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$ATS_055$Postiats_057$prelude_057$SATS_057$pointer_056$sats_ptr0_add_gint$5(atstkind_type(atstype_ptrk), atstkind_t0ype(atstyvar_type(tk))) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstaticdec()
atstkind_type(atstype_ptrk)
_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$ATS_055$Postiats_057$prelude_057$SATS_057$pointer_056$sats_ptr0_add_gint$5$1(atstkind_type(atstype_ptrk), atstkind_t0ype(atstype_int)) ;

#if(0)
#if(0)
ATSglobaldec()
atstyvar_type(a)
_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$ATS_055$Postiats_057$prelude_057$SATS_057$unsafe_056$sats_ptr0_get$9(atstkind_type(atstype_ptrk)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstaticdec()
postiats_tyrec_0
_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$ATS_055$Postiats_057$prelude_057$SATS_057$unsafe_056$sats_ptr0_get$9$1(atstkind_type(atstype_ptrk)) ;

#if(0)
#if(0)
ATSglobaldec()
atsvoid_t0ype
_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$ATS_055$Postiats_057$prelude_057$SATS_057$arrayptr_056$sats_arrayptr_set_at_gint$11(atsrefarg0_type(atstkind_type(atstype_ptrk)), atstkind_t0ype(atstyvar_type(tk)), atstyvar_type(a)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstaticdec()
atsvoid_t0ype
_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$ATS_055$Postiats_057$prelude_057$SATS_057$arrayptr_056$sats_arrayptr_set_at_gint$11$1(atsrefarg0_type(atstkind_type(atstype_ptrk)), atstkind_t0ype(atstype_int), postiats_tyrec_0) ;

ATSstaticdec()
atstkind_type(atstype_ptrk)
_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$ATS_055$Postiats_057$prelude_057$SATS_057$pointer_056$sats_ptr1_add_gint$3$2(atstkind_type(atstype_ptrk), atstkind_t0ype(atstype_int)) ;

ATSstaticdec()
atstkind_type(atstype_ptrk)
_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$ATS_055$Postiats_057$prelude_057$SATS_057$pointer_056$sats_ptr0_add_gint$5$2(atstkind_type(atstype_ptrk), atstkind_t0ype(atstype_int)) ;

#if(0)
#if(0)
ATSglobaldec()
atsvoid_t0ype
_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$ATS_055$Postiats_057$prelude_057$SATS_057$unsafe_056$sats_ptr0_set$15(atstkind_type(atstype_ptrk), atstyvar_type(a)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstaticdec()
atsvoid_t0ype
_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$ATS_055$Postiats_057$prelude_057$SATS_057$unsafe_056$sats_ptr0_set$15$1(atstkind_type(atstype_ptrk), postiats_tyrec_0) ;

#if(0)
#if(0)
ATSglobaldec()
atstkind_t0ype(atstype_bool)
_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$ATS_055$Postiats_057$prelude_057$SATS_057$integer_056$sats_eq_g1int_int$17(atstkind_t0ype(atstyvar_type(tk)), atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstaticdec()
atstkind_t0ype(atstype_bool)
_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$ATS_055$Postiats_057$prelude_057$SATS_057$integer_056$sats_eq_g1int_int$17$1(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

ATSstaticdec()
atstkind_t0ype(atstype_bool)
_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$ATS_055$Postiats_057$prelude_057$SATS_057$integer_056$sats_eq_g1int_int$17$2(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

#if(0)
ATSglobaldec()
atsvoid_t0ype
mainats_void_0() ;
#endif // end of [QUALIFIED]

/*
/home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/test19.dats: 52(line=6, offs=5) -- 366(line=24, offs=2)
*/
/*
local: 
global: foo_0$0(0)
local: 
global: 
*/
ATSstaticdec()
atsvoid_t0ype
foo_0()
{
/* tmpvardeclst(beg) */
ATStmpdec_void(tmpret0, atsvoid_t0ype) ;
ATStmpdec(tmp1, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp2, atstype_arrpsz) ;
ATStmpdec(tmp3, atstype_arrptr) ;
ATStmpdec(tmp4, postiats_tyrec_0) ;
ATStmpdec(tmp5, postiats_tyrec_0) ;
ATStmpdec(tmp6, postiats_tyrec_0) ;
ATStmpdec_void(tmp25, atsvoid_t0ype) ;
ATStmpdec(tmp37, postiats_tyrec_0) ;
ATStmpdec_void(tmp38, atsvoid_t0ype) ;
ATStmpdec(tmpref39, postiats_tyrec_1) ;
ATStmpdec(tmp40, postiats_tyrec_0) ;
ATStmpdec_void(tmp41, atsvoid_t0ype) ;
ATStmpdec(tmp42, atstkind_t0ype(atstype_bool)) ;
ATStmpdec_void(tmp47, atsvoid_t0ype) ;
ATStmpdec(tmp48, atstkind_t0ype(atstype_bool)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_foo_0:
/*
letpush(beg)
*/
/*
ATSINStmpdec(tmp2)) ;
*/
ATSINSstore_arrpsz_asz(tmp2, 2) ;
ATSINSstore_arrpsz_ptr(tmp2, postiats_tyrec_0, 2) ;
ATSINSmove_arrpsz_ptr(tmp3, tmp2) ;
ATSINSstore_fltrec_ofs (tmp4, postiats_tyrec_0, atslab$0, ATSPMVi0nt(1)) ;
ATSINSstore_fltrec_ofs (tmp4, postiats_tyrec_0, atslab$1, ATSPMVi0nt(1)) ;
ATSINSpmove(tmp3, postiats_tyrec_0, tmp4) ;
ATSINSupdate_ptrinc(tmp3, postiats_tyrec_0) ;
ATSINSstore_fltrec_ofs (tmp5, postiats_tyrec_0, atslab$0, ATSPMVi0nt(2)) ;
ATSINSstore_fltrec_ofs (tmp5, postiats_tyrec_0, atslab$1, ATSPMVi0nt(2)) ;
ATSINSpmove(tmp3, postiats_tyrec_0, tmp5) ;
ATSINSmove(tmp1, atspre_arrayptr_make_arrpsz(tmp2)) ;
ATSINSmove(tmp6, _057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$ATS_055$Postiats_057$prelude_057$SATS_057$arrayptr_056$sats_arrayptr_get_at_gint$1$1(ATSPMVrefarg0(tmp1), ATSPMVi0nt(0))) ;
ATSINSstore_fltrec_ofs (tmp37, postiats_tyrec_0, atslab$0, ATSPMVi0nt(3)) ;
ATSINSstore_fltrec_ofs (tmp37, postiats_tyrec_0, atslab$1, ATSPMVi0nt(3)) ;
ATSINSmove_void(tmp25, _057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$ATS_055$Postiats_057$prelude_057$SATS_057$arrayptr_056$sats_arrayptr_set_at_gint$11$1(ATSPMVrefarg0(tmp1), ATSPMVi0nt(0), tmp37)) ;
ATSINSmove_void(tmp38, atspre_arrayptr_free(tmp1)) ;
/*
ATSINStmpdec(tmpref39)) ;
*/
ATSINSstore_fltrec_ofs (tmp40, postiats_tyrec_0, atslab$0, ATSPMVi0nt(2)) ;
ATSINSstore_fltrec_ofs (tmp40, postiats_tyrec_0, atslab$1, ATSPMVi0nt(3)) ;
ATSINSstore_fltrec_ofs (tmpref39, postiats_tyrec_1, atslab$0, ATSPMVi0nt(1)) ;
ATSINSstore_fltrec_ofs (tmpref39, postiats_tyrec_1, atslab$1, tmp40) ;
ATSINSstore(ATSselfltrec(tmpref39, postiats_tyrec_1, atslab$0), ATSPMVi0nt(3)) ;
ATSINSstore(ATSselfltrec(ATSselfltrec(tmpref39, postiats_tyrec_1, atslab$1), postiats_tyrec_0, atslab$0), ATSPMVi0nt(4)) ;
ATSINSmove(tmp42, _057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$ATS_055$Postiats_057$prelude_057$SATS_057$integer_056$sats_eq_g1int_int$17$1(ATSselfltrec(tmpref39, postiats_tyrec_1, atslab$0), ATSPMVi0nt(3))) ;
ATSINSmove_void(tmp41, atspre_assert_errmsg_bool1(tmp42, ATSCSTSPmyloc("/home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/test19.dats: 309(line=19, offs=10) -- 328(line=19, offs=29)"))) ;
ATSINSmove(tmp48, _057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$ATS_055$Postiats_057$prelude_057$SATS_057$integer_056$sats_eq_g1int_int$17$2(ATSselfltrec(ATSselfltrec(tmpref39, postiats_tyrec_1, atslab$1), postiats_tyrec_0, atslab$0), ATSPMVi0nt(4))) ;
ATSINSmove_void(tmp47, atspre_assert_errmsg_bool1(tmp48, ATSCSTSPmyloc("/home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/test19.dats: 339(line=20, offs=10) -- 360(line=20, offs=31)"))) ;
/*
letpush(end)
*/

ATSINSmove_void(tmpret0, ATSempty()) ;
/*
INSletpop()
*/
/* funbodyinstrlst(end) */
ATSreturn_void(tmpret0) ;
} /* end of [foo_0] */

#if(0)
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/arrayptr.dats: 3559(line=155, offs=3) -- 3648(line=158, offs=4)
*/
/*
local: 
global: arrayptr_get_at_gint$1$0(0)
local: 
global: 
*/
ATSglobaldec()
/*
imparg = a(4023), tk(4024)
tmparg = S2Evar(a(4023)); S2Evar(tk(4024))
tmpsub = None()
*/
atstyvar_type(a)
_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$ATS_055$Postiats_057$prelude_057$SATS_057$arrayptr_056$sats_arrayptr_get_at_gint$1(atsrefarg0_type(atstkind_type(atstype_ptrk)) arg0, atstkind_t0ype(atstyvar_type(tk)) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret7, atstyvar_type(a)) ;
ATStmpdec(tmp8, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_arrayptr_get_at_gint:
/*
letpush(beg)
*/
/* (*nothing*) */
/*
letpush(end)
*/

ATSINSmove(tmp8, PMVtmpltcst(ptr1_add_gint<S2Evar(a(4023))><S2Evar(tk(4024))>)(ATSPMVcastfn(arrayptr2ptr, atstkind_type(atstype_ptrk), ATSPMVrefarg0(arg0)), arg1)) ;
ATSINSmove(tmpret7, PMVtmpltcst(ptr0_get<S2Evar(a(4023))>)(tmp8)) ;
/*
INSletpop()
*/
/* funbodyinstrlst(end) */
ATSreturn(tmpret7) ;
} /* end of [_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$ATS_055$Postiats_057$prelude_057$SATS_057$arrayptr_056$sats_arrayptr_get_at_gint$1] */
#endif // end of [TEMPLATE]

/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/arrayptr.dats: 3559(line=155, offs=3) -- 3648(line=158, offs=4)
*/
/*
local: 
global: arrayptr_get_at_gint$1$1(1)
local: 
global: 
*/
ATSstaticdec()
/*
imparg = a(4023), tk(4024)
tmparg = S2Evar(a(4023)); S2Evar(tk(4024))
tmpsub = Some(a(4023) -> S2Etyrec(flt0; npf=-1; 0=S2Ecst(int), 1=S2Ecst(int)); tk(4024) -> S2Eextkind(atstype_int))
*/
postiats_tyrec_0
_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$ATS_055$Postiats_057$prelude_057$SATS_057$arrayptr_056$sats_arrayptr_get_at_gint$1$1(atsrefarg0_type(atstkind_type(atstype_ptrk)) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmp7$1, postiats_tyrec_0) ;
ATStmpdec(tmp8$1, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_arrayptr_get_at_gint:
/*
letpush(beg)
*/
/* (*nothing*) */
/*
letpush(end)
*/

ATSINSmove(tmp8$1, _057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$ATS_055$Postiats_057$prelude_057$SATS_057$pointer_056$sats_ptr1_add_gint$3$1(ATSPMVcastfn(arrayptr2ptr, atstkind_type(atstype_ptrk), ATSPMVrefarg0(arg0)), arg1)) ;
ATSINSmove(tmp7$1, _057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$ATS_055$Postiats_057$prelude_057$SATS_057$unsafe_056$sats_ptr0_get$9$1(tmp8$1)) ;
/*
INSletpop()
*/
/* funbodyinstrlst(end) */
ATSreturn(tmp7$1) ;
} /* end of [_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$ATS_055$Postiats_057$prelude_057$SATS_057$arrayptr_056$sats_arrayptr_get_at_gint$1$1] */

#if(0)
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/pointer.dats: 2542(line=93, offs=22) -- 2609(line=94, offs=59)
*/
/*
local: 
global: ptr1_add_gint$3$0(0)
local: 
global: 
*/
ATSglobaldec()
/*
imparg = a(3245), tk(3246)
tmparg = S2Evar(a(3245)); S2Evar(tk(3246))
tmpsub = None()
*/
atstkind_type(atstype_ptrk)
_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$ATS_055$Postiats_057$prelude_057$SATS_057$pointer_056$sats_ptr1_add_gint$3(atstkind_type(atstype_ptrk) arg0, atstkind_t0ype(atstyvar_type(tk)) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret11, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp12, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_ptr1_add_gint:
ATSINSmove(tmp12, PMVtmpltcst(ptr0_add_gint<S2Evar(a(3245))><S2Evar(tk(3246))>)(arg0, arg1)) ;
ATSINSmove(tmpret11, ATSPMVcastfn(cast, atstkind_type(atstype_ptrk), tmp12)) ;
/* funbodyinstrlst(end) */
ATSreturn(tmpret11) ;
} /* end of [_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$ATS_055$Postiats_057$prelude_057$SATS_057$pointer_056$sats_ptr1_add_gint$3] */
#endif // end of [TEMPLATE]

/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/pointer.dats: 2542(line=93, offs=22) -- 2609(line=94, offs=59)
*/
/*
local: 
global: ptr1_add_gint$3$1(2)
local: 
global: 
*/
ATSstaticdec()
/*
imparg = a(3245), tk(3246)
tmparg = S2Evar(a(3245)); S2Evar(tk(3246))
tmpsub = Some(a(3245) -> S2Etyrec(flt0; npf=-1; 0=S2Ecst(int), 1=S2Ecst(int)); tk(3246) -> S2Eextkind(atstype_int))
*/
atstkind_type(atstype_ptrk)
_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$ATS_055$Postiats_057$prelude_057$SATS_057$pointer_056$sats_ptr1_add_gint$3$1(atstkind_type(atstype_ptrk) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmp11$1, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp12$1, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_ptr1_add_gint:
ATSINSmove(tmp12$1, _057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$ATS_055$Postiats_057$prelude_057$SATS_057$pointer_056$sats_ptr0_add_gint$5$1(arg0, arg1)) ;
ATSINSmove(tmp11$1, ATSPMVcastfn(cast, atstkind_type(atstype_ptrk), tmp12$1)) ;
/* funbodyinstrlst(end) */
ATSreturn(tmp11$1) ;
} /* end of [_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$ATS_055$Postiats_057$prelude_057$SATS_057$pointer_056$sats_ptr1_add_gint$3$1] */

#if(0)
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/pointer.dats: 1962(line=68, offs=15) -- 2021(line=69, offs=51)
*/
/*
local: 
global: ptr0_add_gint$5$0(0)
local: 
global: 
*/
ATSglobaldec()
/*
imparg = a(3231), tk(3232)
tmparg = S2Evar(a(3231)); S2Evar(tk(3232))
tmpsub = None()
*/
atstkind_type(atstype_ptrk)
_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$ATS_055$Postiats_057$prelude_057$SATS_057$pointer_056$sats_ptr0_add_gint$5(atstkind_type(atstype_ptrk) arg0, atstkind_t0ype(atstyvar_type(tk)) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret15, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp16, atstkind_t0ype(atstype_size)) ;
ATStmpdec(tmp17, atstkind_t0ype(atstype_size)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_ptr0_add_gint:
ATSINSmove(tmp17, PMVtmpltcst(g0int2uint<S2EVar(824->S2Evar(tk(3232))), S2EVar(825->S2EVar(826->S2Eextkind(atstype_size)))>)(arg1)) ;
ATSINSmove(tmp16, PMVtmpltcst(g0uint_mul<S2EVar(826->S2Eextkind(atstype_size))>)(tmp17, ATSPMVsizeof(atstyvar_type(a)))) ;
ATSINSmove(tmpret15, atspre_ptr0_add_bytesize(arg0, tmp16)) ;
/* funbodyinstrlst(end) */
ATSreturn(tmpret15) ;
} /* end of [_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$ATS_055$Postiats_057$prelude_057$SATS_057$pointer_056$sats_ptr0_add_gint$5] */
#endif // end of [TEMPLATE]

/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/pointer.dats: 1962(line=68, offs=15) -- 2021(line=69, offs=51)
*/
/*
local: 
global: ptr0_add_gint$5$1(3)
local: 
global: 
*/
ATSstaticdec()
/*
imparg = a(3231), tk(3232)
tmparg = S2Evar(a(3231)); S2Evar(tk(3232))
tmpsub = Some(a(3231) -> S2Etyrec(flt0; npf=-1; 0=S2Ecst(int), 1=S2Ecst(int)); tk(3232) -> S2Eextkind(atstype_int))
*/
atstkind_type(atstype_ptrk)
_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$ATS_055$Postiats_057$prelude_057$SATS_057$pointer_056$sats_ptr0_add_gint$5$1(atstkind_type(atstype_ptrk) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmp15$1, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp16$1, atstkind_t0ype(atstype_size)) ;
ATStmpdec(tmp17$1, atstkind_t0ype(atstype_size)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_ptr0_add_gint:
ATSINSmove(tmp17$1, atspre_g0int2uint_int_size(arg1)) ;
ATSINSmove(tmp16$1, atspre_g0uint_mul_size(tmp17$1, ATSPMVsizeof(postiats_tyrec_0))) ;
ATSINSmove(tmp15$1, atspre_ptr0_add_bytesize(arg0, tmp16$1)) ;
/* funbodyinstrlst(end) */
ATSreturn(tmp15$1) ;
} /* end of [_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$ATS_055$Postiats_057$prelude_057$SATS_057$pointer_056$sats_ptr0_add_gint$5$1] */

#if(0)
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/unsafe.dats: 1621(line=51, offs=3) -- 1836(line=59, offs=2)
*/
/*
local: 
global: ptr0_get$9$0(0)
local: 
global: 
*/
ATSglobaldec()
/*
imparg = a(4362)
tmparg = S2Evar(a(4362))
tmpsub = None()
*/
atstyvar_type(a)
_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$ATS_055$Postiats_057$prelude_057$SATS_057$unsafe_056$sats_ptr0_get$9(atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret21, atstyvar_type(a)) ;
ATStmpdec(tmp22, atstyvar_type(a)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_ptr0_get:
/*
letpush(beg)
*/
/* (*nothing*) */
/* (*nothing*) */
ATSINSmove(tmp22, ATSderef(ATSPMVcastfn(ptr1_of_ptr0, atstkind_type(atstype_ptrk), arg0), atstyvar_type(a))) ;
/* (*nothing*) */
/*
letpush(end)
*/

ATSINSmove(tmpret21, tmp22) ;
/*
INSletpop()
*/
/* funbodyinstrlst(end) */
ATSreturn(tmpret21) ;
} /* end of [_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$ATS_055$Postiats_057$prelude_057$SATS_057$unsafe_056$sats_ptr0_get$9] */
#endif // end of [TEMPLATE]

/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/unsafe.dats: 1621(line=51, offs=3) -- 1836(line=59, offs=2)
*/
/*
local: 
global: ptr0_get$9$1(2)
local: 
global: 
*/
ATSstaticdec()
/*
imparg = a(4362)
tmparg = S2Evar(a(4362))
tmpsub = Some(a(4362) -> S2Etyrec(flt0; npf=-1; 0=S2Ecst(int), 1=S2Ecst(int)))
*/
postiats_tyrec_0
_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$ATS_055$Postiats_057$prelude_057$SATS_057$unsafe_056$sats_ptr0_get$9$1(atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmp21$1, postiats_tyrec_0) ;
ATStmpdec(tmp22$1, postiats_tyrec_0) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_ptr0_get:
/*
letpush(beg)
*/
/* (*nothing*) */
/* (*nothing*) */
ATSINSmove(tmp22$1, ATSderef(ATSPMVcastfn(ptr1_of_ptr0, atstkind_type(atstype_ptrk), arg0), postiats_tyrec_0)) ;
/* (*nothing*) */
/*
letpush(end)
*/

ATSINSmove(tmp21$1, tmp22$1) ;
/*
INSletpop()
*/
/* funbodyinstrlst(end) */
ATSreturn(tmp21$1) ;
} /* end of [_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$ATS_055$Postiats_057$prelude_057$SATS_057$unsafe_056$sats_ptr0_get$9$1] */

#if(0)
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/arrayptr.dats: 3911(line=171, offs=3) -- 4006(line=174, offs=4)
*/
/*
local: 
global: arrayptr_set_at_gint$11$0(0)
local: 
global: 
*/
ATSglobaldec()
/*
imparg = a(4033), tk(4034)
tmparg = S2Evar(a(4033)); S2Evar(tk(4034))
tmpsub = None()
*/
atsvoid_t0ype
_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$ATS_055$Postiats_057$prelude_057$SATS_057$arrayptr_056$sats_arrayptr_set_at_gint$11(atsrefarg0_type(atstkind_type(atstype_ptrk)) arg0, atstkind_t0ype(atstyvar_type(tk)) arg1, atstyvar_type(a) arg2)
{
/* tmpvardeclst(beg) */
ATStmpdec_void(tmpret26, atsvoid_t0ype) ;
ATStmpdec(tmp27, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_arrayptr_set_at_gint:
/*
letpush(beg)
*/
/* (*nothing*) */
/*
letpush(end)
*/

ATSINSmove(tmp27, PMVtmpltcst(ptr1_add_gint<S2Evar(a(4033))><S2Evar(tk(4034))>)(ATSPMVcastfn(arrayptr2ptr, atstkind_type(atstype_ptrk), ATSPMVrefarg0(arg0)), arg1)) ;
ATSINSmove_void(tmpret26, PMVtmpltcst(ptr0_set<S2Evar(a(4033))>)(tmp27, arg2)) ;
/*
INSletpop()
*/
/* funbodyinstrlst(end) */
ATSreturn_void(tmpret26) ;
} /* end of [_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$ATS_055$Postiats_057$prelude_057$SATS_057$arrayptr_056$sats_arrayptr_set_at_gint$11] */
#endif // end of [TEMPLATE]

/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/arrayptr.dats: 3911(line=171, offs=3) -- 4006(line=174, offs=4)
*/
/*
local: 
global: arrayptr_set_at_gint$11$1(1)
local: 
global: 
*/
ATSstaticdec()
/*
imparg = a(4033), tk(4034)
tmparg = S2Evar(a(4033)); S2Evar(tk(4034))
tmpsub = Some(a(4033) -> S2Etyrec(flt0; npf=-1; 0=S2Ecst(int), 1=S2Ecst(int)); tk(4034) -> S2Eextkind(atstype_int))
*/
atsvoid_t0ype
_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$ATS_055$Postiats_057$prelude_057$SATS_057$arrayptr_056$sats_arrayptr_set_at_gint$11$1(atsrefarg0_type(atstkind_type(atstype_ptrk)) arg0, atstkind_t0ype(atstype_int) arg1, postiats_tyrec_0 arg2)
{
/* tmpvardeclst(beg) */
ATStmpdec_void(tmp26$1, atsvoid_t0ype) ;
ATStmpdec(tmp27$1, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_arrayptr_set_at_gint:
/*
letpush(beg)
*/
/* (*nothing*) */
/*
letpush(end)
*/

ATSINSmove(tmp27$1, _057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$ATS_055$Postiats_057$prelude_057$SATS_057$pointer_056$sats_ptr1_add_gint$3$2(ATSPMVcastfn(arrayptr2ptr, atstkind_type(atstype_ptrk), ATSPMVrefarg0(arg0)), arg1)) ;
ATSINSmove_void(tmp26$1, _057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$ATS_055$Postiats_057$prelude_057$SATS_057$unsafe_056$sats_ptr0_set$15$1(tmp27$1, arg2)) ;
/*
INSletpop()
*/
/* funbodyinstrlst(end) */
ATSreturn_void(tmp26$1) ;
} /* end of [_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$ATS_055$Postiats_057$prelude_057$SATS_057$arrayptr_056$sats_arrayptr_set_at_gint$11$1] */

/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/pointer.dats: 2542(line=93, offs=22) -- 2609(line=94, offs=59)
*/
/*
local: 
global: ptr1_add_gint$3$2(2)
local: 
global: 
*/
ATSstaticdec()
/*
imparg = a(3245), tk(3246)
tmparg = S2Evar(a(3245)); S2Evar(tk(3246))
tmpsub = Some(a(3245) -> S2Etyrec(flt0; npf=-1; 0=S2Ecst(int), 1=S2Ecst(int)); tk(3246) -> S2Eextkind(atstype_int))
*/
atstkind_type(atstype_ptrk)
_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$ATS_055$Postiats_057$prelude_057$SATS_057$pointer_056$sats_ptr1_add_gint$3$2(atstkind_type(atstype_ptrk) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmp11$2, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp12$2, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_ptr1_add_gint:
ATSINSmove(tmp12$2, _057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$ATS_055$Postiats_057$prelude_057$SATS_057$pointer_056$sats_ptr0_add_gint$5$2(arg0, arg1)) ;
ATSINSmove(tmp11$2, ATSPMVcastfn(cast, atstkind_type(atstype_ptrk), tmp12$2)) ;
/* funbodyinstrlst(end) */
ATSreturn(tmp11$2) ;
} /* end of [_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$ATS_055$Postiats_057$prelude_057$SATS_057$pointer_056$sats_ptr1_add_gint$3$2] */

/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/pointer.dats: 1962(line=68, offs=15) -- 2021(line=69, offs=51)
*/
/*
local: 
global: ptr0_add_gint$5$2(3)
local: 
global: 
*/
ATSstaticdec()
/*
imparg = a(3231), tk(3232)
tmparg = S2Evar(a(3231)); S2Evar(tk(3232))
tmpsub = Some(a(3231) -> S2Etyrec(flt0; npf=-1; 0=S2Ecst(int), 1=S2Ecst(int)); tk(3232) -> S2Eextkind(atstype_int))
*/
atstkind_type(atstype_ptrk)
_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$ATS_055$Postiats_057$prelude_057$SATS_057$pointer_056$sats_ptr0_add_gint$5$2(atstkind_type(atstype_ptrk) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmp15$2, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp16$2, atstkind_t0ype(atstype_size)) ;
ATStmpdec(tmp17$2, atstkind_t0ype(atstype_size)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_ptr0_add_gint:
ATSINSmove(tmp17$2, atspre_g0int2uint_int_size(arg1)) ;
ATSINSmove(tmp16$2, atspre_g0uint_mul_size(tmp17$2, ATSPMVsizeof(postiats_tyrec_0))) ;
ATSINSmove(tmp15$2, atspre_ptr0_add_bytesize(arg0, tmp16$2)) ;
/* funbodyinstrlst(end) */
ATSreturn(tmp15$2) ;
} /* end of [_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$ATS_055$Postiats_057$prelude_057$SATS_057$pointer_056$sats_ptr0_add_gint$5$2] */

#if(0)
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/unsafe.dats: 1949(line=68, offs=3) -- 2174(line=76, offs=2)
*/
/*
local: 
global: ptr0_set$15$0(0)
local: 
global: 
*/
ATSglobaldec()
/*
imparg = a(4365)
tmparg = S2Evar(a(4365))
tmpsub = None()
*/
atsvoid_t0ype
_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$ATS_055$Postiats_057$prelude_057$SATS_057$unsafe_056$sats_ptr0_set$15(atstkind_type(atstype_ptrk) arg0, atstyvar_type(a) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec_void(tmpret35, atsvoid_t0ype) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_ptr0_set:
/*
letpush(beg)
*/
/* (*nothing*) */
/* (*nothing*) */
ATSINSstore(ATSderef(ATSPMVcastfn(ptr1_of_ptr0, atstkind_type(atstype_ptrk), arg0), atstyvar_type(a)), arg1) ;
/* (*nothing*) */
/*
letpush(end)
*/

ATSINSmove_void(tmpret35, ATSempty()) ;
/*
INSletpop()
*/
/* funbodyinstrlst(end) */
ATSreturn_void(tmpret35) ;
} /* end of [_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$ATS_055$Postiats_057$prelude_057$SATS_057$unsafe_056$sats_ptr0_set$15] */
#endif // end of [TEMPLATE]

/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/unsafe.dats: 1949(line=68, offs=3) -- 2174(line=76, offs=2)
*/
/*
local: 
global: ptr0_set$15$1(2)
local: 
global: 
*/
ATSstaticdec()
/*
imparg = a(4365)
tmparg = S2Evar(a(4365))
tmpsub = Some(a(4365) -> S2Etyrec(flt0; npf=-1; 0=S2Ecst(int), 1=S2Ecst(int)))
*/
atsvoid_t0ype
_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$ATS_055$Postiats_057$prelude_057$SATS_057$unsafe_056$sats_ptr0_set$15$1(atstkind_type(atstype_ptrk) arg0, postiats_tyrec_0 arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec_void(tmp35$1, atsvoid_t0ype) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_ptr0_set:
/*
letpush(beg)
*/
/* (*nothing*) */
/* (*nothing*) */
ATSINSstore(ATSderef(ATSPMVcastfn(ptr1_of_ptr0, atstkind_type(atstype_ptrk), arg0), postiats_tyrec_0), arg1) ;
/* (*nothing*) */
/*
letpush(end)
*/

ATSINSmove_void(tmp35$1, ATSempty()) ;
/*
INSletpop()
*/
/* funbodyinstrlst(end) */
ATSreturn_void(tmp35$1) ;
} /* end of [_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$ATS_055$Postiats_057$prelude_057$SATS_057$unsafe_056$sats_ptr0_set$15$1] */

#if(0)
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/integer.dats: 27035(line=704, offs=14) -- 27075(line=704, offs=54)
*/
/*
local: 
global: eq_g1int_int$17$0(0)
local: 
global: 
*/
ATSglobaldec()
/*
imparg = tk(2954)
tmparg = S2Evar(tk(2954))
tmpsub = None()
*/
atstkind_t0ype(atstype_bool)
_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$ATS_055$Postiats_057$prelude_057$SATS_057$integer_056$sats_eq_g1int_int$17(atstkind_t0ype(atstyvar_type(tk)) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret43, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp44, atstkind_t0ype(atstyvar_type(tk))) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_eq_g1int_int:
ATSINSmove(tmp44, PMVtmpltcst(g1int2int<S2EVar(406->S2Eextkind(atstype_int)), S2EVar(407->S2Evar(tk(2954)))>)(arg1)) ;
ATSINSmove(tmpret43, PMVtmpltcst(g1int_eq<S2Evar(tk(2954))>)(arg0, tmp44)) ;
/* funbodyinstrlst(end) */
ATSreturn(tmpret43) ;
} /* end of [_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$ATS_055$Postiats_057$prelude_057$SATS_057$integer_056$sats_eq_g1int_int$17] */
#endif // end of [TEMPLATE]

/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/integer.dats: 27035(line=704, offs=14) -- 27075(line=704, offs=54)
*/
/*
local: 
global: eq_g1int_int$17$1(1)
local: 
global: 
*/
ATSstaticdec()
/*
imparg = tk(2954)
tmparg = S2Evar(tk(2954))
tmpsub = Some(tk(2954) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$ATS_055$Postiats_057$prelude_057$SATS_057$integer_056$sats_eq_g1int_int$17$1(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmp43$1, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp44$1, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_eq_g1int_int:
ATSINSmove(tmp44$1, atspre_g1int2int_int_int(arg1)) ;
ATSINSmove(tmp43$1, atspre_g1int_eq_int(arg0, tmp44$1)) ;
/* funbodyinstrlst(end) */
ATSreturn(tmp43$1) ;
} /* end of [_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$ATS_055$Postiats_057$prelude_057$SATS_057$integer_056$sats_eq_g1int_int$17$1] */

/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/integer.dats: 27035(line=704, offs=14) -- 27075(line=704, offs=54)
*/
/*
local: 
global: eq_g1int_int$17$2(1)
local: 
global: 
*/
ATSstaticdec()
/*
imparg = tk(2954)
tmparg = S2Evar(tk(2954))
tmpsub = Some(tk(2954) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$ATS_055$Postiats_057$prelude_057$SATS_057$integer_056$sats_eq_g1int_int$17$2(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmp43$2, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp44$2, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_eq_g1int_int:
ATSINSmove(tmp44$2, atspre_g1int2int_int_int(arg1)) ;
ATSINSmove(tmp43$2, atspre_g1int_eq_int(arg0, tmp44$2)) ;
/* funbodyinstrlst(end) */
ATSreturn(tmp43$2) ;
} /* end of [_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$ATS_055$Postiats_057$prelude_057$SATS_057$integer_056$sats_eq_g1int_int$17$2] */

/*
/home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/test19.dats: 400(line=26, offs=17) -- 411(line=26, offs=28)
*/
/*
local: foo_0$0(0)
global: foo_0$0(0), mainats_void_0$22$0(0)
local: 
global: 
*/
ATSglobaldec()
atsvoid_t0ype
mainats_void_0()
{
/* tmpvardeclst(beg) */
ATStmpdec_void(tmpret51, atsvoid_t0ype) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_main_void_0:
ATSINSmove_void(tmpret51, foo_0()) ;
/* funbodyinstrlst(end) */
ATSreturn_void(tmpret51) ;
} /* end of [mainats_void_0] */


/*
** for initialization(dynloading)
*/
atsvoid_t0ype
_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$projects_057$org_056$ats_055$lang_056$postiats_056$jats_057$test_057$test19_056$dats__dynload()
{
ATSdynload0(
_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$projects_057$org_056$ats_055$lang_056$postiats_056$jats_057$test_057$test19_056$dats__dynloadflag
) ;
ATSif(
ATSCKiseqz(
_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$projects_057$org_056$ats_055$lang_056$postiats_056$jats_057$test_057$test19_056$dats__dynloadflag
)
) ATSthen() {
ATSdynloadset(_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$projects_057$org_056$ats_055$lang_056$postiats_056$jats_057$test_057$test19_056$dats__dynloadflag) ;
} /* ATSendif */
ATSreturn_void() ;
} /* end of [*_dynload] */

/*
** the ATS runtime
*/
#ifndef _ATS_CCOMP_RUNTIME_NONE
#include "pats_ccomp_runtime.c"
#endif /* _ATS_CCOMP_RUNTIME_NONE */

/*
** the [main] implementation
*/
int
main
(
int argc, char **argv, char **envp
) {
int err = 0 ;
_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$projects_057$org_056$ats_055$lang_056$postiats_056$jats_057$test_057$test19_056$dats__dynload() ;
ATSmainats_void_0(err) ;
return (err) ;
} /* end of [main] */
