/*

staload
"prelude/DATS/integer.dats"
staload
"prelude/DATS/pointer.dats"
staload
"prelude/DATS/arrayptr.dats"
//
staload
_(*anon*) = "prelude/DATS/unsafe.dats"
//
val psz =
  $arrpsz{double}(1.0, 2.0, 3.0)
var asz: size_t
val A = arrpsz_get_ptrsize (psz, asz)
//
val () = println! ("A[0] = ", A[0])
val () = println! ("A[1] = ", A[1])
val () = println! ("A[2] = ", A[2])

*/

/*
**
** The C code is generated by ATS/Postiats
** The compilation time is: 2013-1-25: 15h:49m
**
*/

/*
** include runtime header files
*/
#ifndef _ATS_CCOMP_HEADER_NONE
#include "pats_ccomp_config.h"
#include "pats_ccomp_basics.h"
#include "pats_ccomp_typedefs.h"
#include "pats_ccomp_instrset.h"
#include "pats_ccomp_exception.h"
#include "pats_ccomp_memalloc.h"
#endif /* _ATS_CCOMP_HEADER_NONE */


/*
** include prelude cats files
*/
#ifndef _ATS_CCOMP_PRELUDE_NONE
//
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/float.cats"
//
#include "prelude/CATS/list.cats"
#include "prelude/CATS/option.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/arrayptr.cats"
#include "prelude/CATS/arrayref.cats"
#include "prelude/CATS/matrix.cats"
//
#endif /* _ATS_CCOMP_PRELUDE_NONE */

#define ATS_MALLOC malloc

/*
typedefs-for-tyrecs-and-tysums(beg)
*/
/*
typedefs-for-tyrecs-and-tysums(end)
*/
ATStmpdec(tmp0, atstype_arrpsz) ;
ATStmpdec(tmp1, atstype_arrptr) ;
ATStmpdec(tmp2, atstkind_t0ype(atstype_size)) ;
ATStmpdec(tmp3, atstkind_type(atstype_ptrk)) ;
ATStmpdec_void(tmp4, atsvoid_t0ype) ;
ATStmpdec_void(tmp5, atsvoid_t0ype) ;
ATStmpdec(tmp6, atstkind_t0ype(atstype_double)) ;
ATStmpdec_void(tmp25, atsvoid_t0ype) ;
ATStmpdec_void(tmp26, atsvoid_t0ype) ;
ATStmpdec_void(tmp27, atsvoid_t0ype) ;
ATStmpdec(tmp28, atstkind_t0ype(atstype_double)) ;
ATStmpdec_void(tmp38, atsvoid_t0ype) ;
ATStmpdec_void(tmp39, atsvoid_t0ype) ;
ATStmpdec_void(tmp40, atsvoid_t0ype) ;
ATStmpdec(tmp41, atstkind_t0ype(atstype_double)) ;
ATStmpdec_void(tmp51, atsvoid_t0ype) ;
#if(0)
ATSglobaldec()
HITundef(HSEtyvar(a(2897)))
_057$home_057$hwxi_057$research_057$Postiats_057$git_057$prelude_057$SATS_057$arrayptr_056$sats__arrayptr_get_at_gint$0 (atsrefarg0_type(atstkind_type(atstype_ptrk)) arg0, atstkind_t0ype(postiats_undef(HSEtyvar(tk(2898)))) arg1) ;
#endif // end of [TEMPLATE]

ATSstaticdec()
atstkind_t0ype(atstype_double)
_057$home_057$hwxi_057$research_057$Postiats_057$git_057$prelude_057$SATS_057$arrayptr_056$sats__arrayptr_get_at_gint$0$1 (atsrefarg0_type(atstkind_type(atstype_ptrk)) arg0, atstkind_t0ype(atstype_int) arg1) ;

#if(0)
ATSglobaldec()
atstkind_type(atstype_ptrk)
_057$home_057$hwxi_057$research_057$Postiats_057$git_057$prelude_057$SATS_057$pointer_056$sats__ptr1_add_gint$2 (atstkind_type(atstype_ptrk) arg0, atstkind_t0ype(postiats_undef(HSEtyvar(tk(2862)))) arg1) ;
#endif // end of [TEMPLATE]

ATSstaticdec()
atstkind_type(atstype_ptrk)
_057$home_057$hwxi_057$research_057$Postiats_057$git_057$prelude_057$SATS_057$pointer_056$sats__ptr1_add_gint$2$1 (atstkind_type(atstype_ptrk) arg0, atstkind_t0ype(atstype_int) arg1) ;

#if(0)
ATSglobaldec()
atstkind_type(atstype_ptrk)
_057$home_057$hwxi_057$research_057$Postiats_057$git_057$prelude_057$SATS_057$pointer_056$sats__ptr0_add_gint$4 (atstkind_type(atstype_ptrk) arg0, atstkind_t0ype(postiats_undef(HSEtyvar(tk(2854)))) arg1) ;
#endif // end of [TEMPLATE]

ATSstaticdec()
atstkind_type(atstype_ptrk)
_057$home_057$hwxi_057$research_057$Postiats_057$git_057$prelude_057$SATS_057$pointer_056$sats__ptr0_add_gint$4$1 (atstkind_type(atstype_ptrk) arg0, atstkind_t0ype(atstype_int) arg1) ;

#if(0)
ATSglobaldec()
HITundef(HSEtyvar(a(2938)))
_057$home_057$hwxi_057$research_057$Postiats_057$git_057$prelude_057$SATS_057$unsafe_056$sats__ptr0_get$8 (atstkind_type(atstype_ptrk) arg0) ;
#endif // end of [TEMPLATE]

ATSstaticdec()
atstkind_t0ype(atstype_double)
_057$home_057$hwxi_057$research_057$Postiats_057$git_057$prelude_057$SATS_057$unsafe_056$sats__ptr0_get$8$1 (atstkind_type(atstype_ptrk) arg0) ;

ATSstaticdec()
atstkind_t0ype(atstype_double)
_057$home_057$hwxi_057$research_057$Postiats_057$git_057$prelude_057$SATS_057$arrayptr_056$sats__arrayptr_get_at_gint$0$2 (atsrefarg0_type(atstkind_type(atstype_ptrk)) arg0, atstkind_t0ype(atstype_int) arg1) ;

ATSstaticdec()
atstkind_type(atstype_ptrk)
_057$home_057$hwxi_057$research_057$Postiats_057$git_057$prelude_057$SATS_057$pointer_056$sats__ptr1_add_gint$2$2 (atstkind_type(atstype_ptrk) arg0, atstkind_t0ype(atstype_int) arg1) ;

ATSstaticdec()
atstkind_type(atstype_ptrk)
_057$home_057$hwxi_057$research_057$Postiats_057$git_057$prelude_057$SATS_057$pointer_056$sats__ptr0_add_gint$4$2 (atstkind_type(atstype_ptrk) arg0, atstkind_t0ype(atstype_int) arg1) ;

ATSstaticdec()
atstkind_t0ype(atstype_double)
_057$home_057$hwxi_057$research_057$Postiats_057$git_057$prelude_057$SATS_057$unsafe_056$sats__ptr0_get$8$2 (atstkind_type(atstype_ptrk) arg0) ;

ATSstaticdec()
atstkind_t0ype(atstype_double)
_057$home_057$hwxi_057$research_057$Postiats_057$git_057$prelude_057$SATS_057$arrayptr_056$sats__arrayptr_get_at_gint$0$3 (atsrefarg0_type(atstkind_type(atstype_ptrk)) arg0, atstkind_t0ype(atstype_int) arg1) ;

ATSstaticdec()
atstkind_type(atstype_ptrk)
_057$home_057$hwxi_057$research_057$Postiats_057$git_057$prelude_057$SATS_057$pointer_056$sats__ptr1_add_gint$2$3 (atstkind_type(atstype_ptrk) arg0, atstkind_t0ype(atstype_int) arg1) ;

ATSstaticdec()
atstkind_type(atstype_ptrk)
_057$home_057$hwxi_057$research_057$Postiats_057$git_057$prelude_057$SATS_057$pointer_056$sats__ptr0_add_gint$4$3 (atstkind_type(atstype_ptrk) arg0, atstkind_t0ype(atstype_int) arg1) ;

ATSstaticdec()
atstkind_t0ype(atstype_double)
_057$home_057$hwxi_057$research_057$Postiats_057$git_057$prelude_057$SATS_057$unsafe_056$sats__ptr0_get$8$3 (atstkind_type(atstype_ptrk) arg0) ;

#if(0)
ATSglobaldec()
/*
imparg = a(2897), tk(2898)
tmparg = S2Evar(a(2897)); S2Evar(tk(2898))
tmpsub = None()
*/
HITundef(HSEtyvar(a(2897)))
_057$home_057$hwxi_057$research_057$Postiats_057$git_057$prelude_057$SATS_057$arrayptr_056$sats__arrayptr_get_at_gint$0 (atsrefarg0_type(atstkind_type(atstype_ptrk)) arg0, atstkind_t0ype(postiats_undef(HSEtyvar(tk(2898)))) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmp7, HITundef(HSEtyvar(a(2897)))) ;
ATStmpdec(tmp8, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_arrayptr_get_at_gint:
/*
letpush(beg)
*/
/* (*nothing*) */
/*
letpush(end)
*/

ATSINSmove(tmp8, PMVtmpltcst(ptr1_add_gint<S2Evar(a(2897))><S2Evar(tk(2898))>)(ATSPMVcastfn(arrayptr2ptr, atstkind_type(atstype_ptrk), ATSPMVrefarg0(arg0)), arg1)) ;
ATSINSmove(tmp7, PMVtmpltcst(ptr0_get<S2Evar(a(2897))>)(tmp8)) ;
/*
INSletpop()
*/
/* funbodyinstrlst(end) */
ATSreturn(tmp7) ;
} /* end of [_057$home_057$hwxi_057$research_057$Postiats_057$git_057$prelude_057$SATS_057$arrayptr_056$sats__arrayptr_get_at_gint$0] */
#endif // end of [TEMPLATE]
ATSstaticdec()
/*
imparg = a(2897), tk(2898)
tmparg = S2Evar(a(2897)); S2Evar(tk(2898))
tmpsub = Some(a(2897) -> S2Eapp(S2Ecst(g0float_t0ype); S2Ecst(double_kind)); tk(2898) -> S2Etkname(atstype_int))
*/
atstkind_t0ype(atstype_double)
_057$home_057$hwxi_057$research_057$Postiats_057$git_057$prelude_057$SATS_057$arrayptr_056$sats__arrayptr_get_at_gint$0$1 (atsrefarg0_type(atstkind_type(atstype_ptrk)) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmp7$1, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp8$1, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_arrayptr_get_at_gint:
/*
letpush(beg)
*/
/* (*nothing*) */
/*
letpush(end)
*/

ATSINSmove(tmp8$1, _057$home_057$hwxi_057$research_057$Postiats_057$git_057$prelude_057$SATS_057$pointer_056$sats__ptr1_add_gint$2$1(ATSPMVcastfn(arrayptr2ptr, atstkind_type(atstype_ptrk), ATSPMVrefarg0(arg0)), arg1)) ;
ATSINSmove(tmp7$1, _057$home_057$hwxi_057$research_057$Postiats_057$git_057$prelude_057$SATS_057$unsafe_056$sats__ptr0_get$8$1(tmp8$1)) ;
/*
INSletpop()
*/
/* funbodyinstrlst(end) */
ATSreturn(tmp7$1) ;
} /* end of [_057$home_057$hwxi_057$research_057$Postiats_057$git_057$prelude_057$SATS_057$arrayptr_056$sats__arrayptr_get_at_gint$0$1] */
#if(0)
ATSglobaldec()
/*
imparg = a(2861), tk(2862)
tmparg = S2Evar(a(2861)); S2Evar(tk(2862))
tmpsub = None()
*/
atstkind_type(atstype_ptrk)
_057$home_057$hwxi_057$research_057$Postiats_057$git_057$prelude_057$SATS_057$pointer_056$sats__ptr1_add_gint$2 (atstkind_type(atstype_ptrk) arg0, atstkind_t0ype(postiats_undef(HSEtyvar(tk(2862)))) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmp11, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp12, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_ptr1_add_gint:
ATSINSmove(tmp12, PMVtmpltcst(ptr0_add_gint<S2Evar(a(2861))><S2Evar(tk(2862))>)(arg0, arg1)) ;
ATSINSmove(tmp11, ATSPMVcastfn(cast, atstkind_type(atstype_ptrk), tmp12)) ;
/* funbodyinstrlst(end) */
ATSreturn(tmp11) ;
} /* end of [_057$home_057$hwxi_057$research_057$Postiats_057$git_057$prelude_057$SATS_057$pointer_056$sats__ptr1_add_gint$2] */
#endif // end of [TEMPLATE]
ATSstaticdec()
/*
imparg = a(2861), tk(2862)
tmparg = S2Evar(a(2861)); S2Evar(tk(2862))
tmpsub = Some(a(2861) -> S2Eapp(S2Ecst(g0float_t0ype); S2Ecst(double_kind)); tk(2862) -> S2Etkname(atstype_int))
*/
atstkind_type(atstype_ptrk)
_057$home_057$hwxi_057$research_057$Postiats_057$git_057$prelude_057$SATS_057$pointer_056$sats__ptr1_add_gint$2$1 (atstkind_type(atstype_ptrk) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmp11$1, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp12$1, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_ptr1_add_gint:
ATSINSmove(tmp12$1, _057$home_057$hwxi_057$research_057$Postiats_057$git_057$prelude_057$SATS_057$pointer_056$sats__ptr0_add_gint$4$1(arg0, arg1)) ;
ATSINSmove(tmp11$1, ATSPMVcastfn(cast, atstkind_type(atstype_ptrk), tmp12$1)) ;
/* funbodyinstrlst(end) */
ATSreturn(tmp11$1) ;
} /* end of [_057$home_057$hwxi_057$research_057$Postiats_057$git_057$prelude_057$SATS_057$pointer_056$sats__ptr1_add_gint$2$1] */
#if(0)
ATSglobaldec()
/*
imparg = a(2853), tk(2854)
tmparg = S2Evar(a(2853)); S2Evar(tk(2854))
tmpsub = None()
*/
atstkind_type(atstype_ptrk)
_057$home_057$hwxi_057$research_057$Postiats_057$git_057$prelude_057$SATS_057$pointer_056$sats__ptr0_add_gint$4 (atstkind_type(atstype_ptrk) arg0, atstkind_t0ype(postiats_undef(HSEtyvar(tk(2854)))) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmp15, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp16, atstkind_t0ype(atstype_size)) ;
ATStmpdec(tmp17, atstkind_t0ype(atstype_size)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_ptr0_add_gint:
ATSINSmove(tmp17, PMVtmpltcst(g0int2uint<S2EVar(456->S2Evar(tk(2854))), S2EVar(457->S2EVar(458->S2Etkname(atstype_size)))>)(arg1)) ;
ATSINSmove(tmp16, PMVtmpltcst(g0uint_mul<S2EVar(458->S2Etkname(atstype_size))>)(tmp17, ATSPMVsizeof(HITundef(HSEtyvar(a(2853)))))) ;
ATSINSmove(tmp15, atspre_ptr0_add_bytesize(arg0, tmp16)) ;
/* funbodyinstrlst(end) */
ATSreturn(tmp15) ;
} /* end of [_057$home_057$hwxi_057$research_057$Postiats_057$git_057$prelude_057$SATS_057$pointer_056$sats__ptr0_add_gint$4] */
#endif // end of [TEMPLATE]
ATSstaticdec()
/*
imparg = a(2853), tk(2854)
tmparg = S2Evar(a(2853)); S2Evar(tk(2854))
tmpsub = Some(a(2853) -> S2Eapp(S2Ecst(g0float_t0ype); S2Ecst(double_kind)); tk(2854) -> S2Etkname(atstype_int))
*/
atstkind_type(atstype_ptrk)
_057$home_057$hwxi_057$research_057$Postiats_057$git_057$prelude_057$SATS_057$pointer_056$sats__ptr0_add_gint$4$1 (atstkind_type(atstype_ptrk) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmp15$1, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp16$1, atstkind_t0ype(atstype_size)) ;
ATStmpdec(tmp17$1, atstkind_t0ype(atstype_size)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_ptr0_add_gint:
ATSINSmove(tmp17$1, atspre_g0int2uint_int_size(arg1)) ;
ATSINSmove(tmp16$1, atspre_g0uint_mul_size(tmp17$1, ATSPMVsizeof(atstkind_t0ype(atstype_double)))) ;
ATSINSmove(tmp15$1, atspre_ptr0_add_bytesize(arg0, tmp16$1)) ;
/* funbodyinstrlst(end) */
ATSreturn(tmp15$1) ;
} /* end of [_057$home_057$hwxi_057$research_057$Postiats_057$git_057$prelude_057$SATS_057$pointer_056$sats__ptr0_add_gint$4$1] */
#if(0)
ATSglobaldec()
/*
imparg = a(2938)
tmparg = S2Evar(a(2938))
tmpsub = None()
*/
HITundef(HSEtyvar(a(2938)))
_057$home_057$hwxi_057$research_057$Postiats_057$git_057$prelude_057$SATS_057$unsafe_056$sats__ptr0_get$8 (atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmp21, HITundef(HSEtyvar(a(2938)))) ;
ATStmpdec(tmp22, HITundef(HSEtyvar(a(2938)))) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_ptr0_get:
/*
letpush(beg)
*/
/* (*nothing*) */
/* (*nothing*) */
ATSINSload(tmp22, ATSderef2(ATSPMVcastfn(ptr1_of_ptr0, atstkind_type(atstype_ptrk), arg0), HITundef(HSEtyvar(a(2938))))) ; 
/* (*nothing*) */
/*
letpush(end)
*/

ATSINSmove(tmp21, tmp22) ;
/*
INSletpop()
*/
/* funbodyinstrlst(end) */
ATSreturn(tmp21) ;
} /* end of [_057$home_057$hwxi_057$research_057$Postiats_057$git_057$prelude_057$SATS_057$unsafe_056$sats__ptr0_get$8] */
#endif // end of [TEMPLATE]
ATSstaticdec()
/*
imparg = a(2938)
tmparg = S2Evar(a(2938))
tmpsub = Some(a(2938) -> S2Eapp(S2Ecst(g0float_t0ype); S2Ecst(double_kind)))
*/
atstkind_t0ype(atstype_double)
_057$home_057$hwxi_057$research_057$Postiats_057$git_057$prelude_057$SATS_057$unsafe_056$sats__ptr0_get$8$1 (atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmp21$1, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp22$1, atstkind_t0ype(atstype_double)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_ptr0_get:
/*
letpush(beg)
*/
/* (*nothing*) */
/* (*nothing*) */
ATSINSload(tmp22$1, ATSderef2(ATSPMVcastfn(ptr1_of_ptr0, atstkind_type(atstype_ptrk), arg0), atstkind_t0ype(atstype_double))) ; 
/* (*nothing*) */
/*
letpush(end)
*/

ATSINSmove(tmp21$1, tmp22$1) ;
/*
INSletpop()
*/
/* funbodyinstrlst(end) */
ATSreturn(tmp21$1) ;
} /* end of [_057$home_057$hwxi_057$research_057$Postiats_057$git_057$prelude_057$SATS_057$unsafe_056$sats__ptr0_get$8$1] */
ATSstaticdec()
/*
imparg = a(2897), tk(2898)
tmparg = S2Evar(a(2897)); S2Evar(tk(2898))
tmpsub = Some(a(2897) -> S2Eapp(S2Ecst(g0float_t0ype); S2Ecst(double_kind)); tk(2898) -> S2Etkname(atstype_int))
*/
atstkind_t0ype(atstype_double)
_057$home_057$hwxi_057$research_057$Postiats_057$git_057$prelude_057$SATS_057$arrayptr_056$sats__arrayptr_get_at_gint$0$2 (atsrefarg0_type(atstkind_type(atstype_ptrk)) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmp7$2, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp8$2, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_arrayptr_get_at_gint:
/*
letpush(beg)
*/
/* (*nothing*) */
/*
letpush(end)
*/

ATSINSmove(tmp8$2, _057$home_057$hwxi_057$research_057$Postiats_057$git_057$prelude_057$SATS_057$pointer_056$sats__ptr1_add_gint$2$2(ATSPMVcastfn(arrayptr2ptr, atstkind_type(atstype_ptrk), ATSPMVrefarg0(arg0)), arg1)) ;
ATSINSmove(tmp7$2, _057$home_057$hwxi_057$research_057$Postiats_057$git_057$prelude_057$SATS_057$unsafe_056$sats__ptr0_get$8$2(tmp8$2)) ;
/*
INSletpop()
*/
/* funbodyinstrlst(end) */
ATSreturn(tmp7$2) ;
} /* end of [_057$home_057$hwxi_057$research_057$Postiats_057$git_057$prelude_057$SATS_057$arrayptr_056$sats__arrayptr_get_at_gint$0$2] */
ATSstaticdec()
/*
imparg = a(2861), tk(2862)
tmparg = S2Evar(a(2861)); S2Evar(tk(2862))
tmpsub = Some(a(2861) -> S2Eapp(S2Ecst(g0float_t0ype); S2Ecst(double_kind)); tk(2862) -> S2Etkname(atstype_int))
*/
atstkind_type(atstype_ptrk)
_057$home_057$hwxi_057$research_057$Postiats_057$git_057$prelude_057$SATS_057$pointer_056$sats__ptr1_add_gint$2$2 (atstkind_type(atstype_ptrk) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmp11$2, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp12$2, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_ptr1_add_gint:
ATSINSmove(tmp12$2, _057$home_057$hwxi_057$research_057$Postiats_057$git_057$prelude_057$SATS_057$pointer_056$sats__ptr0_add_gint$4$2(arg0, arg1)) ;
ATSINSmove(tmp11$2, ATSPMVcastfn(cast, atstkind_type(atstype_ptrk), tmp12$2)) ;
/* funbodyinstrlst(end) */
ATSreturn(tmp11$2) ;
} /* end of [_057$home_057$hwxi_057$research_057$Postiats_057$git_057$prelude_057$SATS_057$pointer_056$sats__ptr1_add_gint$2$2] */
ATSstaticdec()
/*
imparg = a(2853), tk(2854)
tmparg = S2Evar(a(2853)); S2Evar(tk(2854))
tmpsub = Some(a(2853) -> S2Eapp(S2Ecst(g0float_t0ype); S2Ecst(double_kind)); tk(2854) -> S2Etkname(atstype_int))
*/
atstkind_type(atstype_ptrk)
_057$home_057$hwxi_057$research_057$Postiats_057$git_057$prelude_057$SATS_057$pointer_056$sats__ptr0_add_gint$4$2 (atstkind_type(atstype_ptrk) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmp15$2, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp16$2, atstkind_t0ype(atstype_size)) ;
ATStmpdec(tmp17$2, atstkind_t0ype(atstype_size)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_ptr0_add_gint:
ATSINSmove(tmp17$2, atspre_g0int2uint_int_size(arg1)) ;
ATSINSmove(tmp16$2, atspre_g0uint_mul_size(tmp17$2, ATSPMVsizeof(atstkind_t0ype(atstype_double)))) ;
ATSINSmove(tmp15$2, atspre_ptr0_add_bytesize(arg0, tmp16$2)) ;
/* funbodyinstrlst(end) */
ATSreturn(tmp15$2) ;
} /* end of [_057$home_057$hwxi_057$research_057$Postiats_057$git_057$prelude_057$SATS_057$pointer_056$sats__ptr0_add_gint$4$2] */
ATSstaticdec()
/*
imparg = a(2938)
tmparg = S2Evar(a(2938))
tmpsub = Some(a(2938) -> S2Eapp(S2Ecst(g0float_t0ype); S2Ecst(double_kind)))
*/
atstkind_t0ype(atstype_double)
_057$home_057$hwxi_057$research_057$Postiats_057$git_057$prelude_057$SATS_057$unsafe_056$sats__ptr0_get$8$2 (atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmp21$2, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp22$2, atstkind_t0ype(atstype_double)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_ptr0_get:
/*
letpush(beg)
*/
/* (*nothing*) */
/* (*nothing*) */
ATSINSload(tmp22$2, ATSderef2(ATSPMVcastfn(ptr1_of_ptr0, atstkind_type(atstype_ptrk), arg0), atstkind_t0ype(atstype_double))) ; 
/* (*nothing*) */
/*
letpush(end)
*/

ATSINSmove(tmp21$2, tmp22$2) ;
/*
INSletpop()
*/
/* funbodyinstrlst(end) */
ATSreturn(tmp21$2) ;
} /* end of [_057$home_057$hwxi_057$research_057$Postiats_057$git_057$prelude_057$SATS_057$unsafe_056$sats__ptr0_get$8$2] */
ATSstaticdec()
/*
imparg = a(2897), tk(2898)
tmparg = S2Evar(a(2897)); S2Evar(tk(2898))
tmpsub = Some(a(2897) -> S2Eapp(S2Ecst(g0float_t0ype); S2Ecst(double_kind)); tk(2898) -> S2Etkname(atstype_int))
*/
atstkind_t0ype(atstype_double)
_057$home_057$hwxi_057$research_057$Postiats_057$git_057$prelude_057$SATS_057$arrayptr_056$sats__arrayptr_get_at_gint$0$3 (atsrefarg0_type(atstkind_type(atstype_ptrk)) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmp7$3, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp8$3, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_arrayptr_get_at_gint:
/*
letpush(beg)
*/
/* (*nothing*) */
/*
letpush(end)
*/

ATSINSmove(tmp8$3, _057$home_057$hwxi_057$research_057$Postiats_057$git_057$prelude_057$SATS_057$pointer_056$sats__ptr1_add_gint$2$3(ATSPMVcastfn(arrayptr2ptr, atstkind_type(atstype_ptrk), ATSPMVrefarg0(arg0)), arg1)) ;
ATSINSmove(tmp7$3, _057$home_057$hwxi_057$research_057$Postiats_057$git_057$prelude_057$SATS_057$unsafe_056$sats__ptr0_get$8$3(tmp8$3)) ;
/*
INSletpop()
*/
/* funbodyinstrlst(end) */
ATSreturn(tmp7$3) ;
} /* end of [_057$home_057$hwxi_057$research_057$Postiats_057$git_057$prelude_057$SATS_057$arrayptr_056$sats__arrayptr_get_at_gint$0$3] */
ATSstaticdec()
/*
imparg = a(2861), tk(2862)
tmparg = S2Evar(a(2861)); S2Evar(tk(2862))
tmpsub = Some(a(2861) -> S2Eapp(S2Ecst(g0float_t0ype); S2Ecst(double_kind)); tk(2862) -> S2Etkname(atstype_int))
*/
atstkind_type(atstype_ptrk)
_057$home_057$hwxi_057$research_057$Postiats_057$git_057$prelude_057$SATS_057$pointer_056$sats__ptr1_add_gint$2$3 (atstkind_type(atstype_ptrk) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmp11$3, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp12$3, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_ptr1_add_gint:
ATSINSmove(tmp12$3, _057$home_057$hwxi_057$research_057$Postiats_057$git_057$prelude_057$SATS_057$pointer_056$sats__ptr0_add_gint$4$3(arg0, arg1)) ;
ATSINSmove(tmp11$3, ATSPMVcastfn(cast, atstkind_type(atstype_ptrk), tmp12$3)) ;
/* funbodyinstrlst(end) */
ATSreturn(tmp11$3) ;
} /* end of [_057$home_057$hwxi_057$research_057$Postiats_057$git_057$prelude_057$SATS_057$pointer_056$sats__ptr1_add_gint$2$3] */
ATSstaticdec()
/*
imparg = a(2853), tk(2854)
tmparg = S2Evar(a(2853)); S2Evar(tk(2854))
tmpsub = Some(a(2853) -> S2Eapp(S2Ecst(g0float_t0ype); S2Ecst(double_kind)); tk(2854) -> S2Etkname(atstype_int))
*/
atstkind_type(atstype_ptrk)
_057$home_057$hwxi_057$research_057$Postiats_057$git_057$prelude_057$SATS_057$pointer_056$sats__ptr0_add_gint$4$3 (atstkind_type(atstype_ptrk) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmp15$3, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp16$3, atstkind_t0ype(atstype_size)) ;
ATStmpdec(tmp17$3, atstkind_t0ype(atstype_size)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_ptr0_add_gint:
ATSINSmove(tmp17$3, atspre_g0int2uint_int_size(arg1)) ;
ATSINSmove(tmp16$3, atspre_g0uint_mul_size(tmp17$3, ATSPMVsizeof(atstkind_t0ype(atstype_double)))) ;
ATSINSmove(tmp15$3, atspre_ptr0_add_bytesize(arg0, tmp16$3)) ;
/* funbodyinstrlst(end) */
ATSreturn(tmp15$3) ;
} /* end of [_057$home_057$hwxi_057$research_057$Postiats_057$git_057$prelude_057$SATS_057$pointer_056$sats__ptr0_add_gint$4$3] */
ATSstaticdec()
/*
imparg = a(2938)
tmparg = S2Evar(a(2938))
tmpsub = Some(a(2938) -> S2Eapp(S2Ecst(g0float_t0ype); S2Ecst(double_kind)))
*/
atstkind_t0ype(atstype_double)
_057$home_057$hwxi_057$research_057$Postiats_057$git_057$prelude_057$SATS_057$unsafe_056$sats__ptr0_get$8$3 (atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmp21$3, atstkind_t0ype(atstype_double)) ;
ATStmpdec(tmp22$3, atstkind_t0ype(atstype_double)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_ptr0_get:
/*
letpush(beg)
*/
/* (*nothing*) */
/* (*nothing*) */
ATSINSload(tmp22$3, ATSderef2(ATSPMVcastfn(ptr1_of_ptr0, atstkind_type(atstype_ptrk), arg0), atstkind_t0ype(atstype_double))) ; 
/* (*nothing*) */
/*
letpush(end)
*/

ATSINSmove(tmp21$3, tmp22$3) ;
/*
INSletpop()
*/
/* funbodyinstrlst(end) */
ATSreturn(tmp21$3) ;
} /* end of [_057$home_057$hwxi_057$research_057$Postiats_057$git_057$prelude_057$SATS_057$unsafe_056$sats__ptr0_get$8$3] */
/*
** declaration initialization
*/
int main () {
/*
ATSINStmpdec(tmp0)) ;
*/
ATSINSstore_arrpsz_asz(tmp0, 3) ;
ATSINSstore_arrpsz_ptr(tmp0, atstkind_t0ype(atstype_double), 3) ;
ATSINSmove_arrpsz_ptr(tmp1, tmp0) ;
ATSINSpmove(tmp1, atstkind_t0ype(atstype_double), ATSPMVf0loat(1.0)) ;
ATSINSupdate_ptrinc(tmp1, atstkind_t0ype(atstype_double)) ;
ATSINSpmove(tmp1, atstkind_t0ype(atstype_double), ATSPMVf0loat(2.0)) ;
ATSINSupdate_ptrinc(tmp1, atstkind_t0ype(atstype_double)) ;
ATSINSpmove(tmp1, atstkind_t0ype(atstype_double), ATSPMVf0loat(3.0)) ;
/*
ATSINStmpdec(tmp2)) ;
*/
ATSINSmove(tmp3, atspre_arrpsz_get_ptrsize(tmp0, ATSPMVrefarg1(ATSPMVptrof(tmp2)))) ;  // tmp3 holds the ptr to the array
ATSINSmove_void(tmp4, atspre_print_string(ATSPMVstring("A[0] = "))) ;
ATSINSmove(tmp6, _057$home_057$hwxi_057$research_057$Postiats_057$git_057$prelude_057$SATS_057$arrayptr_056$sats__arrayptr_get_at_gint$0$1(ATSPMVrefarg0(tmp3), ATSPMVi0nt(0))) ;
ATSINSmove_void(tmp5, atspre_print_double(tmp6)) ;
ATSINSmove_void(tmp25, atspre_print_newline()) ;
ATSINSmove_void(tmp26, atspre_print_string(ATSPMVstring("A[1] = "))) ;
ATSINSmove(tmp28, _057$home_057$hwxi_057$research_057$Postiats_057$git_057$prelude_057$SATS_057$arrayptr_056$sats__arrayptr_get_at_gint$0$2(ATSPMVrefarg0(tmp3), ATSPMVi0nt(1))) ;
ATSINSmove_void(tmp27, atspre_print_double(tmp28)) ;
ATSINSmove_void(tmp38, atspre_print_newline()) ;
ATSINSmove_void(tmp39, atspre_print_string(ATSPMVstring("A[2] = "))) ;
ATSINSmove(tmp41, _057$home_057$hwxi_057$research_057$Postiats_057$git_057$prelude_057$SATS_057$arrayptr_056$sats__arrayptr_get_at_gint$0$3(ATSPMVrefarg0(tmp3), ATSPMVi0nt(2))) ;
ATSINSmove_void(tmp40, atspre_print_double(tmp41)) ;
ATSINSmove_void(tmp51, atspre_print_newline()) ;
ATSreturn(0) ;
}
