/*
**
** The C code is generated by ATS/Postiats
** The compilation time is: 2013-5-2: 18h:24m
**
*/

/*
** include runtime header files
*/
#ifndef _ATS_CCOMP_HEADER_NONE
#include "pats_ccomp_config.h"
#include "pats_ccomp_basics.h"
#include "pats_ccomp_typedefs.h"
#include "pats_ccomp_instrset.h"
#include "pats_ccomp_exception.h"
#include "pats_ccomp_memalloc.h"
#include "pats_ccomp_memalloca.h"
#endif /* _ATS_CCOMP_HEADER_NONE */


/*
** include prelude cats files
*/
#ifndef _ATS_CCOMP_PRELUDE_NONE
//
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/memory.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/strptr.cats"
//
#include "prelude/CATS/filebas.cats"
//
#include "prelude/CATS/list.cats"
#include "prelude/CATS/option.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/arrayptr.cats"
#include "prelude/CATS/arrayref.cats"
#include "prelude/CATS/matrix.cats"
#include "prelude/CATS/matrixptr.cats"
//
#endif /* _ATS_CCOMP_PRELUDE_NONE */

/*
staload-prologues(beg)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/integer.dats: 25237(line=637, offs=1) -- 25268(line=637, offs=32)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/libc/SATS/stdlib.sats: 1379(line=35, offs=1) -- 1418(line=37, offs=3)
*/

#include "libc/CATS/stdlib.cats"
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/libc/SATS/stdlib.sats: 1814(line=54, offs=1) -- 1854(line=55, offs=33)
*/
/*
staload-prologues(end)
*/
/*
typedefs-for-tyrecs-and-tysums(beg)
*/
/*
typedefs-for-tyrecs-and-tysums(end)
*/
/*
dyncstlst-declaration(beg)
*/
/*
dyncstlst-declaration(end)
*/
ATSstaticdec()
atstkind_t0ype(atstype_int)
foo2_0(atstkind_t0ype(atstype_int)) ;

#if(0)
#if(0)
ATSglobaldec()
atstkind_t0ype(atstype_bool)
_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$ATS_055$Postiats_057$prelude_057$SATS_057$integer_056$sats_gt_g0int_int$2(atstkind_t0ype(atstyvar_type(tk)), atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstaticdec()
atstkind_t0ype(atstype_bool)
_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$ATS_055$Postiats_057$prelude_057$SATS_057$integer_056$sats_gt_g0int_int$2$1(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

#if(0)
ATSglobaldec()
atsvoid_t0ype
mainats_void_0() ;
#endif // end of [QUALIFIED]

/*
/home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/test17.dats: 47(line=8, offs=5) -- 69(line=8, offs=27)
*/
/*
local: 
global: foo2_0$0(0)
local: 
global: 
*/
ATSstaticdec()
atstkind_t0ype(atstype_int)
foo2_0(atstkind_t0ype(atstype_int) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret0, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_foo2_0:
ATSINSmove(tmpret0, arg0) ;
/* funbodyinstrlst(end) */
ATSreturn(tmpret0) ;
} /* end of [foo2_0] */

#if(0)
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/integer.dats: 26382(line=682, offs=14) -- 26422(line=682, offs=54)
*/
/*
local: 
global: gt_g0int_int$2$0(0)
local: 
global: 
*/
ATSglobaldec()
/*
imparg = tk(2905)
tmparg = S2Evar(tk(2905))
tmpsub = None()
*/
atstkind_t0ype(atstype_bool)
_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$ATS_055$Postiats_057$prelude_057$SATS_057$integer_056$sats_gt_g0int_int$2(atstkind_t0ype(atstyvar_type(tk)) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret4, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp5, atstkind_t0ype(atstyvar_type(tk))) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_gt_g0int_int:
ATSINSmove(tmp5, PMVtmpltcst(g0int2int<S2EVar(369->S2Eextkind(atstype_int)), S2EVar(370->S2Evar(tk(2905)))>)(arg1)) ;
ATSINSmove(tmpret4, PMVtmpltcst(g0int_gt<S2Evar(tk(2905))>)(arg0, tmp5)) ;
/* funbodyinstrlst(end) */
ATSreturn(tmpret4) ;
} /* end of [_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$ATS_055$Postiats_057$prelude_057$SATS_057$integer_056$sats_gt_g0int_int$2] */
#endif // end of [TEMPLATE]

/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/integer.dats: 26382(line=682, offs=14) -- 26422(line=682, offs=54)
*/
/*
local: 
global: gt_g0int_int$2$1(1)
local: 
global: 
*/
ATSstaticdec()
/*
imparg = tk(2905)
tmparg = S2Evar(tk(2905))
tmpsub = Some(tk(2905) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$ATS_055$Postiats_057$prelude_057$SATS_057$integer_056$sats_gt_g0int_int$2$1(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmp4$1, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp5$1, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_gt_g0int_int:
ATSINSmove(tmp5$1, atspre_g0int2int_int_int(arg1)) ;
ATSINSmove(tmp4$1, atspre_g0int_gt_int(arg0, tmp5$1)) ;
/* funbodyinstrlst(end) */
ATSreturn(tmp4$1) ;
} /* end of [_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$ATS_055$Postiats_057$prelude_057$SATS_057$integer_056$sats_gt_g0int_int$2$1] */

/*
/home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/test17.dats: 87(line=10, offs=17) -- 150(line=14, offs=4)
*/
/*
local: foo2_0$0(0)
global: foo2_0$0(0), mainats_void_0$1$0(0)
local: 
global: 
*/
ATSglobaldec()
atsvoid_t0ype
mainats_void_0()
{
/* tmpvardeclst(beg) */
ATStmpdec_void(tmpret1, atsvoid_t0ype) ;
ATStmpdec(tmp2, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp3, atstkind_t0ype(atstype_bool)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_main_void_0:
/*
letpush(beg)
*/
ATSINSmove(tmp2, foo2_0(ATSPMVi0nt(3))) ;
/*
letpush(end)
*/

ATSINSmove(tmp3, _057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$ATS_055$Postiats_057$prelude_057$SATS_057$integer_056$sats_gt_g0int_int$2$1(tmp2, ATSPMVi0nt(3))) ;
ATSif(
tmp3
) ATSthen() {
ATSINSmove_void(tmpret1, ATSempty()) ;
} ATSelse() {
ATSINSmove_void(tmpret1, ATSempty()) ;
} /* ATSendif */
/*
INSletpop()
*/
/* funbodyinstrlst(end) */
ATSreturn_void(tmpret1) ;
} /* end of [mainats_void_0] */


/*
** for initialization(dynloading)
*/
atsvoid_t0ype
_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$projects_057$org_056$ats_055$lang_056$postiats_056$jats_057$test_057$test17_056$dats__dynload()
{
ATSdynload0(
_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$projects_057$org_056$ats_055$lang_056$postiats_056$jats_057$test_057$test17_056$dats__dynloadflag
) ;
ATSif(
ATSCKiseqz(
_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$projects_057$org_056$ats_055$lang_056$postiats_056$jats_057$test_057$test17_056$dats__dynloadflag
)
) ATSthen() {
ATSdynloadset(_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$projects_057$org_056$ats_055$lang_056$postiats_056$jats_057$test_057$test17_056$dats__dynloadflag) ;
} /* ATSendif */
ATSreturn_void() ;
} /* end of [*_dynload] */

/*
** the ATS runtime
*/
#ifndef _ATS_CCOMP_RUNTIME_NONE
#include "pats_ccomp_runtime.c"
#endif /* _ATS_CCOMP_RUNTIME_NONE */

/*
** the [main] implementation
*/
int
main
(
int argc, char **argv, char **envp
) {
int err = 0 ;
_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$projects_057$org_056$ats_055$lang_056$postiats_056$jats_057$test_057$test17_056$dats__dynload() ;
ATSmainats_void_0(err) ;
return (err) ;
} /* end of [main] */
