/*
**
** The C code is generated by ATS/Postiats
** The compilation time is: 2013-5-2: 18h:24m
**
*/

/*
** include runtime header files
*/
#ifndef _ATS_CCOMP_HEADER_NONE
#include "pats_ccomp_config.h"
#include "pats_ccomp_basics.h"
#include "pats_ccomp_typedefs.h"
#include "pats_ccomp_instrset.h"
#include "pats_ccomp_exception.h"
#include "pats_ccomp_memalloc.h"
#include "pats_ccomp_memalloca.h"
#endif /* _ATS_CCOMP_HEADER_NONE */


/*
** include prelude cats files
*/
#ifndef _ATS_CCOMP_PRELUDE_NONE
//
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/memory.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/strptr.cats"
//
#include "prelude/CATS/filebas.cats"
//
#include "prelude/CATS/list.cats"
#include "prelude/CATS/option.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/arrayptr.cats"
#include "prelude/CATS/arrayref.cats"
#include "prelude/CATS/matrix.cats"
#include "prelude/CATS/matrixptr.cats"
//
#endif /* _ATS_CCOMP_PRELUDE_NONE */

/*
staload-prologues(beg)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/integer.dats: 25237(line=637, offs=1) -- 25268(line=637, offs=32)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/libc/SATS/stdlib.sats: 1379(line=35, offs=1) -- 1418(line=37, offs=3)
*/

#include "libc/CATS/stdlib.cats"
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/libc/SATS/stdlib.sats: 1814(line=54, offs=1) -- 1854(line=55, offs=33)
*/
/*
staload-prologues(end)
*/
/*
typedefs-for-tyrecs-and-tysums(beg)
*/
typedef
struct {
atstkind_t0ype(atstype_int) atslab$0; 
atstkind_t0ype(atstype_double) atslab$1; 
} postiats_tyrec_0 ;
typedef
struct {
atstkind_t0ype(atstype_int) atslab$0; 
atstkind_type(atstype_ptrk) atslab$1; 
} postiats_tyrec_1 ;
typedef
struct {
atstkind_t0ype(atstype_int) atslab$0; 
atstkind_t0ype(atstype_int) atslab$1; 
} postiats_tyrec_2 ;
typedef
struct {
atstkind_t0ype(atstype_int) atslab$0; 
atstkind_t0ype(atstype_char) atslab$1; 
} postiats_tyrec_3 ;
/*
typedefs-for-tyrecs-and-tysums(end)
*/
/*
dyncstlst-declaration(beg)
*/
ATSdyncst_mac(atspre_print_string) ;
ATSdyncst_mac(atspre_print_int) ;
ATSdyncst_mac(atspre_print_newline) ;
ATSdyncst_mac(atspre_assert_errmsg_bool1) ;
ATSdyncst_mac(atspre_assert_errmsg_bool0) ;
ATSdyncst_mac(atspre_eq_string_string) ;
/*
dyncstlst-declaration(end)
*/
ATSstaticdec()
atsvoid_t0ype
foo_bt_val_0(atstype_boxed) ;

ATSstaticdec()
atsvoid_t0ype
foo_ft_val_1(postiats_tyrec_0) ;

ATSstaticdec()
atsvoid_t0ype
foo_bt_var_2(atsrefarg1_type(atstype_boxed)) ;

ATSstaticdec()
atsvoid_t0ype
foo_ft_var_3(atsrefarg1_type(postiats_tyrec_1)) ;

ATSstaticdec()
atstkind_t0ype(atstype_int)
foo_int_4() ;

#if(0)
#if(0)
ATSglobaldec()
atstkind_t0ype(atstype_bool)
_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$ATS_055$Postiats_057$prelude_057$SATS_057$integer_056$sats_eq_g1int_int$7(atstkind_t0ype(atstyvar_type(tk)), atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstaticdec()
atstkind_t0ype(atstype_bool)
_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$ATS_055$Postiats_057$prelude_057$SATS_057$integer_056$sats_eq_g1int_int$7$1(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

#if(0)
#if(0)
ATSglobaldec()
atstkind_t0ype(atstype_bool)
_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$ATS_055$Postiats_057$prelude_057$SATS_057$integer_056$sats_eq_g0int_int$11(atstkind_t0ype(atstyvar_type(tk)), atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstaticdec()
atstkind_t0ype(atstype_bool)
_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$ATS_055$Postiats_057$prelude_057$SATS_057$integer_056$sats_eq_g0int_int$11$1(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

ATSstaticdec()
atstkind_t0ype(atstype_bool)
_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$ATS_055$Postiats_057$prelude_057$SATS_057$integer_056$sats_eq_g1int_int$7$2(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

ATSstaticdec()
atstkind_t0ype(atstype_bool)
_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$ATS_055$Postiats_057$prelude_057$SATS_057$integer_056$sats_eq_g0int_int$11$2(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

#if(0)
ATSglobaldec()
atsvoid_t0ype
mainats_void_0() ;
#endif // end of [QUALIFIED]

/*
/home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/test01.dats: 45(line=6, offs=5) -- 128(line=9, offs=4)
*/
/*
local: 
global: foo_bt_val_0$0(0)
local: 
global: 
*/
ATSstaticdec()
atsvoid_t0ype
foo_bt_val_0(atstype_boxed arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec_void(tmpret0, atsvoid_t0ype) ;
ATStmpdec_void(tmp1, atsvoid_t0ype) ;
ATStmpdec_void(tmp2, atsvoid_t0ype) ;
ATStmpdec_void(tmp3, atsvoid_t0ype) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_foo_bt_val_0:
/*
letpush(beg)
*/
ATSINSmove_void(tmp1, atspre_print_string(ATSPMVstring("int is "))) ;
ATSINSmove_void(tmp2, atspre_print_int(ATSselboxrec(arg0, postiats_tyrec_2, atslab$0))) ;
ATSINSmove_void(tmp3, atspre_print_newline()) ;
/*
letpush(end)
*/

ATSINSmove_void(tmpret0, ATSempty()) ;
/*
INSletpop()
*/
/* funbodyinstrlst(end) */
ATSreturn_void(tmpret0) ;
} /* end of [foo_bt_val_0] */

/*
/home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/test01.dats: 134(line=11, offs=5) -- 220(line=14, offs=4)
*/
/*
local: 
global: foo_ft_val_1$0(0)
local: 
global: 
*/
ATSstaticdec()
atsvoid_t0ype
foo_ft_val_1(postiats_tyrec_0 arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec_void(tmpret4, atsvoid_t0ype) ;
ATStmpdec_void(tmp5, atsvoid_t0ype) ;
ATStmpdec_void(tmp6, atsvoid_t0ype) ;
ATStmpdec_void(tmp7, atsvoid_t0ype) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_foo_ft_val_1:
/*
letpush(beg)
*/
ATSINSmove_void(tmp5, atspre_print_string(ATSPMVstring("int is "))) ;
ATSINSmove_void(tmp6, atspre_print_int(ATSselfltrec(arg0, postiats_tyrec_0, atslab$0))) ;
ATSINSmove_void(tmp7, atspre_print_newline()) ;
/*
letpush(end)
*/

ATSINSmove_void(tmpret4, ATSempty()) ;
/*
INSletpop()
*/
/* funbodyinstrlst(end) */
ATSreturn_void(tmpret4) ;
} /* end of [foo_ft_val_1] */

/*
/home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/test01.dats: 226(line=16, offs=5) -- 335(line=20, offs=4)
*/
/*
local: 
global: foo_bt_var_2$0(0)
local: 
global: 
*/
ATSstaticdec()
atsvoid_t0ype
foo_bt_var_2(atsrefarg1_type(atstype_boxed) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec_void(tmpret8, atsvoid_t0ype) ;
ATStmpdec(tmp9, atstype_boxed) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_foo_bt_var_2:
/*
letpush(beg)
*/
ATSINSmove_boxrec(tmp9, postiats_tyrec_3) ;
ATSINSstore_boxrec_ofs (tmp9, postiats_tyrec_3, atslab$0, ATSPMVi0nt(52)) ;
ATSINSstore_boxrec_ofs (tmp9, postiats_tyrec_3, atslab$1, ATSPMVchar('c')) ;
ATSINSstore(ATSderef(arg0, atstype_boxed), tmp9) ;
/*
letpush(end)
*/

ATSINSmove_void(tmpret8, ATSempty()) ;
/*
INSletpop()
*/
/* funbodyinstrlst(end) */
ATSreturn_void(tmpret8) ;
} /* end of [foo_bt_var_2] */

/*
/home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/test01.dats: 341(line=22, offs=5) -- 445(line=26, offs=4)
*/
/*
local: 
global: foo_ft_var_3$0(0)
local: 
global: 
*/
ATSstaticdec()
atsvoid_t0ype
foo_ft_var_3(atsrefarg1_type(postiats_tyrec_1) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec_void(tmpret10, atsvoid_t0ype) ;
ATStmpdec(tmp11, postiats_tyrec_1) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_foo_ft_var_3:
/*
letpush(beg)
*/
ATSINSstore_fltrec_ofs (tmp11, postiats_tyrec_1, atslab$0, ATSPMVi0nt(72)) ;
ATSINSstore_fltrec_ofs (tmp11, postiats_tyrec_1, atslab$1, ATSPMVstring("cde")) ;
ATSINSstore(ATSderef(arg0, postiats_tyrec_1), tmp11) ;
ATSINSstore(ATSselfltrec(ATSderef(arg0, postiats_tyrec_1), postiats_tyrec_1, atslab$1), ATSPMVstring("def")) ;
/*
letpush(end)
*/

ATSINSmove_void(tmpret10, ATSempty()) ;
/*
INSletpop()
*/
/* funbodyinstrlst(end) */
ATSreturn_void(tmpret10) ;
} /* end of [foo_ft_var_3] */

/*
/home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/test01.dats: 451(line=28, offs=5) -- 470(line=28, offs=24)
*/
/*
local: 
global: foo_int_4$0(0)
local: 
global: 
*/
ATSstaticdec()
atstkind_t0ype(atstype_int)
foo_int_4()
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret12, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_foo_int_4:
ATSINSmove(tmpret12, ATSPMVi0nt(3)) ;
/* funbodyinstrlst(end) */
ATSreturn(tmpret12) ;
} /* end of [foo_int_4] */

#if(0)
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/integer.dats: 27035(line=704, offs=14) -- 27075(line=704, offs=54)
*/
/*
local: 
global: eq_g1int_int$7$0(0)
local: 
global: 
*/
ATSglobaldec()
/*
imparg = tk(2922)
tmparg = S2Evar(tk(2922))
tmpsub = None()
*/
atstkind_t0ype(atstype_bool)
_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$ATS_055$Postiats_057$prelude_057$SATS_057$integer_056$sats_eq_g1int_int$7(atstkind_t0ype(atstyvar_type(tk)) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret29, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp30, atstkind_t0ype(atstyvar_type(tk))) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_eq_g1int_int:
ATSINSmove(tmp30, PMVtmpltcst(g1int2int<S2EVar(399->S2Eextkind(atstype_int)), S2EVar(400->S2Evar(tk(2922)))>)(arg1)) ;
ATSINSmove(tmpret29, PMVtmpltcst(g1int_eq<S2Evar(tk(2922))>)(arg0, tmp30)) ;
/* funbodyinstrlst(end) */
ATSreturn(tmpret29) ;
} /* end of [_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$ATS_055$Postiats_057$prelude_057$SATS_057$integer_056$sats_eq_g1int_int$7] */
#endif // end of [TEMPLATE]

/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/integer.dats: 27035(line=704, offs=14) -- 27075(line=704, offs=54)
*/
/*
local: 
global: eq_g1int_int$7$1(1)
local: 
global: 
*/
ATSstaticdec()
/*
imparg = tk(2922)
tmparg = S2Evar(tk(2922))
tmpsub = Some(tk(2922) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$ATS_055$Postiats_057$prelude_057$SATS_057$integer_056$sats_eq_g1int_int$7$1(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmp29$1, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp30$1, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_eq_g1int_int:
ATSINSmove(tmp30$1, atspre_g1int2int_int_int(arg1)) ;
ATSINSmove(tmp29$1, atspre_g1int_eq_int(arg0, tmp30$1)) ;
/* funbodyinstrlst(end) */
ATSreturn(tmp29$1) ;
} /* end of [_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$ATS_055$Postiats_057$prelude_057$SATS_057$integer_056$sats_eq_g1int_int$7$1] */

#if(0)
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/integer.dats: 26520(line=686, offs=14) -- 26560(line=686, offs=54)
*/
/*
local: 
global: eq_g0int_int$11$0(0)
local: 
global: 
*/
ATSglobaldec()
/*
imparg = tk(2907)
tmparg = S2Evar(tk(2907))
tmpsub = None()
*/
atstkind_t0ype(atstype_bool)
_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$ATS_055$Postiats_057$prelude_057$SATS_057$integer_056$sats_eq_g0int_int$11(atstkind_t0ype(atstyvar_type(tk)) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret36, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp37, atstkind_t0ype(atstyvar_type(tk))) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_eq_g0int_int:
ATSINSmove(tmp37, PMVtmpltcst(g0int2int<S2EVar(373->S2Eextkind(atstype_int)), S2EVar(374->S2Evar(tk(2907)))>)(arg1)) ;
ATSINSmove(tmpret36, PMVtmpltcst(g0int_eq<S2Evar(tk(2907))>)(arg0, tmp37)) ;
/* funbodyinstrlst(end) */
ATSreturn(tmpret36) ;
} /* end of [_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$ATS_055$Postiats_057$prelude_057$SATS_057$integer_056$sats_eq_g0int_int$11] */
#endif // end of [TEMPLATE]

/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/integer.dats: 26520(line=686, offs=14) -- 26560(line=686, offs=54)
*/
/*
local: 
global: eq_g0int_int$11$1(1)
local: 
global: 
*/
ATSstaticdec()
/*
imparg = tk(2907)
tmparg = S2Evar(tk(2907))
tmpsub = Some(tk(2907) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$ATS_055$Postiats_057$prelude_057$SATS_057$integer_056$sats_eq_g0int_int$11$1(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmp36$1, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp37$1, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_eq_g0int_int:
ATSINSmove(tmp37$1, atspre_g0int2int_int_int(arg1)) ;
ATSINSmove(tmp36$1, atspre_g0int_eq_int(arg0, tmp37$1)) ;
/* funbodyinstrlst(end) */
ATSreturn(tmp36$1) ;
} /* end of [_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$ATS_055$Postiats_057$prelude_057$SATS_057$integer_056$sats_eq_g0int_int$11$1] */

/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/integer.dats: 27035(line=704, offs=14) -- 27075(line=704, offs=54)
*/
/*
local: 
global: eq_g1int_int$7$2(1)
local: 
global: 
*/
ATSstaticdec()
/*
imparg = tk(2922)
tmparg = S2Evar(tk(2922))
tmpsub = Some(tk(2922) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$ATS_055$Postiats_057$prelude_057$SATS_057$integer_056$sats_eq_g1int_int$7$2(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmp29$2, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp30$2, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_eq_g1int_int:
ATSINSmove(tmp30$2, atspre_g1int2int_int_int(arg1)) ;
ATSINSmove(tmp29$2, atspre_g1int_eq_int(arg0, tmp30$2)) ;
/* funbodyinstrlst(end) */
ATSreturn(tmp29$2) ;
} /* end of [_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$ATS_055$Postiats_057$prelude_057$SATS_057$integer_056$sats_eq_g1int_int$7$2] */

/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/integer.dats: 26520(line=686, offs=14) -- 26560(line=686, offs=54)
*/
/*
local: 
global: eq_g0int_int$11$2(1)
local: 
global: 
*/
ATSstaticdec()
/*
imparg = tk(2907)
tmparg = S2Evar(tk(2907))
tmpsub = Some(tk(2907) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$ATS_055$Postiats_057$prelude_057$SATS_057$integer_056$sats_eq_g0int_int$11$2(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmp36$2, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp37$2, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_eq_g0int_int:
ATSINSmove(tmp37$2, atspre_g0int2int_int_int(arg1)) ;
ATSINSmove(tmp36$2, atspre_g0int_eq_int(arg0, tmp37$2)) ;
/* funbodyinstrlst(end) */
ATSreturn(tmp36$2) ;
} /* end of [_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$ATS_055$Postiats_057$prelude_057$SATS_057$integer_056$sats_eq_g0int_int$11$2] */

/*
/home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/test01.dats: 488(line=30, offs=17) -- 1465(line=75, offs=4)
*/
/*
local: foo_bt_val_0$0(0), foo_ft_val_1$0(0), foo_bt_var_2$0(0), foo_ft_var_3$0(0), foo_int_4$0(0)
global: foo_bt_val_0$0(0), foo_ft_val_1$0(0), foo_bt_var_2$0(0), foo_ft_var_3$0(0), foo_int_4$0(0), mainats_void_0$5$0(0)
local: 
global: 
*/
ATSglobaldec()
atsvoid_t0ype
mainats_void_0()
{
/* tmpvardeclst(beg) */
ATStmpdec_void(tmpret13, atsvoid_t0ype) ;
ATStmpdec(tmp14, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp15, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmpref16, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmpref17, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp18, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp19, atstype_boxed) ;
ATStmpdec(tmp20, atstype_boxed) ;
ATStmpdec_void(tmp21, atsvoid_t0ype) ;
ATStmpdec(tmp22, postiats_tyrec_0) ;
ATStmpdec(tmp23, postiats_tyrec_0) ;
ATStmpdec_void(tmp24, atsvoid_t0ype) ;
ATStmpdec(tmpref25, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp26, atstype_boxed) ;
ATStmpdec_void(tmp27, atsvoid_t0ype) ;
ATStmpdec(tmp28, atstkind_t0ype(atstype_bool)) ;
ATStmpdec_void(tmp33, atsvoid_t0ype) ;
ATStmpdec_void(tmp34, atsvoid_t0ype) ;
ATStmpdec(tmp35, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmpref40, postiats_tyrec_1) ;
ATStmpdec_void(tmp41, atsvoid_t0ype) ;
ATStmpdec(tmp42, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp45, postiats_tyrec_1) ;
ATStmpdec_void(tmp46, atsvoid_t0ype) ;
ATStmpdec(tmp47, atstkind_t0ype(atstype_bool)) ;
ATStmpdec_void(tmp48, atsvoid_t0ype) ;
ATStmpdec_void(tmp49, atsvoid_t0ype) ;
ATStmpdec(tmp50, atstkind_t0ype(atstype_bool)) ;
ATStmpdec_void(tmp53, atsvoid_t0ype) ;
ATStmpdec(tmp54, atstkind_t0ype(atstype_bool)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_main_void_0:
/*
letpush(beg)
*/
ATSINSmove(tmp14, foo_int_4()) ;
ATSINSmove(tmp15, atspre_g0int_add_int(tmp14, ATSPMVi0nt(1))) ;
/*
ATSINStmpdec(tmpref16)) ;
*/
ATSINSmove(tmpref16, foo_int_4()) ;
/*
ATSINStmpdec(tmpref17)) ;
*/
ATSINSmove(tmpref17, atspre_g0int_add_int(tmpref16, ATSPMVi0nt(1))) ;
ATSINSmove(tmp18, atspre_g0int_add_int(tmpref17, ATSPMVi0nt(2))) ;
ATSINSstore(tmpref17, tmp18) ;
ATSINSmove_boxrec(tmp19, postiats_tyrec_2) ;
ATSINSstore_boxrec_ofs (tmp19, postiats_tyrec_2, atslab$0, ATSPMVi0nt(0)) ;
ATSINSstore_boxrec_ofs (tmp19, postiats_tyrec_2, atslab$1, ATSPMVi0nt(1)) ;
ATSINSmove_boxrec(tmp20, postiats_tyrec_2) ;
ATSINSstore_boxrec_ofs (tmp20, postiats_tyrec_2, atslab$0, ATSPMVi0nt(1)) ;
ATSINSstore_boxrec_ofs (tmp20, postiats_tyrec_2, atslab$1, ATSPMVi0nt(2)) ;
ATSINSmove_void(tmp21, foo_bt_val_0(tmp20)) ;
ATSINSstore_fltrec_ofs (tmp22, postiats_tyrec_0, atslab$0, ATSPMVi0nt(2)) ;
ATSINSstore_fltrec_ofs (tmp22, postiats_tyrec_0, atslab$1, ATSPMVf0loat(0.1)) ;
ATSINSstore_fltrec_ofs (tmp23, postiats_tyrec_0, atslab$0, ATSPMVi0nt(3)) ;
ATSINSstore_fltrec_ofs (tmp23, postiats_tyrec_0, atslab$1, ATSPMVf0loat(1.2)) ;
ATSINSmove_void(tmp24, foo_ft_val_1(tmp23)) ;
/*
ATSINStmpdec(tmpref25)) ;
*/
ATSINSmove_boxrec(tmpref25, postiats_tyrec_3) ;
ATSINSstore_boxrec_ofs (tmpref25, postiats_tyrec_3, atslab$0, ATSPMVi0nt(5)) ;
ATSINSstore_boxrec_ofs (tmpref25, postiats_tyrec_3, atslab$1, ATSPMVchar('a')) ;
ATSINSmove_boxrec(tmp26, postiats_tyrec_3) ;
ATSINSstore_boxrec_ofs (tmp26, postiats_tyrec_3, atslab$0, ATSPMVi0nt(51)) ;
ATSINSstore_boxrec_ofs (tmp26, postiats_tyrec_3, atslab$1, ATSPMVchar('b')) ;
ATSINSstore(tmpref25, tmp26) ;
ATSINSmove(tmp28, _057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$ATS_055$Postiats_057$prelude_057$SATS_057$integer_056$sats_eq_g1int_int$7$1(ATSselboxrec(tmpref25, postiats_tyrec_3, atslab$0), ATSPMVi0nt(51))) ;
ATSINSmove_void(tmp27, atspre_assert_errmsg_bool1(tmp28, ATSCSTSPmyloc("/home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/test01.dats: 894(line=53, offs=12) -- 920(line=53, offs=38)"))) ;
ATSINSmove_void(tmp33, foo_bt_var_2(ATSPMVrefarg1(ATSPMVptrof(tmpref25)))) ;
ATSINSmove(tmp35, _057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$ATS_055$Postiats_057$prelude_057$SATS_057$integer_056$sats_eq_g0int_int$11$1(ATSselboxrec(tmpref25, postiats_tyrec_3, atslab$0), ATSPMVi0nt(52))) ;
ATSINSmove_void(tmp34, atspre_assert_errmsg_bool0(tmp35, ATSCSTSPmyloc("/home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/test01.dats: 1007(line=57, offs=12) -- 1033(line=57, offs=38)"))) ;
/*
ATSINStmpdec(tmpref40)) ;
*/
ATSINSstore_fltrec_ofs (tmpref40, postiats_tyrec_1, atslab$0, ATSPMVi0nt(7)) ;
ATSINSstore_fltrec_ofs (tmpref40, postiats_tyrec_1, atslab$1, ATSPMVstring("abc")) ;
ATSINSstore(ATSselfltrec(tmpref40, postiats_tyrec_1, atslab$0), ATSPMVi0nt(70)) ;
ATSINSmove(tmp42, _057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$ATS_055$Postiats_057$prelude_057$SATS_057$integer_056$sats_eq_g1int_int$7$2(ATSselfltrec(tmpref40, postiats_tyrec_1, atslab$0), ATSPMVi0nt(70))) ;
ATSINSmove_void(tmp41, atspre_assert_errmsg_bool1(tmp42, ATSCSTSPmyloc("/home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/test01.dats: 1144(line=62, offs=12) -- 1170(line=62, offs=38)"))) ;
ATSINSstore_fltrec_ofs (tmp45, postiats_tyrec_1, atslab$0, ATSPMVi0nt(71)) ;
ATSINSstore_fltrec_ofs (tmp45, postiats_tyrec_1, atslab$1, ATSPMVstring("bcd")) ;
ATSINSstore(tmpref40, tmp45) ;
ATSINSmove(tmp47, atspre_eq_string_string(ATSselfltrec(tmpref40, postiats_tyrec_1, atslab$1), ATSPMVstring("bcd"))) ;
ATSINSmove_void(tmp46, atspre_assert_errmsg_bool0(tmp47, ATSCSTSPmyloc("/home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/test01.dats: 1222(line=65, offs=13) -- 1251(line=65, offs=42)"))) ;
ATSINSmove_void(tmp48, foo_ft_var_3(ATSPMVrefarg1(ATSPMVptrof(tmpref40)))) ;
ATSINSmove(tmp50, _057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$ATS_055$Postiats_057$prelude_057$SATS_057$integer_056$sats_eq_g0int_int$11$2(ATSselfltrec(tmpref40, postiats_tyrec_1, atslab$0), ATSPMVi0nt(72))) ;
ATSINSmove_void(tmp49, atspre_assert_errmsg_bool0(tmp50, ATSCSTSPmyloc("/home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/test01.dats: 1303(line=68, offs=13) -- 1329(line=68, offs=39)"))) ;
ATSINSmove(tmp54, atspre_eq_string_string(ATSselfltrec(tmpref40, postiats_tyrec_1, atslab$1), ATSPMVstring("def"))) ;
ATSINSmove_void(tmp53, atspre_assert_errmsg_bool0(tmp54, ATSCSTSPmyloc("/home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/test01.dats: 1343(line=69, offs=13) -- 1372(line=69, offs=42)"))) ;
/*
letpush(end)
*/

ATSINSmove_void(tmpret13, ATSempty()) ;
/*
INSletpop()
*/
/* funbodyinstrlst(end) */
ATSreturn_void(tmpret13) ;
} /* end of [mainats_void_0] */


/*
** for initialization(dynloading)
*/
atsvoid_t0ype
_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$projects_057$org_056$ats_055$lang_056$postiats_056$jats_057$test_057$test01_056$dats__dynload()
{
ATSdynload0(
_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$projects_057$org_056$ats_055$lang_056$postiats_056$jats_057$test_057$test01_056$dats__dynloadflag
) ;
ATSif(
ATSCKiseqz(
_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$projects_057$org_056$ats_055$lang_056$postiats_056$jats_057$test_057$test01_056$dats__dynloadflag
)
) ATSthen() {
ATSdynloadset(_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$projects_057$org_056$ats_055$lang_056$postiats_056$jats_057$test_057$test01_056$dats__dynloadflag) ;
} /* ATSendif */
ATSreturn_void() ;
} /* end of [*_dynload] */

/*
** the ATS runtime
*/
#ifndef _ATS_CCOMP_RUNTIME_NONE
#include "pats_ccomp_runtime.c"
#endif /* _ATS_CCOMP_RUNTIME_NONE */

/*
** the [main] implementation
*/
int
main
(
int argc, char **argv, char **envp
) {
int err = 0 ;
_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$projects_057$org_056$ats_055$lang_056$postiats_056$jats_057$test_057$test01_056$dats__dynload() ;
ATSmainats_void_0(err) ;
return (err) ;
} /* end of [main] */
