/*
**
** The C code is generated by ATS/Postiats
** The starting compilation time is: 2015-6-2: 14h:53m
**
*/

/*
** include runtime header files
*/
#ifndef _ATS_CCOMP_HEADER_NONE
#include "pats_ccomp_config.h"
#include "pats_ccomp_basics.h"
#include "pats_ccomp_typedefs.h"
#include "pats_ccomp_instrset.h"
#include "pats_ccomp_memalloc.h"
#ifndef _ATS_CCOMP_EXCEPTION_NONE
#include "pats_ccomp_memalloca.h"
#include "pats_ccomp_exception.h"
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE]
#endif /* _ATS_CCOMP_HEADER_NONE */


/*
** include prelude cats files
*/
#ifndef _ATS_CCOMP_PRELUDE_NONE
//
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/integer_ptr.cats"
#include "prelude/CATS/integer_fixed.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/memory.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/strptr.cats"
//
#include "prelude/CATS/filebas.cats"
//
#include "prelude/CATS/list.cats"
#include "prelude/CATS/option.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/arrayptr.cats"
#include "prelude/CATS/arrayref.cats"
#include "prelude/CATS/matrix.cats"
#include "prelude/CATS/matrixptr.cats"
//
#endif /* _ATS_CCOMP_PRELUDE_NONE */
/*
** for user-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER
//
#include _ATS_CCOMP_PRELUDE_USER
//
#endif /* _ATS_CCOMP_PRELUDE_USER */
/*
** for user2-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER2
//
#include _ATS_CCOMP_PRELUDE_USER2
//
#endif /* _ATS_CCOMP_PRELUDE_USER2 */

/*
staload-prologues(beg)
*/
/*
/home/grad2/aren/programs/ats2_github/ATS-Postiats/prelude/DATS/integer.dats: 1636(line=51, offs=1) -- 1675(line=51, offs=40)
*/
/*
staload-prologues(end)
*/
/*
typedefs-for-tyrecs-and-tysums(beg)
*/
typedef
ATSstruct {
atstkind_t0ype(atstype_int) atslab__0 ;
atstkind_t0ype(atstype_double) atslab__1 ;
} postiats_tyrec_0 ;
typedef
ATSstruct {
atstkind_t0ype(atstype_int) atslab__0 ;
atstkind_type(atstype_ptrk) atslab__1 ;
} postiats_tyrec_1 ;
typedef
ATSstruct {
atstkind_t0ype(atstype_int) atslab__0 ;
atstkind_t0ype(atstype_int) atslab__1 ;
} postiats_tyrec_2 ;
typedef
ATSstruct {
atstkind_t0ype(atstype_int) atslab__0 ;
atstkind_t0ype(atstype_char) atslab__1 ;
} postiats_tyrec_3 ;
/*
typedefs-for-tyrecs-and-tysums(end)
*/
/*
dynconlst-declaration(beg)
*/
/*
dynconlst-declaration(end)
*/
/*
dyncstlst-declaration(beg)
*/
ATSdyncst_mac(atspre_print_string)
ATSdyncst_mac(atspre_print_int)
ATSdyncst_mac(atspre_print_newline)
ATSdyncst_mac(atspre_g0int_add_int)
ATSdyncst_mac(atspre_assert_errmsg_bool1)
ATSdyncst_mac(atspre_g1int2int_int_int)
ATSdyncst_mac(atspre_g1int_eq_int)
ATSdyncst_mac(atspre_assert_errmsg_bool0)
ATSdyncst_mac(atspre_g0int2int_int_int)
ATSdyncst_mac(atspre_g0int_eq_int)
ATSdyncst_mac(atspre_eq_string_string)
/*
dyncstlst-declaration(end)
*/
/*
dynvalist-implementation(beg)
*/
/*
dynvalist-implementation(end)
*/
/*
exnconlst-declaration(beg)
*/
#ifndef _ATS_CCOMP_EXCEPTION_NONE
ATSextern()
atsvoid_t0ype
the_atsexncon_initize
(
  atstype_exnconptr d2c, atstype_string exnmsg
) ;
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE]
/*
exnconlst-declaration(end)
*/
/*
assumelst-declaration(beg)
*/
/*
assumelst-declaration(end)
*/
/*
extypelst-declaration(beg)
*/
/*
extypelst-declaration(end)
*/
ATSstatic()
atsvoid_t0ype
foo_bt_val_0(atstype_boxed) ;

ATSstatic()
atsvoid_t0ype
foo_ft_val_1(postiats_tyrec_0) ;

ATSstatic()
atsvoid_t0ype
foo_bt_var_2(atsrefarg1_type(atstype_boxed)) ;

ATSstatic()
atsvoid_t0ype
foo_ft_var_3(atsrefarg1_type(postiats_tyrec_1)) ;

ATSstatic()
atstkind_t0ype(atstype_int)
foo_int_4() ;

#if(0)
ATSextern()
atsvoid_t0ype
mainats_void_0() ;
#endif // end of [QUALIFIED]

#if(0)
#if(0)
ATSextern()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g1int_int__7(atstkind_t0ype(atstyvar_type(tk)), atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstatic()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g1int_int__7__1(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

#if(0)
#if(0)
ATSextern()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__11(atstkind_t0ype(atstyvar_type(tk)), atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstatic()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__11__1(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

ATSstatic()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g1int_int__7__2(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

ATSstatic()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__11__2(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

/*
/home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/test01.dats: 45(line=6, offs=5) -- 128(line=9, offs=4)
*/
/*
local: 
global: foo_bt_val_0$0(level=0)
local: 
global: 
*/
ATSstatic()
atsvoid_t0ype
foo_bt_val_0(atstype_boxed arg0)
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret0) ;
// ATStmpdec_void(tmp1) ;
// ATStmpdec_void(tmp2) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/test01.dats: 45(line=6, offs=5) -- 128(line=9, offs=4)
*/
ATSINSflab(__patsflab_foo_bt_val_0):
/*
emit_instr: loc0 = /home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/test01.dats: 81(line=6, offs=41) -- 128(line=9, offs=4)
*/
/*
letpush(beg)
*/
/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/test01.dats: 96(line=7, offs=12) -- 121(line=7, offs=37)
*/
ATSINSmove_void(tmp1, atspre_print_string(ATSPMVstring("int is "))) ;

/*
emit_instr: loc0 = /home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/test01.dats: 96(line=7, offs=12) -- 121(line=7, offs=37)
*/
ATSINSmove_void(tmp2, atspre_print_int(ATSSELboxrec(arg0, postiats_tyrec_2, atslab__0))) ;

/*
emit_instr: loc0 = /home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/test01.dats: 96(line=7, offs=12) -- 121(line=7, offs=37)
*/
ATSINSmove_void(tmpret0, atspre_print_newline()) ;

/*
emit_instr: loc0 = /home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/test01.dats: 81(line=6, offs=41) -- 128(line=9, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn_void(tmpret0) ;
} /* end of [foo_bt_val_0] */

/*
/home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/test01.dats: 134(line=11, offs=5) -- 220(line=14, offs=4)
*/
/*
local: 
global: foo_ft_val_1$0(level=0)
local: 
global: 
*/
ATSstatic()
atsvoid_t0ype
foo_ft_val_1(postiats_tyrec_0 arg0)
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret3) ;
// ATStmpdec_void(tmp4) ;
// ATStmpdec_void(tmp5) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/test01.dats: 134(line=11, offs=5) -- 220(line=14, offs=4)
*/
ATSINSflab(__patsflab_foo_ft_val_1):
/*
emit_instr: loc0 = /home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/test01.dats: 173(line=11, offs=44) -- 220(line=14, offs=4)
*/
/*
letpush(beg)
*/
/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/test01.dats: 188(line=12, offs=12) -- 213(line=12, offs=37)
*/
ATSINSmove_void(tmp4, atspre_print_string(ATSPMVstring("int is "))) ;

/*
emit_instr: loc0 = /home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/test01.dats: 188(line=12, offs=12) -- 213(line=12, offs=37)
*/
ATSINSmove_void(tmp5, atspre_print_int(ATSSELfltrec(arg0, postiats_tyrec_0, atslab__0))) ;

/*
emit_instr: loc0 = /home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/test01.dats: 188(line=12, offs=12) -- 213(line=12, offs=37)
*/
ATSINSmove_void(tmpret3, atspre_print_newline()) ;

/*
emit_instr: loc0 = /home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/test01.dats: 173(line=11, offs=44) -- 220(line=14, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn_void(tmpret3) ;
} /* end of [foo_ft_val_1] */

/*
/home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/test01.dats: 226(line=16, offs=5) -- 335(line=20, offs=4)
*/
/*
local: 
global: foo_bt_var_2$0(level=0)
local: 
global: 
*/
ATSstatic()
atsvoid_t0ype
foo_bt_var_2(atsrefarg1_type(atstype_boxed) arg0)
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret6) ;
ATStmpdec(tmp7, atstype_boxed) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/test01.dats: 226(line=16, offs=5) -- 335(line=20, offs=4)
*/
ATSINSflab(__patsflab_foo_bt_var_2):
/*
emit_instr: loc0 = /home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/test01.dats: 264(line=16, offs=43) -- 335(line=20, offs=4)
*/
/*
letpush(beg)
*/
/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/test01.dats: 284(line=17, offs=17) -- 294(line=17, offs=27)
*/
/*
#LINCONSTATUS==2
*/
ATSINSmove_boxrec_beg()
ATSINSmove_boxrec_new(tmp7, postiats_tyrec_3) ;
ATSINSstore_boxrec_ofs (tmp7, postiats_tyrec_3, atslab__0, ATSPMVi0nt(52)) ;
ATSINSstore_boxrec_ofs (tmp7, postiats_tyrec_3, atslab__1, ATSPMVchar('c')) ;
ATSINSmove_boxrec_end()
/*
emit_instr: loc0 = /home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/test01.dats: 279(line=17, offs=12) -- 294(line=17, offs=27)
*/
ATSINSstore(ATSderef(arg0, atstype_boxed), tmp7) ;
/*
emit_instr: loc0 = /home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/test01.dats: 279(line=17, offs=12) -- 294(line=17, offs=27)
*/
ATSINSmove_void(tmpret6, ATSPMVempty()) ;
/*
emit_instr: loc0 = /home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/test01.dats: 264(line=16, offs=43) -- 335(line=20, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn_void(tmpret6) ;
} /* end of [foo_bt_var_2] */

/*
/home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/test01.dats: 341(line=22, offs=5) -- 445(line=26, offs=4)
*/
/*
local: 
global: foo_ft_var_3$0(level=0)
local: 
global: 
*/
ATSstatic()
atsvoid_t0ype
foo_ft_var_3(atsrefarg1_type(postiats_tyrec_1) arg0)
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret8) ;
ATStmpdec(tmp9, postiats_tyrec_1) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/test01.dats: 341(line=22, offs=5) -- 445(line=26, offs=4)
*/
ATSINSflab(__patsflab_foo_ft_var_3):
/*
emit_instr: loc0 = /home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/test01.dats: 382(line=22, offs=46) -- 445(line=26, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/test01.dats: 402(line=23, offs=17) -- 414(line=23, offs=29)
*/
ATSINSmove_fltrec_beg()
ATSINSstore_fltrec_ofs (tmp9, postiats_tyrec_1, atslab__0, ATSPMVi0nt(72)) ;
ATSINSstore_fltrec_ofs (tmp9, postiats_tyrec_1, atslab__1, ATSPMVstring("cde")) ;
ATSINSmove_fltrec_end()
/*
emit_instr: loc0 = /home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/test01.dats: 397(line=23, offs=12) -- 414(line=23, offs=29)
*/
ATSINSstore(ATSderef(arg0, postiats_tyrec_1), tmp9) ;
/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/test01.dats: 426(line=24, offs=12) -- 438(line=24, offs=24)
*/
ATSINSstore(ATSSELfltrec(ATSderef(arg0, postiats_tyrec_1), postiats_tyrec_1, atslab__1), ATSPMVstring("def")) ;
/*
emit_instr: loc0 = /home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/test01.dats: 426(line=24, offs=12) -- 438(line=24, offs=24)
*/
ATSINSmove_void(tmpret8, ATSPMVempty()) ;
/*
emit_instr: loc0 = /home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/test01.dats: 382(line=22, offs=46) -- 445(line=26, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn_void(tmpret8) ;
} /* end of [foo_ft_var_3] */

/*
/home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/test01.dats: 451(line=28, offs=5) -- 470(line=28, offs=24)
*/
/*
local: 
global: foo_int_4$0(level=0)
local: 
global: 
*/
ATSstatic()
atstkind_t0ype(atstype_int)
foo_int_4()
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret10, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/test01.dats: 451(line=28, offs=5) -- 470(line=28, offs=24)
*/
ATSINSflab(__patsflab_foo_int_4):
/*
emit_instr: loc0 = /home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/test01.dats: 469(line=28, offs=23) -- 470(line=28, offs=24)
*/
ATSINSmove(tmpret10, ATSPMVi0nt(3)) ;
ATSfunbody_end()
ATSreturn(tmpret10) ;
} /* end of [foo_int_4] */

/*
/home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/test01.dats: 488(line=30, offs=17) -- 1495(line=76, offs=4)
*/
/*
local: foo_bt_val_0$0(level=0), foo_ft_val_1$0(level=0), foo_bt_var_2$0(level=0), foo_ft_var_3$0(level=0), foo_int_4$0(level=0)
global: foo_bt_val_0$0(level=0), foo_ft_val_1$0(level=0), foo_bt_var_2$0(level=0), foo_ft_var_3$0(level=0), foo_int_4$0(level=0), mainats_void_0$5$0(level=0)
local: 
global: 
*/
ATSextern()
atsvoid_t0ype
mainats_void_0()
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret11) ;
ATStmpdec(tmp12, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp13, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmpref14, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmpref15, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp16, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp17, atstype_boxed) ;
ATStmpdec(tmp18, atstype_boxed) ;
// ATStmpdec_void(tmp19) ;
ATStmpdec(tmp20, postiats_tyrec_0) ;
ATStmpdec(tmp21, postiats_tyrec_0) ;
// ATStmpdec_void(tmp22) ;
ATStmpdec(tmpref23, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp24, atstype_boxed) ;
// ATStmpdec_void(tmp25) ;
ATStmpdec(tmp26, atstkind_t0ype(atstype_bool)) ;
// ATStmpdec_void(tmp31) ;
// ATStmpdec_void(tmp32) ;
ATStmpdec(tmp33, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmpref38, postiats_tyrec_1) ;
// ATStmpdec_void(tmp39) ;
ATStmpdec(tmp40, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp43, postiats_tyrec_1) ;
// ATStmpdec_void(tmp44) ;
ATStmpdec(tmp45, atstkind_t0ype(atstype_bool)) ;
// ATStmpdec_void(tmp46) ;
// ATStmpdec_void(tmp47) ;
ATStmpdec(tmp48, atstkind_t0ype(atstype_bool)) ;
// ATStmpdec_void(tmp51) ;
ATStmpdec(tmp52, atstkind_t0ype(atstype_bool)) ;
// ATStmpdec_void(tmp53) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/test01.dats: 482(line=30, offs=11) -- 1495(line=76, offs=4)
*/
ATSINSflab(__patsflab_main_void_0):
/*
emit_instr: loc0 = /home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/test01.dats: 493(line=30, offs=22) -- 1495(line=76, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/test01.dats: 509(line=32, offs=11) -- 519(line=32, offs=21)
*/
ATSINSmove(tmp12, foo_int_4()) ;

/*
emit_instr: loc0 = /home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/test01.dats: 530(line=33, offs=11) -- 535(line=33, offs=16)
*/
ATSINSmove(tmp13, atspre_g0int_add_int(tmp12, ATSPMVi0nt(1))) ;

/*
emit_instr: loc0 = /home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/test01.dats: 545(line=35, offs=7) -- 546(line=35, offs=8)
*/
/*
ATSINStmpdec(tmpref14) ;
*/
/*
emit_instr: loc0 = /home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/test01.dats: 549(line=35, offs=11) -- 559(line=35, offs=21)
*/
ATSINSmove(tmpref14, foo_int_4()) ;

/*
emit_instr: loc0 = /home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/test01.dats: 566(line=36, offs=7) -- 567(line=36, offs=8)
*/
/*
ATSINStmpdec(tmpref15) ;
*/
/*
emit_instr: loc0 = /home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/test01.dats: 570(line=36, offs=11) -- 575(line=36, offs=16)
*/
ATSINSmove(tmpref15, atspre_g0int_add_int(tmpref14, ATSPMVi0nt(1))) ;

/*
emit_instr: loc0 = /home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/test01.dats: 592(line=37, offs=17) -- 597(line=37, offs=22)
*/
ATSINSmove(tmp16, atspre_g0int_add_int(tmpref15, ATSPMVi0nt(2))) ;

/*
emit_instr: loc0 = /home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/test01.dats: 587(line=37, offs=12) -- 597(line=37, offs=22)
*/
ATSINSstore(tmpref15, tmp16) ;
/*
emit_instr: loc0 = /home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/test01.dats: 618(line=39, offs=18) -- 625(line=39, offs=25)
*/
/*
#LINCONSTATUS==2
*/
ATSINSmove_boxrec_beg()
ATSINSmove_boxrec_new(tmp17, postiats_tyrec_2) ;
ATSINSstore_boxrec_ofs (tmp17, postiats_tyrec_2, atslab__0, ATSPMVi0nt(0)) ;
ATSINSstore_boxrec_ofs (tmp17, postiats_tyrec_2, atslab__1, ATSPMVi0nt(1)) ;
ATSINSmove_boxrec_end()
/*
emit_instr: loc0 = /home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/test01.dats: 643(line=40, offs=18) -- 650(line=40, offs=25)
*/
/*
#LINCONSTATUS==2
*/
ATSINSmove_boxrec_beg()
ATSINSmove_boxrec_new(tmp18, postiats_tyrec_2) ;
ATSINSstore_boxrec_ofs (tmp18, postiats_tyrec_2, atslab__0, ATSPMVi0nt(1)) ;
ATSINSstore_boxrec_ofs (tmp18, postiats_tyrec_2, atslab__1, ATSPMVi0nt(2)) ;
ATSINSmove_boxrec_end()
/*
emit_instr: loc0 = /home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/test01.dats: 662(line=41, offs=12) -- 681(line=41, offs=31)
*/
ATSINSmove_void(tmp19, foo_bt_val_0(tmp18)) ;

/*
emit_instr: loc0 = /home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/test01.dats: 726(line=45, offs=18) -- 735(line=45, offs=27)
*/
ATSINSmove_fltrec_beg()
ATSINSstore_fltrec_ofs (tmp20, postiats_tyrec_0, atslab__0, ATSPMVi0nt(2)) ;
ATSINSstore_fltrec_ofs (tmp20, postiats_tyrec_0, atslab__1, ATSPMVf0loat(0.1)) ;
ATSINSmove_fltrec_end()
/*
emit_instr: loc0 = /home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/test01.dats: 753(line=46, offs=18) -- 762(line=46, offs=27)
*/
ATSINSmove_fltrec_beg()
ATSINSstore_fltrec_ofs (tmp21, postiats_tyrec_0, atslab__0, ATSPMVi0nt(3)) ;
ATSINSstore_fltrec_ofs (tmp21, postiats_tyrec_0, atslab__1, ATSPMVf0loat(1.2)) ;
ATSINSmove_fltrec_end()
/*
emit_instr: loc0 = /home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/test01.dats: 774(line=47, offs=12) -- 793(line=47, offs=31)
*/
ATSINSmove_void(tmp22, foo_ft_val_1(tmp21)) ;

/*
emit_instr: loc0 = /home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/test01.dats: 828(line=51, offs=7) -- 836(line=51, offs=15)
*/
/*
ATSINStmpdec(tmpref23) ;
*/
/*
emit_instr: loc0 = /home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/test01.dats: 839(line=51, offs=18) -- 848(line=51, offs=27)
*/
/*
#LINCONSTATUS==2
*/
ATSINSmove_boxrec_beg()
ATSINSmove_boxrec_new(tmpref23, postiats_tyrec_3) ;
ATSINSstore_boxrec_ofs (tmpref23, postiats_tyrec_3, atslab__0, ATSPMVi0nt(5)) ;
ATSINSstore_boxrec_ofs (tmpref23, postiats_tyrec_3, atslab__1, ATSPMVchar('a')) ;
ATSINSmove_boxrec_end()
/*
emit_instr: loc0 = /home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/test01.dats: 872(line=52, offs=24) -- 882(line=52, offs=34)
*/
/*
#LINCONSTATUS==2
*/
ATSINSmove_boxrec_beg()
ATSINSmove_boxrec_new(tmp24, postiats_tyrec_3) ;
ATSINSstore_boxrec_ofs (tmp24, postiats_tyrec_3, atslab__0, ATSPMVi0nt(51)) ;
ATSINSstore_boxrec_ofs (tmp24, postiats_tyrec_3, atslab__1, ATSPMVchar('b')) ;
ATSINSmove_boxrec_end()
/*
emit_instr: loc0 = /home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/test01.dats: 860(line=52, offs=12) -- 882(line=52, offs=34)
*/
ATSINSstore(tmpref23, tmp24) ;
/*
emit_instr: loc0 = /home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/test01.dats: 894(line=53, offs=12) -- 921(line=53, offs=39)
*/
ATSINSmove(tmp26, ATSLIB_056_prelude__eq_g1int_int__7__1(ATSSELboxrec(tmpref23, postiats_tyrec_3, atslab__0), ATSPMVi0nt(51))) ;

/*
emit_instr: loc0 = /home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/test01.dats: 894(line=53, offs=12) -- 921(line=53, offs=39)
*/
ATSINSmove_void(tmp25, atspre_assert_errmsg_bool1(tmp26, ATSCSTSPmyloc("/home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/test01.dats: 894(line=53, offs=12) -- 921(line=53, offs=39)"))) ;

/*
emit_instr: loc0 = /home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/test01.dats: 974(line=56, offs=12) -- 994(line=56, offs=32)
*/
ATSINSmove_void(tmp31, foo_bt_var_2(ATSPMVrefarg1(ATSPMVptrof(tmpref23)))) ;

/*
emit_instr: loc0 = /home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/test01.dats: 1007(line=57, offs=12) -- 1034(line=57, offs=39)
*/
ATSINSmove(tmp33, ATSLIB_056_prelude__eq_g0int_int__11__1(ATSSELboxrec(tmpref23, postiats_tyrec_3, atslab__0), ATSPMVi0nt(52))) ;

/*
emit_instr: loc0 = /home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/test01.dats: 1007(line=57, offs=12) -- 1034(line=57, offs=39)
*/
ATSINSmove_void(tmp32, atspre_assert_errmsg_bool0(tmp33, ATSCSTSPmyloc("/home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/test01.dats: 1007(line=57, offs=12) -- 1034(line=57, offs=39)"))) ;

/*
emit_instr: loc0 = /home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/test01.dats: 1067(line=60, offs=7) -- 1075(line=60, offs=15)
*/
/*
ATSINStmpdec(tmpref38) ;
*/
/*
emit_instr: loc0 = /home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/test01.dats: 1078(line=60, offs=18) -- 1089(line=60, offs=29)
*/
ATSINSmove_fltrec_beg()
ATSINSstore_fltrec_ofs (tmpref38, postiats_tyrec_1, atslab__0, ATSPMVi0nt(7)) ;
ATSINSstore_fltrec_ofs (tmpref38, postiats_tyrec_1, atslab__1, ATSPMVstring("abc")) ;
ATSINSmove_fltrec_end()
/*
emit_instr: loc0 = /home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/test01.dats: 1116(line=61, offs=12) -- 1132(line=61, offs=28)
*/
ATSINSstore(ATSSELfltrec(tmpref38, postiats_tyrec_1, atslab__0), ATSPMVi0nt(70)) ;
/*
emit_instr: loc0 = /home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/test01.dats: 1144(line=62, offs=12) -- 1171(line=62, offs=39)
*/
ATSINSmove(tmp40, ATSLIB_056_prelude__eq_g1int_int__7__2(ATSSELfltrec(tmpref38, postiats_tyrec_1, atslab__0), ATSPMVi0nt(70))) ;

/*
emit_instr: loc0 = /home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/test01.dats: 1144(line=62, offs=12) -- 1171(line=62, offs=39)
*/
ATSINSmove_void(tmp39, atspre_assert_errmsg_bool1(tmp40, ATSCSTSPmyloc("/home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/test01.dats: 1144(line=62, offs=12) -- 1171(line=62, offs=39)"))) ;

/*
emit_instr: loc0 = /home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/test01.dats: 1198(line=64, offs=25) -- 1209(line=64, offs=36)
*/
ATSINSmove_fltrec_beg()
ATSINSstore_fltrec_ofs (tmp43, postiats_tyrec_1, atslab__0, ATSPMVi0nt(71)) ;
ATSINSstore_fltrec_ofs (tmp43, postiats_tyrec_1, atslab__1, ATSPMVstring("bcd")) ;
ATSINSmove_fltrec_end()
/*
emit_instr: loc0 = /home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/test01.dats: 1186(line=64, offs=13) -- 1209(line=64, offs=36)
*/
ATSINSstore(tmpref38, tmp43) ;
/*
emit_instr: loc0 = /home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/test01.dats: 1222(line=65, offs=13) -- 1252(line=65, offs=43)
*/
ATSINSmove(tmp45, atspre_eq_string_string(ATSSELfltrec(tmpref38, postiats_tyrec_1, atslab__1), ATSPMVstring("bcd"))) ;

/*
emit_instr: loc0 = /home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/test01.dats: 1222(line=65, offs=13) -- 1252(line=65, offs=43)
*/
ATSINSmove_void(tmp44, atspre_assert_errmsg_bool0(tmp45, ATSCSTSPmyloc("/home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/test01.dats: 1222(line=65, offs=13) -- 1252(line=65, offs=43)"))) ;

/*
emit_instr: loc0 = /home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/test01.dats: 1269(line=67, offs=13) -- 1289(line=67, offs=33)
*/
ATSINSmove_void(tmp46, foo_ft_var_3(ATSPMVrefarg1(ATSPMVptrof(tmpref38)))) ;

/*
emit_instr: loc0 = /home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/test01.dats: 1303(line=68, offs=13) -- 1330(line=68, offs=40)
*/
ATSINSmove(tmp48, ATSLIB_056_prelude__eq_g0int_int__11__2(ATSSELfltrec(tmpref38, postiats_tyrec_1, atslab__0), ATSPMVi0nt(72))) ;

/*
emit_instr: loc0 = /home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/test01.dats: 1303(line=68, offs=13) -- 1330(line=68, offs=40)
*/
ATSINSmove_void(tmp47, atspre_assert_errmsg_bool0(tmp48, ATSCSTSPmyloc("/home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/test01.dats: 1303(line=68, offs=13) -- 1330(line=68, offs=40)"))) ;

/*
emit_instr: loc0 = /home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/test01.dats: 1343(line=69, offs=13) -- 1373(line=69, offs=43)
*/
ATSINSmove(tmp52, atspre_eq_string_string(ATSSELfltrec(tmpref38, postiats_tyrec_1, atslab__1), ATSPMVstring("def"))) ;

/*
emit_instr: loc0 = /home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/test01.dats: 1343(line=69, offs=13) -- 1373(line=69, offs=43)
*/
ATSINSmove_void(tmp51, atspre_assert_errmsg_bool0(tmp52, ATSCSTSPmyloc("/home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/test01.dats: 1343(line=69, offs=13) -- 1373(line=69, offs=43)"))) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/test01.dats: 1386(line=70, offs=13) -- 1403(line=70, offs=30)
*/
ATSINSmove_void(tmp53, atspre_print_string(ATSPMVstring("done"))) ;

/*
emit_instr: loc0 = /home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/test01.dats: 1386(line=70, offs=13) -- 1403(line=70, offs=30)
*/
ATSINSmove_void(tmpret11, atspre_print_newline()) ;

/*
emit_instr: loc0 = /home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/test01.dats: 493(line=30, offs=22) -- 1495(line=76, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn_void(tmpret11) ;
} /* end of [mainats_void_0] */

#if(0)
/*
/home/grad2/aren/programs/ats2_github/ATS-Postiats/prelude/DATS/integer.dats: 29874(line=831, offs=14) -- 29914(line=831, offs=54)
*/
/*
local: 
global: eq_g1int_int$7$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = tk(4441)
tmparg = S2Evar(tk(4441))
tmpsub = None()
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g1int_int__7(atstkind_t0ype(atstyvar_type(tk)) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret27, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp28, atstkind_t0ype(atstyvar_type(tk))) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/grad2/aren/programs/ats2_github/ATS-Postiats/prelude/DATS/integer.dats: 29861(line=831, offs=1) -- 29914(line=831, offs=54)
*/
ATSINSflab(__patsflab_eq_g1int_int):
/*
emit_instr: loc0 = /home/grad2/aren/programs/ats2_github/ATS-Postiats/prelude/DATS/integer.dats: 29900(line=831, offs=40) -- 29912(line=831, offs=52)
*/
ATSINSmove(tmp28, PMVtmpltcst(g1int2int<S2Eextkind(atstype_int), S2Evar(tk(4441))>)(arg1)) ;

/*
emit_instr: loc0 = /home/grad2/aren/programs/ats2_github/ATS-Postiats/prelude/DATS/integer.dats: 29883(line=831, offs=23) -- 29914(line=831, offs=54)
*/
ATSINSmove(tmpret27, PMVtmpltcst(g1int_eq<S2Evar(tk(4441))>)(arg0, tmp28)) ;

ATSfunbody_end()
ATSreturn(tmpret27) ;
} /* end of [ATSLIB_056_prelude__eq_g1int_int__7] */
#endif // end of [TEMPLATE]

/*
/home/grad2/aren/programs/ats2_github/ATS-Postiats/prelude/DATS/integer.dats: 29874(line=831, offs=14) -- 29914(line=831, offs=54)
*/
/*
local: 
global: eq_g1int_int$7$1(level=1)
local: 
global: 
*/
ATSstatic()
/*
imparg = tk(4441)
tmparg = S2Evar(tk(4441))
tmpsub = Some(tk(4441) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g1int_int__7__1(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret27__1, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp28__1, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/grad2/aren/programs/ats2_github/ATS-Postiats/prelude/DATS/integer.dats: 29861(line=831, offs=1) -- 29914(line=831, offs=54)
*/
ATSINSflab(__patsflab_eq_g1int_int):
/*
emit_instr: loc0 = /home/grad2/aren/programs/ats2_github/ATS-Postiats/prelude/DATS/integer.dats: 29900(line=831, offs=40) -- 29912(line=831, offs=52)
*/
ATSINSmove(tmp28__1, atspre_g1int2int_int_int(arg1)) ;

/*
emit_instr: loc0 = /home/grad2/aren/programs/ats2_github/ATS-Postiats/prelude/DATS/integer.dats: 29883(line=831, offs=23) -- 29914(line=831, offs=54)
*/
ATSINSmove(tmpret27__1, atspre_g1int_eq_int(arg0, tmp28__1)) ;

ATSfunbody_end()
ATSreturn(tmpret27__1) ;
} /* end of [ATSLIB_056_prelude__eq_g1int_int__7__1] */

#if(0)
/*
/home/grad2/aren/programs/ats2_github/ATS-Postiats/prelude/DATS/integer.dats: 29359(line=813, offs=14) -- 29399(line=813, offs=54)
*/
/*
local: 
global: eq_g0int_int$11$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = tk(4426)
tmparg = S2Evar(tk(4426))
tmpsub = None()
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__11(atstkind_t0ype(atstyvar_type(tk)) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret34, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp35, atstkind_t0ype(atstyvar_type(tk))) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/grad2/aren/programs/ats2_github/ATS-Postiats/prelude/DATS/integer.dats: 29346(line=813, offs=1) -- 29399(line=813, offs=54)
*/
ATSINSflab(__patsflab_eq_g0int_int):
/*
emit_instr: loc0 = /home/grad2/aren/programs/ats2_github/ATS-Postiats/prelude/DATS/integer.dats: 29385(line=813, offs=40) -- 29397(line=813, offs=52)
*/
ATSINSmove(tmp35, PMVtmpltcst(g0int2int<S2Eextkind(atstype_int), S2Evar(tk(4426))>)(arg1)) ;

/*
emit_instr: loc0 = /home/grad2/aren/programs/ats2_github/ATS-Postiats/prelude/DATS/integer.dats: 29368(line=813, offs=23) -- 29399(line=813, offs=54)
*/
ATSINSmove(tmpret34, PMVtmpltcst(g0int_eq<S2Evar(tk(4426))>)(arg0, tmp35)) ;

ATSfunbody_end()
ATSreturn(tmpret34) ;
} /* end of [ATSLIB_056_prelude__eq_g0int_int__11] */
#endif // end of [TEMPLATE]

/*
/home/grad2/aren/programs/ats2_github/ATS-Postiats/prelude/DATS/integer.dats: 29359(line=813, offs=14) -- 29399(line=813, offs=54)
*/
/*
local: 
global: eq_g0int_int$11$1(level=1)
local: 
global: 
*/
ATSstatic()
/*
imparg = tk(4426)
tmparg = S2Evar(tk(4426))
tmpsub = Some(tk(4426) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__11__1(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret34__1, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp35__1, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/grad2/aren/programs/ats2_github/ATS-Postiats/prelude/DATS/integer.dats: 29346(line=813, offs=1) -- 29399(line=813, offs=54)
*/
ATSINSflab(__patsflab_eq_g0int_int):
/*
emit_instr: loc0 = /home/grad2/aren/programs/ats2_github/ATS-Postiats/prelude/DATS/integer.dats: 29385(line=813, offs=40) -- 29397(line=813, offs=52)
*/
ATSINSmove(tmp35__1, atspre_g0int2int_int_int(arg1)) ;

/*
emit_instr: loc0 = /home/grad2/aren/programs/ats2_github/ATS-Postiats/prelude/DATS/integer.dats: 29368(line=813, offs=23) -- 29399(line=813, offs=54)
*/
ATSINSmove(tmpret34__1, atspre_g0int_eq_int(arg0, tmp35__1)) ;

ATSfunbody_end()
ATSreturn(tmpret34__1) ;
} /* end of [ATSLIB_056_prelude__eq_g0int_int__11__1] */

/*
/home/grad2/aren/programs/ats2_github/ATS-Postiats/prelude/DATS/integer.dats: 29874(line=831, offs=14) -- 29914(line=831, offs=54)
*/
/*
local: 
global: eq_g1int_int$7$2(level=1)
local: 
global: 
*/
ATSstatic()
/*
imparg = tk(4441)
tmparg = S2Evar(tk(4441))
tmpsub = Some(tk(4441) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g1int_int__7__2(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret27__2, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp28__2, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/grad2/aren/programs/ats2_github/ATS-Postiats/prelude/DATS/integer.dats: 29861(line=831, offs=1) -- 29914(line=831, offs=54)
*/
ATSINSflab(__patsflab_eq_g1int_int):
/*
emit_instr: loc0 = /home/grad2/aren/programs/ats2_github/ATS-Postiats/prelude/DATS/integer.dats: 29900(line=831, offs=40) -- 29912(line=831, offs=52)
*/
ATSINSmove(tmp28__2, atspre_g1int2int_int_int(arg1)) ;

/*
emit_instr: loc0 = /home/grad2/aren/programs/ats2_github/ATS-Postiats/prelude/DATS/integer.dats: 29883(line=831, offs=23) -- 29914(line=831, offs=54)
*/
ATSINSmove(tmpret27__2, atspre_g1int_eq_int(arg0, tmp28__2)) ;

ATSfunbody_end()
ATSreturn(tmpret27__2) ;
} /* end of [ATSLIB_056_prelude__eq_g1int_int__7__2] */

/*
/home/grad2/aren/programs/ats2_github/ATS-Postiats/prelude/DATS/integer.dats: 29359(line=813, offs=14) -- 29399(line=813, offs=54)
*/
/*
local: 
global: eq_g0int_int$11$2(level=1)
local: 
global: 
*/
ATSstatic()
/*
imparg = tk(4426)
tmparg = S2Evar(tk(4426))
tmpsub = Some(tk(4426) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__11__2(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret34__2, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp35__2, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/grad2/aren/programs/ats2_github/ATS-Postiats/prelude/DATS/integer.dats: 29346(line=813, offs=1) -- 29399(line=813, offs=54)
*/
ATSINSflab(__patsflab_eq_g0int_int):
/*
emit_instr: loc0 = /home/grad2/aren/programs/ats2_github/ATS-Postiats/prelude/DATS/integer.dats: 29385(line=813, offs=40) -- 29397(line=813, offs=52)
*/
ATSINSmove(tmp35__2, atspre_g0int2int_int_int(arg1)) ;

/*
emit_instr: loc0 = /home/grad2/aren/programs/ats2_github/ATS-Postiats/prelude/DATS/integer.dats: 29368(line=813, offs=23) -- 29399(line=813, offs=54)
*/
ATSINSmove(tmpret34__2, atspre_g0int_eq_int(arg0, tmp35__2)) ;

ATSfunbody_end()
ATSreturn(tmpret34__2) ;
} /* end of [ATSLIB_056_prelude__eq_g0int_int__11__2] */

/*
** for initialization(dynloading)
*/
ATSdynloadflag_minit(_057_home_057_grad2_057_aren_057_workspace_057_Postiats_057_projects_057_org_056_ats_055_lang_056_postiats_056_jats_057_test_057_test01_056_dats__dynloadflag) ;
ATSextern()
atsvoid_t0ype
_057_home_057_grad2_057_aren_057_workspace_057_Postiats_057_projects_057_org_056_ats_055_lang_056_postiats_056_jats_057_test_057_test01_056_dats__dynload()
{
ATSfunbody_beg()
ATSdynload(/*void*/)
ATSdynloadflag_sta(
_057_home_057_grad2_057_aren_057_workspace_057_Postiats_057_projects_057_org_056_ats_055_lang_056_postiats_056_jats_057_test_057_test01_056_dats__dynloadflag
) ;
ATSif(
ATSCKiseqz(
_057_home_057_grad2_057_aren_057_workspace_057_Postiats_057_projects_057_org_056_ats_055_lang_056_postiats_056_jats_057_test_057_test01_056_dats__dynloadflag
)
) ATSthen() {
ATSdynloadset(_057_home_057_grad2_057_aren_057_workspace_057_Postiats_057_projects_057_org_056_ats_055_lang_056_postiats_056_jats_057_test_057_test01_056_dats__dynloadflag) ;
/*
dynexnlst-initize(beg)
*/
/*
dynexnlst-initize(end)
*/
} /* ATSendif */
ATSfunbody_end()
ATSreturn_void(tmpret_void) ;
} /* end of [*_dynload] */

/*
** the ATS runtime
*/
#ifndef _ATS_CCOMP_RUNTIME_NONE
#include "pats_ccomp_runtime.c"
#include "pats_ccomp_runtime_memalloc.c"
#ifndef _ATS_CCOMP_EXCEPTION_NONE
#include "pats_ccomp_runtime2_dats.c"
#ifndef _ATS_CCOMP_RUNTIME_TRYWITH_NONE
#include "pats_ccomp_runtime_trywith.c"
#endif /* _ATS_CCOMP_RUNTIME_TRYWITH_NONE */
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE]
#endif /* _ATS_CCOMP_RUNTIME_NONE */

/*
** the [main] implementation
*/
int
main
(
int argc, char **argv, char **envp
) {
int err = 0 ;
_057_home_057_grad2_057_aren_057_workspace_057_Postiats_057_projects_057_org_056_ats_055_lang_056_postiats_056_jats_057_test_057_test01_056_dats__dynload() ;
ATSmainats_void_0(err) ;
return (err) ;
} /* end of [main] */

/* ****** ****** */

/* end-of-compilation-unit */
