/*
**
** The C code is generated by ATS/Postiats
** The compilation time is: 2013-7-15: 20h:10m
**
*/

/*
** include runtime header files
*/
#ifndef _ATS_CCOMP_HEADER_NONE
#include "pats_ccomp_config.h"
#include "pats_ccomp_basics.h"
#include "pats_ccomp_typedefs.h"
#include "pats_ccomp_instrset.h"
#include "pats_ccomp_memalloc.h"
#include "pats_ccomp_memalloca.h"
#include "pats_ccomp_exception.h"
#endif /* _ATS_CCOMP_HEADER_NONE */


/*
** include prelude cats files
*/
#ifndef _ATS_CCOMP_PRELUDE_NONE
//
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/memory.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/strptr.cats"
//
#include "prelude/CATS/filebas.cats"
//
#include "prelude/CATS/list.cats"
#include "prelude/CATS/option.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/arrayptr.cats"
#include "prelude/CATS/arrayref.cats"
#include "prelude/CATS/matrix.cats"
#include "prelude/CATS/matrixptr.cats"
//
#endif /* _ATS_CCOMP_PRELUDE_NONE */

/*
staload-prologues(beg)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/integer.dats: 1636(line=51, offs=1) -- 1675(line=51, offs=40)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/integer.dats: 26347(line=693, offs=1) -- 26378(line=693, offs=32)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/libc/SATS/stdlib.sats: 1379(line=35, offs=1) -- 1418(line=37, offs=3)
*/

#include "libc/CATS/stdlib.cats"
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/libc/SATS/stdlib.sats: 1814(line=54, offs=1) -- 1854(line=55, offs=33)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/string.dats: 1609(line=48, offs=1) -- 1648(line=48, offs=40)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/strptr.dats: 1609(line=48, offs=1) -- 1648(line=48, offs=40)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/strptr.dats: 1671(line=52, offs=1) -- 1718(line=52, offs=48)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/integer.dats: 1636(line=51, offs=1) -- 1675(line=51, offs=40)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/integer.dats: 26347(line=693, offs=1) -- 26378(line=693, offs=32)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/libc/SATS/stdlib.sats: 1379(line=35, offs=1) -- 1418(line=37, offs=3)
*/

#include "libc/CATS/stdlib.cats"
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/libc/SATS/stdlib.sats: 1814(line=54, offs=1) -- 1854(line=55, offs=33)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/pointer.dats: 1533(line=44, offs=1) -- 1572(line=44, offs=40)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/filebas.dats: 1613(line=48, offs=1) -- 1652(line=48, offs=40)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/filebas.dats: 1675(line=52, offs=1) -- 1722(line=52, offs=48)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/integer.dats: 1636(line=51, offs=1) -- 1675(line=51, offs=40)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/integer.dats: 26347(line=693, offs=1) -- 26378(line=693, offs=32)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/libc/SATS/stdlib.sats: 1379(line=35, offs=1) -- 1418(line=37, offs=3)
*/

#include "libc/CATS/stdlib.cats"
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/libc/SATS/stdlib.sats: 1814(line=54, offs=1) -- 1854(line=55, offs=33)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/filebas.dats: 1745(line=56, offs=1) -- 1783(line=56, offs=39)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/libc/SATS/stdio.sats: 1380(line=35, offs=1) -- 1418(line=37, offs=3)
*/

#include "libc/CATS/stdio.cats"
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/libc/SATS/stdio.sats: 1855(line=57, offs=1) -- 1897(line=59, offs=27)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/libc/sys/SATS/types.sats: 1380(line=35, offs=1) -- 1422(line=37, offs=3)
*/

#include "libc/sys/CATS/types.cats"
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/list.dats: 1533(line=44, offs=1) -- 1572(line=44, offs=40)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/list.dats: 1573(line=45, offs=1) -- 1619(line=45, offs=47)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/unsafe.dats: 1532(line=44, offs=1) -- 1566(line=44, offs=35)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/list_vt.dats: 1536(line=44, offs=1) -- 1575(line=44, offs=40)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/list_vt_mergesort.dats: 1546(line=44, offs=1) -- 1585(line=44, offs=40)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/list_vt_quicksort.dats: 1546(line=44, offs=1) -- 1585(line=44, offs=40)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/array.dats: 1534(line=44, offs=1) -- 1573(line=44, offs=40)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/array.dats: 1574(line=45, offs=1) -- 1616(line=45, offs=43)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/array_bsearch.dats: 1531(line=44, offs=1) -- 1570(line=44, offs=40)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/array_quicksort.dats: 1531(line=44, offs=1) -- 1570(line=44, offs=40)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/arrayptr.dats: 1532(line=44, offs=1) -- 1571(line=44, offs=40)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/arrayref.dats: 1532(line=44, offs=1) -- 1571(line=44, offs=40)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/matrix.dats: 1535(line=44, offs=1) -- 1574(line=44, offs=40)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/matrixptr.dats: 1538(line=44, offs=1) -- 1577(line=44, offs=40)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/matrixref.dats: 1538(line=44, offs=1) -- 1577(line=44, offs=40)
*/
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/unsafe.dats: 1532(line=44, offs=1) -- 1566(line=44, offs=35)
*/
/*
staload-prologues(end)
*/
/*
typedefs-for-tyrecs-and-tysums(beg)
*/
/*
typedefs-for-tyrecs-and-tysums(end)
*/
/*
dynconlst-declaration(beg)
*/
/*
dynconlst-declaration(end)
*/
/*
dyncstlst-declaration(beg)
*/
ATSdyncst_mac(atspre_arrayptr_make_arrpsz) ;
ATSdyncst_mac(atspre_assert_errmsg_bool0) ;
ATSdyncst_mac(atspre_add_ptr0_bsz) ;
ATSdyncst_mac(atspre_arrayptr_free) ;
/*
dyncstlst-declaration(end)
*/
/*
dynvalist-implementation(beg)
*/
/*
dynvalist-implementation(end)
*/
/*
exnconlst-declaration(beg)
*/
extern void the_atsexncon_initize (atstype_exncon *d2c, char *exnmsg) ;
/*
exnconlst-declaration(end)
*/
/*
assumelst-declaration(beg)
*/
/*
assumelst-declaration(end)
*/
ATSstaticdec()
atsvoid_t0ype
foo_0() ;

#if(0)
#if(0)
ATSglobaldec()
atstkind_t0ype(atstype_bool)
ATSLIB_056$prelude_eq_g0int_int$1(atstkind_t0ype(atstyvar_type(tk)), atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstaticdec()
atstkind_t0ype(atstype_bool)
ATSLIB_056$prelude_eq_g0int_int$1$1(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

#if(0)
#if(0)
ATSglobaldec()
atstyvar_type(a)
ATSLIB_056$prelude_arrayptr_get_at_gint$5(atsrefarg0_type(atstkind_type(atstype_ptrk)), atstkind_t0ype(atstyvar_type(tk))) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstaticdec()
atstkind_t0ype(atstype_int)
ATSLIB_056$prelude_arrayptr_get_at_gint$5$1(atsrefarg0_type(atstkind_type(atstype_ptrk)), atstkind_t0ype(atstype_int)) ;

#if(0)
#if(0)
ATSglobaldec()
atstkind_type(atstype_ptrk)
ATSLIB_056$prelude_ptr1_add_gint$7(atstkind_type(atstype_ptrk), atstkind_t0ype(atstyvar_type(tk))) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstaticdec()
atstkind_type(atstype_ptrk)
ATSLIB_056$prelude_ptr1_add_gint$7$1(atstkind_type(atstype_ptrk), atstkind_t0ype(atstype_int)) ;

#if(0)
#if(0)
ATSglobaldec()
atstkind_type(atstype_ptrk)
ATSLIB_056$prelude_ptr0_add_gint$9(atstkind_type(atstype_ptrk), atstkind_t0ype(atstyvar_type(tk))) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstaticdec()
atstkind_type(atstype_ptrk)
ATSLIB_056$prelude_ptr0_add_gint$9$1(atstkind_type(atstype_ptrk), atstkind_t0ype(atstype_int)) ;

#if(0)
#if(0)
ATSglobaldec()
atstyvar_type(a)
ATSLIB_056$prelude_056$unsafe_ptr0_get$13(atstkind_type(atstype_ptrk)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstaticdec()
atstkind_t0ype(atstype_int)
ATSLIB_056$prelude_056$unsafe_ptr0_get$13$1(atstkind_type(atstype_ptrk)) ;

ATSstaticdec()
atstkind_t0ype(atstype_bool)
ATSLIB_056$prelude_eq_g0int_int$1$2(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

ATSstaticdec()
atstkind_t0ype(atstype_int)
ATSLIB_056$prelude_arrayptr_get_at_gint$5$2(atsrefarg0_type(atstkind_type(atstype_ptrk)), atstkind_t0ype(atstype_int)) ;

ATSstaticdec()
atstkind_type(atstype_ptrk)
ATSLIB_056$prelude_ptr1_add_gint$7$2(atstkind_type(atstype_ptrk), atstkind_t0ype(atstype_int)) ;

ATSstaticdec()
atstkind_type(atstype_ptrk)
ATSLIB_056$prelude_ptr0_add_gint$9$2(atstkind_type(atstype_ptrk), atstkind_t0ype(atstype_int)) ;

ATSstaticdec()
atstkind_t0ype(atstype_int)
ATSLIB_056$prelude_056$unsafe_ptr0_get$13$2(atstkind_type(atstype_ptrk)) ;

ATSstaticdec()
atstkind_t0ype(atstype_bool)
ATSLIB_056$prelude_eq_g0int_int$1$3(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

ATSstaticdec()
atstkind_t0ype(atstype_int)
ATSLIB_056$prelude_arrayptr_get_at_gint$5$3(atsrefarg0_type(atstkind_type(atstype_ptrk)), atstkind_t0ype(atstype_int)) ;

ATSstaticdec()
atstkind_type(atstype_ptrk)
ATSLIB_056$prelude_ptr1_add_gint$7$3(atstkind_type(atstype_ptrk), atstkind_t0ype(atstype_int)) ;

ATSstaticdec()
atstkind_type(atstype_ptrk)
ATSLIB_056$prelude_ptr0_add_gint$9$3(atstkind_type(atstype_ptrk), atstkind_t0ype(atstype_int)) ;

ATSstaticdec()
atstkind_t0ype(atstype_int)
ATSLIB_056$prelude_056$unsafe_ptr0_get$13$3(atstkind_type(atstype_ptrk)) ;

#if(0)
ATSglobaldec()
atsvoid_t0ype
mainats_void_0() ;
#endif // end of [QUALIFIED]

/*
/home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/test15.dats: 52(line=6, offs=5) -- 227(line=13, offs=2)
*/
/*
local: 
global: foo_0$0(level=0)
local: 
global: 
*/
ATSstaticdec()
atsvoid_t0ype
foo_0()
{
/* tmpvardeclst(beg) */
ATStmpdec_void(tmpret0, atsvoid_t0ype) ;
ATStmpdec(tmp1, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp2, atstype_arrpsz) ;
ATStmpdec(tmp3, atstype_arrptr) ;
ATStmpdec_void(tmp4, atsvoid_t0ype) ;
ATStmpdec(tmp5, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp10, atstkind_t0ype(atstype_int)) ;
ATStmpdec_void(tmp29, atsvoid_t0ype) ;
ATStmpdec(tmp30, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp33, atstkind_t0ype(atstype_int)) ;
ATStmpdec_void(tmp43, atsvoid_t0ype) ;
ATStmpdec(tmp44, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp47, atstkind_t0ype(atstype_int)) ;
ATStmpdec_void(tmp57, atsvoid_t0ype) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_foo_0:
/*
letpush(beg)
*/
/*
ATSINStmpdec(tmp2)) ;
*/
ATSINSstore_arrpsz_asz(tmp2, 3) ;
ATSINSstore_arrpsz_ptr(tmp2, atstkind_t0ype(atstype_int), 3) ;
ATSINSmove_arrpsz_ptr(tmp3, tmp2) ;
ATSINSpmove(tmp3, atstkind_t0ype(atstype_int), ATSPMVi0nt(3)) ;
ATSINSupdate_ptrinc(tmp3, atstkind_t0ype(atstype_int)) ;
ATSINSpmove(tmp3, atstkind_t0ype(atstype_int), ATSPMVi0nt(4)) ;
ATSINSupdate_ptrinc(tmp3, atstkind_t0ype(atstype_int)) ;
ATSINSpmove(tmp3, atstkind_t0ype(atstype_int), ATSPMVi0nt(5)) ;
ATSINSmove(tmp1, atspre_arrayptr_make_arrpsz(tmp2)) ;
ATSINSmove(tmp10, ATSLIB_056$prelude_arrayptr_get_at_gint$5$1(ATSPMVrefarg0(tmp1), ATSPMVi0nt(0))) ;
ATSINSmove(tmp5, ATSLIB_056$prelude_eq_g0int_int$1$1(tmp10, ATSPMVi0nt(3))) ;
ATSINSmove_void(tmp4, atspre_assert_errmsg_bool0(tmp5, ATSCSTSPmyloc("/home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/test15.dats: 118(line=9, offs=10) -- 137(line=9, offs=29)"))) ;
ATSINSmove(tmp33, ATSLIB_056$prelude_arrayptr_get_at_gint$5$2(ATSPMVrefarg0(tmp1), ATSPMVi0nt(1))) ;
ATSINSmove(tmp30, ATSLIB_056$prelude_eq_g0int_int$1$2(tmp33, ATSPMVi0nt(4))) ;
ATSINSmove_void(tmp29, atspre_assert_errmsg_bool0(tmp30, ATSCSTSPmyloc("/home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/test15.dats: 148(line=10, offs=10) -- 167(line=10, offs=29)"))) ;
ATSINSmove(tmp47, ATSLIB_056$prelude_arrayptr_get_at_gint$5$3(ATSPMVrefarg0(tmp1), ATSPMVi0nt(2))) ;
ATSINSmove(tmp44, ATSLIB_056$prelude_eq_g0int_int$1$3(tmp47, ATSPMVi0nt(5))) ;
ATSINSmove_void(tmp43, atspre_assert_errmsg_bool0(tmp44, ATSCSTSPmyloc("/home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/test15.dats: 178(line=11, offs=10) -- 197(line=11, offs=29)"))) ;
ATSINSmove_void(tmp57, atspre_arrayptr_free(tmp1)) ;
/*
letpush(end)
*/

ATSINSmove_void(tmpret0, ATSempty()) ;
/*
INSletpop()
*/
/* funbodyinstrlst(end) */
ATSreturn_void(tmpret0) ;
} /* end of [foo_0] */

#if(0)
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/integer.dats: 27633(line=742, offs=14) -- 27673(line=742, offs=54)
*/
/*
local: 
global: eq_g0int_int$1$0(level=0)
local: 
global: 
*/
ATSglobaldec()
/*
imparg = tk(3260)
tmparg = S2Evar(tk(3260))
tmpsub = None()
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056$prelude_eq_g0int_int$1(atstkind_t0ype(atstyvar_type(tk)) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret6, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp7, atstkind_t0ype(atstyvar_type(tk))) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_eq_g0int_int:
ATSINSmove(tmp7, PMVtmpltcst(g0int2int<S2Eextkind(atstype_int), S2Evar(tk(3260))>)(arg1)) ;
ATSINSmove(tmpret6, PMVtmpltcst(g0int_eq<S2Evar(tk(3260))>)(arg0, tmp7)) ;
/* funbodyinstrlst(end) */
ATSreturn(tmpret6) ;
} /* end of [ATSLIB_056$prelude_eq_g0int_int$1] */
#endif // end of [TEMPLATE]

/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/integer.dats: 27633(line=742, offs=14) -- 27673(line=742, offs=54)
*/
/*
local: 
global: eq_g0int_int$1$1(level=1)
local: 
global: 
*/
ATSstaticdec()
/*
imparg = tk(3260)
tmparg = S2Evar(tk(3260))
tmpsub = Some(tk(3260) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056$prelude_eq_g0int_int$1$1(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmp6$1, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp7$1, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_eq_g0int_int:
ATSINSmove(tmp7$1, atspre_g0int2int_int_int(arg1)) ;
ATSINSmove(tmp6$1, atspre_g0int_eq_int(arg0, tmp7$1)) ;
/* funbodyinstrlst(end) */
ATSreturn(tmp6$1) ;
} /* end of [ATSLIB_056$prelude_eq_g0int_int$1$1] */

#if(0)
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/arrayptr.dats: 4515(line=219, offs=3) -- 4604(line=222, offs=4)
*/
/*
local: 
global: arrayptr_get_at_gint$5$0(level=0)
local: 
global: 
*/
ATSglobaldec()
/*
imparg = a(5249), tk(5250)
tmparg = S2Evar(a(5249)); S2Evar(tk(5250))
tmpsub = None()
*/
atstyvar_type(a)
ATSLIB_056$prelude_arrayptr_get_at_gint$5(atsrefarg0_type(atstkind_type(atstype_ptrk)) arg0, atstkind_t0ype(atstyvar_type(tk)) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret11, atstyvar_type(a)) ;
ATStmpdec(tmp12, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_arrayptr_get_at_gint:
/*
letpush(beg)
*/
/* (*nothing*) */
/*
letpush(end)
*/

ATSINSmove(tmp12, PMVtmpltcst(ptr1_add_gint<S2Evar(a(5249))><S2Evar(tk(5250))>)(ATSPMVcastfn(arrayptr2ptr, atstkind_type(atstype_ptrk), ATSPMVrefarg0(arg0)), arg1)) ;
ATSINSmove(tmpret11, PMVtmpltcst(ptr0_get<S2Evar(a(5249))>)(tmp12)) ;
/*
INSletpop()
*/
/* funbodyinstrlst(end) */
ATSreturn(tmpret11) ;
} /* end of [ATSLIB_056$prelude_arrayptr_get_at_gint$5] */
#endif // end of [TEMPLATE]

/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/arrayptr.dats: 4515(line=219, offs=3) -- 4604(line=222, offs=4)
*/
/*
local: 
global: arrayptr_get_at_gint$5$1(level=1)
local: 
global: 
*/
ATSstaticdec()
/*
imparg = a(5249), tk(5250)
tmparg = S2Evar(a(5249)); S2Evar(tk(5250))
tmpsub = Some(a(5249) -> S2Eapp(S2Ecst(g0int_t0ype); S2Ecst(int_kind)); tk(5250) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_int)
ATSLIB_056$prelude_arrayptr_get_at_gint$5$1(atsrefarg0_type(atstkind_type(atstype_ptrk)) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmp11$1, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp12$1, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_arrayptr_get_at_gint:
/*
letpush(beg)
*/
/* (*nothing*) */
/*
letpush(end)
*/

ATSINSmove(tmp12$1, ATSLIB_056$prelude_ptr1_add_gint$7$1(ATSPMVcastfn(arrayptr2ptr, atstkind_type(atstype_ptrk), ATSPMVrefarg0(arg0)), arg1)) ;
ATSINSmove(tmp11$1, ATSLIB_056$prelude_056$unsafe_ptr0_get$13$1(tmp12$1)) ;
/*
INSletpop()
*/
/* funbodyinstrlst(end) */
ATSreturn(tmp11$1) ;
} /* end of [ATSLIB_056$prelude_arrayptr_get_at_gint$5$1] */

#if(0)
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/pointer.dats: 2518(line=93, offs=22) -- 2585(line=94, offs=59)
*/
/*
local: 
global: ptr1_add_gint$7$0(level=0)
local: 
global: 
*/
ATSglobaldec()
/*
imparg = a(3542), tk(3543)
tmparg = S2Evar(a(3542)); S2Evar(tk(3543))
tmpsub = None()
*/
atstkind_type(atstype_ptrk)
ATSLIB_056$prelude_ptr1_add_gint$7(atstkind_type(atstype_ptrk) arg0, atstkind_t0ype(atstyvar_type(tk)) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret15, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp16, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_ptr1_add_gint:
ATSINSmove(tmp16, PMVtmpltcst(ptr0_add_gint<S2Evar(a(3542))><S2Evar(tk(3543))>)(arg0, arg1)) ;
ATSINSmove(tmpret15, ATSPMVcastfn(cast, atstkind_type(atstype_ptrk), tmp16)) ;
/* funbodyinstrlst(end) */
ATSreturn(tmpret15) ;
} /* end of [ATSLIB_056$prelude_ptr1_add_gint$7] */
#endif // end of [TEMPLATE]

/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/pointer.dats: 2518(line=93, offs=22) -- 2585(line=94, offs=59)
*/
/*
local: 
global: ptr1_add_gint$7$1(level=2)
local: 
global: 
*/
ATSstaticdec()
/*
imparg = a(3542), tk(3543)
tmparg = S2Evar(a(3542)); S2Evar(tk(3543))
tmpsub = Some(a(3542) -> S2Eapp(S2Ecst(g0int_t0ype); S2Ecst(int_kind)); tk(3543) -> S2Eextkind(atstype_int))
*/
atstkind_type(atstype_ptrk)
ATSLIB_056$prelude_ptr1_add_gint$7$1(atstkind_type(atstype_ptrk) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmp15$1, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp16$1, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_ptr1_add_gint:
ATSINSmove(tmp16$1, ATSLIB_056$prelude_ptr0_add_gint$9$1(arg0, arg1)) ;
ATSINSmove(tmp15$1, ATSPMVcastfn(cast, atstkind_type(atstype_ptrk), tmp16$1)) ;
/* funbodyinstrlst(end) */
ATSreturn(tmp15$1) ;
} /* end of [ATSLIB_056$prelude_ptr1_add_gint$7$1] */

#if(0)
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/pointer.dats: 1952(line=68, offs=15) -- 2005(line=69, offs=45)
*/
/*
local: 
global: ptr0_add_gint$9$0(level=0)
local: 
global: 
*/
ATSglobaldec()
/*
imparg = a(3528), tk(3529)
tmparg = S2Evar(a(3528)); S2Evar(tk(3529))
tmpsub = None()
*/
atstkind_type(atstype_ptrk)
ATSLIB_056$prelude_ptr0_add_gint$9(atstkind_type(atstype_ptrk) arg0, atstkind_t0ype(atstyvar_type(tk)) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret19, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp20, atstkind_t0ype(atstype_size)) ;
ATStmpdec(tmp21, atstkind_t0ype(atstype_size)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_ptr0_add_gint:
ATSINSmove(tmp21, PMVtmpltcst(g0int2uint<S2Evar(tk(3529)), S2Eextkind(atstype_size)>)(arg1)) ;
ATSINSmove(tmp20, PMVtmpltcst(g0uint_mul<S2Eextkind(atstype_size)>)(tmp21, ATSPMVsizeof(atstyvar_type(a)))) ;
ATSINSmove(tmpret19, atspre_add_ptr0_bsz(arg0, tmp20)) ;
/* funbodyinstrlst(end) */
ATSreturn(tmpret19) ;
} /* end of [ATSLIB_056$prelude_ptr0_add_gint$9] */
#endif // end of [TEMPLATE]

/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/pointer.dats: 1952(line=68, offs=15) -- 2005(line=69, offs=45)
*/
/*
local: 
global: ptr0_add_gint$9$1(level=3)
local: 
global: 
*/
ATSstaticdec()
/*
imparg = a(3528), tk(3529)
tmparg = S2Evar(a(3528)); S2Evar(tk(3529))
tmpsub = Some(a(3528) -> S2Eapp(S2Ecst(g0int_t0ype); S2Ecst(int_kind)); tk(3529) -> S2Eextkind(atstype_int))
*/
atstkind_type(atstype_ptrk)
ATSLIB_056$prelude_ptr0_add_gint$9$1(atstkind_type(atstype_ptrk) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmp19$1, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp20$1, atstkind_t0ype(atstype_size)) ;
ATStmpdec(tmp21$1, atstkind_t0ype(atstype_size)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_ptr0_add_gint:
ATSINSmove(tmp21$1, atspre_g0int2uint_int_size(arg1)) ;
ATSINSmove(tmp20$1, atspre_g0uint_mul_size(tmp21$1, ATSPMVsizeof(atstkind_t0ype(atstype_int)))) ;
ATSINSmove(tmp19$1, atspre_add_ptr0_bsz(arg0, tmp20$1)) ;
/* funbodyinstrlst(end) */
ATSreturn(tmp19$1) ;
} /* end of [ATSLIB_056$prelude_ptr0_add_gint$9$1] */

#if(0)
/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/unsafe.dats: 1621(line=51, offs=3) -- 1834(line=59, offs=2)
*/
/*
local: 
global: ptr0_get$13$0(level=0)
local: 
global: 
*/
ATSglobaldec()
/*
imparg = a(3798)
tmparg = S2Evar(a(3798))
tmpsub = None()
*/
atstyvar_type(a)
ATSLIB_056$prelude_056$unsafe_ptr0_get$13(atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret25, atstyvar_type(a)) ;
ATStmpdec(tmp26, atstyvar_type(a)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_ptr0_get:
/*
letpush(beg)
*/
/* (*nothing*) */
/* (*nothing*) */
ATSINSmove(tmp26, ATSderef(ATSPMVcastfn(g1ofg0_ptr, atstkind_type(atstype_ptrk), arg0), atstyvar_type(a))) ;
/* (*nothing*) */
/*
letpush(end)
*/

ATSINSmove(tmpret25, tmp26) ;
/*
INSletpop()
*/
/* funbodyinstrlst(end) */
ATSreturn(tmpret25) ;
} /* end of [ATSLIB_056$prelude_056$unsafe_ptr0_get$13] */
#endif // end of [TEMPLATE]

/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/unsafe.dats: 1621(line=51, offs=3) -- 1834(line=59, offs=2)
*/
/*
local: 
global: ptr0_get$13$1(level=2)
local: 
global: 
*/
ATSstaticdec()
/*
imparg = a(3798)
tmparg = S2Evar(a(3798))
tmpsub = Some(a(3798) -> S2Eapp(S2Ecst(g0int_t0ype); S2Ecst(int_kind)))
*/
atstkind_t0ype(atstype_int)
ATSLIB_056$prelude_056$unsafe_ptr0_get$13$1(atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmp25$1, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp26$1, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_ptr0_get:
/*
letpush(beg)
*/
/* (*nothing*) */
/* (*nothing*) */
ATSINSmove(tmp26$1, ATSderef(ATSPMVcastfn(g1ofg0_ptr, atstkind_type(atstype_ptrk), arg0), atstkind_t0ype(atstype_int))) ;
/* (*nothing*) */
/*
letpush(end)
*/

ATSINSmove(tmp25$1, tmp26$1) ;
/*
INSletpop()
*/
/* funbodyinstrlst(end) */
ATSreturn(tmp25$1) ;
} /* end of [ATSLIB_056$prelude_056$unsafe_ptr0_get$13$1] */

/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/integer.dats: 27633(line=742, offs=14) -- 27673(line=742, offs=54)
*/
/*
local: 
global: eq_g0int_int$1$2(level=1)
local: 
global: 
*/
ATSstaticdec()
/*
imparg = tk(3260)
tmparg = S2Evar(tk(3260))
tmpsub = Some(tk(3260) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056$prelude_eq_g0int_int$1$2(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmp6$2, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp7$2, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_eq_g0int_int:
ATSINSmove(tmp7$2, atspre_g0int2int_int_int(arg1)) ;
ATSINSmove(tmp6$2, atspre_g0int_eq_int(arg0, tmp7$2)) ;
/* funbodyinstrlst(end) */
ATSreturn(tmp6$2) ;
} /* end of [ATSLIB_056$prelude_eq_g0int_int$1$2] */

/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/arrayptr.dats: 4515(line=219, offs=3) -- 4604(line=222, offs=4)
*/
/*
local: 
global: arrayptr_get_at_gint$5$2(level=1)
local: 
global: 
*/
ATSstaticdec()
/*
imparg = a(5249), tk(5250)
tmparg = S2Evar(a(5249)); S2Evar(tk(5250))
tmpsub = Some(a(5249) -> S2Eapp(S2Ecst(g0int_t0ype); S2Ecst(int_kind)); tk(5250) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_int)
ATSLIB_056$prelude_arrayptr_get_at_gint$5$2(atsrefarg0_type(atstkind_type(atstype_ptrk)) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmp11$2, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp12$2, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_arrayptr_get_at_gint:
/*
letpush(beg)
*/
/* (*nothing*) */
/*
letpush(end)
*/

ATSINSmove(tmp12$2, ATSLIB_056$prelude_ptr1_add_gint$7$2(ATSPMVcastfn(arrayptr2ptr, atstkind_type(atstype_ptrk), ATSPMVrefarg0(arg0)), arg1)) ;
ATSINSmove(tmp11$2, ATSLIB_056$prelude_056$unsafe_ptr0_get$13$2(tmp12$2)) ;
/*
INSletpop()
*/
/* funbodyinstrlst(end) */
ATSreturn(tmp11$2) ;
} /* end of [ATSLIB_056$prelude_arrayptr_get_at_gint$5$2] */

/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/pointer.dats: 2518(line=93, offs=22) -- 2585(line=94, offs=59)
*/
/*
local: 
global: ptr1_add_gint$7$2(level=2)
local: 
global: 
*/
ATSstaticdec()
/*
imparg = a(3542), tk(3543)
tmparg = S2Evar(a(3542)); S2Evar(tk(3543))
tmpsub = Some(a(3542) -> S2Eapp(S2Ecst(g0int_t0ype); S2Ecst(int_kind)); tk(3543) -> S2Eextkind(atstype_int))
*/
atstkind_type(atstype_ptrk)
ATSLIB_056$prelude_ptr1_add_gint$7$2(atstkind_type(atstype_ptrk) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmp15$2, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp16$2, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_ptr1_add_gint:
ATSINSmove(tmp16$2, ATSLIB_056$prelude_ptr0_add_gint$9$2(arg0, arg1)) ;
ATSINSmove(tmp15$2, ATSPMVcastfn(cast, atstkind_type(atstype_ptrk), tmp16$2)) ;
/* funbodyinstrlst(end) */
ATSreturn(tmp15$2) ;
} /* end of [ATSLIB_056$prelude_ptr1_add_gint$7$2] */

/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/pointer.dats: 1952(line=68, offs=15) -- 2005(line=69, offs=45)
*/
/*
local: 
global: ptr0_add_gint$9$2(level=3)
local: 
global: 
*/
ATSstaticdec()
/*
imparg = a(3528), tk(3529)
tmparg = S2Evar(a(3528)); S2Evar(tk(3529))
tmpsub = Some(a(3528) -> S2Eapp(S2Ecst(g0int_t0ype); S2Ecst(int_kind)); tk(3529) -> S2Eextkind(atstype_int))
*/
atstkind_type(atstype_ptrk)
ATSLIB_056$prelude_ptr0_add_gint$9$2(atstkind_type(atstype_ptrk) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmp19$2, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp20$2, atstkind_t0ype(atstype_size)) ;
ATStmpdec(tmp21$2, atstkind_t0ype(atstype_size)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_ptr0_add_gint:
ATSINSmove(tmp21$2, atspre_g0int2uint_int_size(arg1)) ;
ATSINSmove(tmp20$2, atspre_g0uint_mul_size(tmp21$2, ATSPMVsizeof(atstkind_t0ype(atstype_int)))) ;
ATSINSmove(tmp19$2, atspre_add_ptr0_bsz(arg0, tmp20$2)) ;
/* funbodyinstrlst(end) */
ATSreturn(tmp19$2) ;
} /* end of [ATSLIB_056$prelude_ptr0_add_gint$9$2] */

/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/unsafe.dats: 1621(line=51, offs=3) -- 1834(line=59, offs=2)
*/
/*
local: 
global: ptr0_get$13$2(level=2)
local: 
global: 
*/
ATSstaticdec()
/*
imparg = a(3798)
tmparg = S2Evar(a(3798))
tmpsub = Some(a(3798) -> S2Eapp(S2Ecst(g0int_t0ype); S2Ecst(int_kind)))
*/
atstkind_t0ype(atstype_int)
ATSLIB_056$prelude_056$unsafe_ptr0_get$13$2(atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmp25$2, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp26$2, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_ptr0_get:
/*
letpush(beg)
*/
/* (*nothing*) */
/* (*nothing*) */
ATSINSmove(tmp26$2, ATSderef(ATSPMVcastfn(g1ofg0_ptr, atstkind_type(atstype_ptrk), arg0), atstkind_t0ype(atstype_int))) ;
/* (*nothing*) */
/*
letpush(end)
*/

ATSINSmove(tmp25$2, tmp26$2) ;
/*
INSletpop()
*/
/* funbodyinstrlst(end) */
ATSreturn(tmp25$2) ;
} /* end of [ATSLIB_056$prelude_056$unsafe_ptr0_get$13$2] */

/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/integer.dats: 27633(line=742, offs=14) -- 27673(line=742, offs=54)
*/
/*
local: 
global: eq_g0int_int$1$3(level=1)
local: 
global: 
*/
ATSstaticdec()
/*
imparg = tk(3260)
tmparg = S2Evar(tk(3260))
tmpsub = Some(tk(3260) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056$prelude_eq_g0int_int$1$3(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmp6$3, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp7$3, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_eq_g0int_int:
ATSINSmove(tmp7$3, atspre_g0int2int_int_int(arg1)) ;
ATSINSmove(tmp6$3, atspre_g0int_eq_int(arg0, tmp7$3)) ;
/* funbodyinstrlst(end) */
ATSreturn(tmp6$3) ;
} /* end of [ATSLIB_056$prelude_eq_g0int_int$1$3] */

/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/arrayptr.dats: 4515(line=219, offs=3) -- 4604(line=222, offs=4)
*/
/*
local: 
global: arrayptr_get_at_gint$5$3(level=1)
local: 
global: 
*/
ATSstaticdec()
/*
imparg = a(5249), tk(5250)
tmparg = S2Evar(a(5249)); S2Evar(tk(5250))
tmpsub = Some(a(5249) -> S2Eapp(S2Ecst(g0int_t0ype); S2Ecst(int_kind)); tk(5250) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_int)
ATSLIB_056$prelude_arrayptr_get_at_gint$5$3(atsrefarg0_type(atstkind_type(atstype_ptrk)) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmp11$3, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp12$3, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_arrayptr_get_at_gint:
/*
letpush(beg)
*/
/* (*nothing*) */
/*
letpush(end)
*/

ATSINSmove(tmp12$3, ATSLIB_056$prelude_ptr1_add_gint$7$3(ATSPMVcastfn(arrayptr2ptr, atstkind_type(atstype_ptrk), ATSPMVrefarg0(arg0)), arg1)) ;
ATSINSmove(tmp11$3, ATSLIB_056$prelude_056$unsafe_ptr0_get$13$3(tmp12$3)) ;
/*
INSletpop()
*/
/* funbodyinstrlst(end) */
ATSreturn(tmp11$3) ;
} /* end of [ATSLIB_056$prelude_arrayptr_get_at_gint$5$3] */

/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/pointer.dats: 2518(line=93, offs=22) -- 2585(line=94, offs=59)
*/
/*
local: 
global: ptr1_add_gint$7$3(level=2)
local: 
global: 
*/
ATSstaticdec()
/*
imparg = a(3542), tk(3543)
tmparg = S2Evar(a(3542)); S2Evar(tk(3543))
tmpsub = Some(a(3542) -> S2Eapp(S2Ecst(g0int_t0ype); S2Ecst(int_kind)); tk(3543) -> S2Eextkind(atstype_int))
*/
atstkind_type(atstype_ptrk)
ATSLIB_056$prelude_ptr1_add_gint$7$3(atstkind_type(atstype_ptrk) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmp15$3, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp16$3, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_ptr1_add_gint:
ATSINSmove(tmp16$3, ATSLIB_056$prelude_ptr0_add_gint$9$3(arg0, arg1)) ;
ATSINSmove(tmp15$3, ATSPMVcastfn(cast, atstkind_type(atstype_ptrk), tmp16$3)) ;
/* funbodyinstrlst(end) */
ATSreturn(tmp15$3) ;
} /* end of [ATSLIB_056$prelude_ptr1_add_gint$7$3] */

/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/pointer.dats: 1952(line=68, offs=15) -- 2005(line=69, offs=45)
*/
/*
local: 
global: ptr0_add_gint$9$3(level=3)
local: 
global: 
*/
ATSstaticdec()
/*
imparg = a(3528), tk(3529)
tmparg = S2Evar(a(3528)); S2Evar(tk(3529))
tmpsub = Some(a(3528) -> S2Eapp(S2Ecst(g0int_t0ype); S2Ecst(int_kind)); tk(3529) -> S2Eextkind(atstype_int))
*/
atstkind_type(atstype_ptrk)
ATSLIB_056$prelude_ptr0_add_gint$9$3(atstkind_type(atstype_ptrk) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmp19$3, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp20$3, atstkind_t0ype(atstype_size)) ;
ATStmpdec(tmp21$3, atstkind_t0ype(atstype_size)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_ptr0_add_gint:
ATSINSmove(tmp21$3, atspre_g0int2uint_int_size(arg1)) ;
ATSINSmove(tmp20$3, atspre_g0uint_mul_size(tmp21$3, ATSPMVsizeof(atstkind_t0ype(atstype_int)))) ;
ATSINSmove(tmp19$3, atspre_add_ptr0_bsz(arg0, tmp20$3)) ;
/* funbodyinstrlst(end) */
ATSreturn(tmp19$3) ;
} /* end of [ATSLIB_056$prelude_ptr0_add_gint$9$3] */

/*
/home/grad2/aren/workspace/Postiats/ATS-Postiats/prelude/DATS/unsafe.dats: 1621(line=51, offs=3) -- 1834(line=59, offs=2)
*/
/*
local: 
global: ptr0_get$13$3(level=2)
local: 
global: 
*/
ATSstaticdec()
/*
imparg = a(3798)
tmparg = S2Evar(a(3798))
tmpsub = Some(a(3798) -> S2Eapp(S2Ecst(g0int_t0ype); S2Ecst(int_kind)))
*/
atstkind_t0ype(atstype_int)
ATSLIB_056$prelude_056$unsafe_ptr0_get$13$3(atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmp25$3, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp26$3, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_ptr0_get:
/*
letpush(beg)
*/
/* (*nothing*) */
/* (*nothing*) */
ATSINSmove(tmp26$3, ATSderef(ATSPMVcastfn(g1ofg0_ptr, atstkind_type(atstype_ptrk), arg0), atstkind_t0ype(atstype_int))) ;
/* (*nothing*) */
/*
letpush(end)
*/

ATSINSmove(tmp25$3, tmp26$3) ;
/*
INSletpop()
*/
/* funbodyinstrlst(end) */
ATSreturn(tmp25$3) ;
} /* end of [ATSLIB_056$prelude_056$unsafe_ptr0_get$13$3] */

/*
/home/grad2/aren/workspace/Postiats/projects/org.ats-lang.postiats.jats/test/test15.dats: 261(line=15, offs=17) -- 272(line=15, offs=28)
*/
/*
local: foo_0$0(level=0)
global: foo_0$0(level=0), mainats_void_0$25$0(level=0)
local: 
global: 
*/
ATSglobaldec()
atsvoid_t0ype
mainats_void_0()
{
/* tmpvardeclst(beg) */
ATStmpdec_void(tmpret58, atsvoid_t0ype) ;
/* tmpvardeclst(end) */
/* funbodyinstrlst(beg) */
__patsflab_main_void_0:
ATSINSmove_void(tmpret58, foo_0()) ;
/* funbodyinstrlst(end) */
ATSreturn_void(tmpret58) ;
} /* end of [mainats_void_0] */


/*
** for initialization(dynloading)
*/
atsvoid_t0ype
_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$projects_057$org_056$ats_055$lang_056$postiats_056$jats_057$test_057$test15_056$dats__dynload()
{
ATSdynload0(
_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$projects_057$org_056$ats_055$lang_056$postiats_056$jats_057$test_057$test15_056$dats__dynloadflag
) ;
ATSif(
ATSCKiseqz(
_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$projects_057$org_056$ats_055$lang_056$postiats_056$jats_057$test_057$test15_056$dats__dynloadflag
)
) ATSthen() {
ATSdynloadset(_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$projects_057$org_056$ats_055$lang_056$postiats_056$jats_057$test_057$test15_056$dats__dynloadflag) ;
/*
dynexnlst-initize(beg)
*/
/*
dynexnlst-initize(end)
*/
} /* ATSendif */
ATSreturn_void() ;
} /* end of [*_dynload] */

/*
** the ATS runtime
*/
#ifndef _ATS_CCOMP_RUNTIME_NONE
#include "pats_ccomp_runtime.c"
#include "pats_ccomp_runtime2_dats.c"
#include "pats_ccomp_runtime_trywith.c"
#endif /* _ATS_CCOMP_RUNTIME_NONE */

/*
** the [main] implementation
*/
int
main
(
int argc, char **argv, char **envp
) {
int err = 0 ;
_057$home_057$grad2_057$aren_057$workspace_057$Postiats_057$projects_057$org_056$ats_055$lang_056$postiats_056$jats_057$test_057$test15_056$dats__dynload() ;
ATSmainats_void_0(err) ;
return (err) ;
} /* end of [main] */
